### ISSUE TITLE
会場を歩いてURGのデータを収集する

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#1]
第一回試走会の日にURGのデータを収集してください。

**Comment by DaikiMaekawa** [comment]
@ximo112 正常に動作しているか確認しながらデータを集めた方がいいと思うので、できればマップを作りながら会場を移動してください。

やり方は以下のURLを参照
http://daikimaekawa.github.io/ros/2014/04/14/HectorSLAM02/

**Comment by DaikiMaekawa** [comment]
@ximo112 ROSの使い方でわからないことがあれば遠慮なく質問してくださいね。

**Comment by ximomoi** [comment]
@DaikiMaekawa 　分かりました、よろしくおねがいします。

**Comment by ximomoi** [comment]
・ROS indigoのインストール完了

・URGのusb接続認識がうまく行かない、エラーが出てしまった
[ERROR] [1404204906.288069715]: Exception thrown while opening Hokuyo.
Failed to open port: /dev/ttyACM0. No such file or directory (errno = 2). The requested port does not exist. Is the hokuyo connected? Was the port name misspelled? (in hokuyo::laser::open) You may find further details at http://www.ros.org/wiki/hokuyo_node/Troubleshooting

**Comment by DaikiMaekawa** [comment]
以下のコマンドを実行してその結果を貼り付けてください

```
$ ls -l /dev/ttyACM*
```

**Comment by ximomoi** [comment]
この様になりました

```
$ ls -l /dev/ttyACM*
ls: /dev/ttyACM* にアクセスできません: そのようなファイルやディレクトリはありません
```

**Comment by DaikiMaekawa** [comment]
/dev以下に存在しないのは妙ですね :sweat: 
電源が入った状態のURGがPCに接続されていますか？

**Comment by ximomoi** [comment]
すみません、バッテリーにつなぎ忘れていたようでした

```
 $ ls -l /dev/ttyACM*
 crw-rw---- 1 root dialout 166, 0  7月  2 12:18 /dev/ttyACM0
```

**Comment by ximomoi** [comment]
```
$ roslaunch hector_hokuyo.launch
```

上記を実行した結果このような得られました。 

```
[ERROR] [1404378639.381452173]: Exception thrown while opening Hokuyo.
Failed to open port: /dev/ttyACM0. Permission denied (errno = 13). You probably don't have   
premission to open the port for reading and writing. (in hokuyo::laser::open) You may find further 
details at http://www.ros.org/wiki/hokuyo_node/Troubleshooting
```

**Comment by ghost** [comment]
/dev/ttyACM0に対して読み書きする権限がないのが問題だから

```
sudo gpasswd -a ユーザ名 dialout 
```

で、アクセスできるグループに自分自身を追加してからもう一回実行。
もしそれでダメだったら一旦ログアウトしてみて。
どういうことかについてはunixとかlinuxとか権限とかパーミッションとか適当に組み合わあせてググって

**Comment by ximomoi** [comment]
```
 $ sudo gpasswd -a ユーザ名 dialout 
```

を実行して

```
 $ roslaunch hector_hokuyo.launch
```

を実行した結果になります。

```
 [ERROR] [1404436440.637906585]: The plugin failed to load for some reason. Error: According 
 to  the loaded plugin descriptions the class hector_geotiff_plugins/TrajectoryMapWriter with base 
 class type hector_geotiff::MapWriterPluginInterface does not exist. Declared types are 
```

**Comment by DaikiMaekawa** [comment]
どうやら必要なパッケージが足りていないようですね。
以下のコマンドを実行してください。

``` sh
$ sudo aptitude install ros-indigo-hector-geotiff ros-indigo-hector-geotiff-plugins
```

**Comment by ximomoi** [comment]
コマンドを実行し、roslaunch hector_hokuyo.launchを実行しました。

```
 [ERROR] [1404446334.409353193]: Exception thrown while opening Hokuyo.
 timeout reached (in hokuyo::laser::laserReadline) You may find further details at  
 http://www.ros.org/wiki/hokuyo_node/Troubleshooting
```

**Comment by DaikiMaekawa** [comment]
なるほど、以下のコマンドを実行してください。

``` sh
$ sudo chmod a+rw /dev/ttyACM0
```

**Comment by ximomoi** [comment]
試しに2号館18Fのマッピングを行いました。

![screenshot from 2014-07-08 16 17 44](https://cloud.githubusercontent.com/assets/7301098/3507086/1c227f18-067a-11e4-9f4d-5e4bdad922a4.png)

**Comment by DaikiMaekawa** [comment]
無事に動作したようですね。
以下のコマンドで結果を保存できますので試してみてください。

``` sh
$ rostopic pub syscommand std_msgs/String "savegeotiff"
```

**Comment by DaikiMaekawa** [comment]
あと、動かしながらバグファイルを生成して欲しいです。
とりあえず全部のトピックを保存してくれればいいよ。

``` sh
$ rosbag record -a
```

レコード終了はCtrl＋C

**Comment by ximomoi** [comment]
バグファイルを上記のコマンドで生成し.bagファイルがあることを確認したのですが

```
 $ rosbag info
```

で見れなかったのですが大丈夫なのでしょうか？

**Comment by DaikiMaekawa** [comment]
見れないというのはバグファイルが読み込めないということでしょうか？

``` sh
$ rosbag info <name>.bag
```

ちゃんとファイルを指定していますか

**Comment by ximomoi** [comment]
うまく見つけられていないみたいです。

```
 ~/src/hector-slam-example$ rosbag info <2014-07-11-22-43-49>.bag
 bash: 2014-07-11-22-43-49: そのようなファイルやディレクトリはありません
```

![screenshot from 2014-07-11 23 16 33](https://cloud.githubusercontent.com/assets/7301098/3553678/326c5418-0906-11e4-87b8-637236e8d60c.png)

**Comment by DaikiMaekawa** [comment]
<>はいりません。　ファイル名をそのままコマンドの引数に渡してください。

**Comment by ximomoi** [comment]
できました。
ありがとうございます。

**Comment by ximomoi** [comment]
mapの辺の最大を変更する方法はあるのでしょうか？

**Comment by DaikiMaekawa** [comment]
mapサイズを10000に変更して第二回試走会でデータを収集しました。
結果、大まかな地図を作成できましたがランドマークが少ない開けた場所で地図が歪んでいます。

**Comment by DaikiMaekawa** [comment]
次回の試走会はt-frogにURGを搭載しオドメトリを使ってSLAMを動作させるべきでしょう。

**Comment by DaikiMaekawa** [comment]
T-frogにURGを搭載して無事動作を確認したため、今後は機体を走らせてデータを収集する
