### ISSUE TITLE
T-frogをジョイスティックで制御可能にする

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#10]
記録走行時にはマニュアルで動かす必要があるのでT-frogをジョイスティックに対応させる。

**Comment by DaikiMaekawa** [comment]
研究室でELECOM製の有線ジョイスティックを発見したため、これに対応させるためのプログラムを作成する。

**Comment by yasuohayashibara** [comment]
アナログを使用するのであれば，ELECOMはあまりおすすめしません．LOGICOOLがお勧めです．
＃ジョイスティックを倒す角度と値のリニアリティに問題がある場合が多いです．
立て替え払いで購入して構いません．

**Comment by DaikiMaekawa** [comment]
@yasuohayashibara 簡単そうなので既に実装してしまいました。
https://www.youtube.com/watch?v=SKyF_GOkttc&feature=youtu.be

今のところ、ELECOMでもあまり問題は感じません。

**Comment by DaikiMaekawa** [comment]
もちろんシミュレータ上のモデルも同様にジョイスティックで動作させることが可能です。
目的は達成したのでこのタスクは閉じます。

**Comment by DaikiMaekawa** [comment]
台車を移動させる際の移動速度が気になったので、記録走行用とは別にR１ボタンを押すことで0.9m/sまで速度を上昇させるブーストモードを実装しました。
https://github.com/open-rdc/t_frog_driver/pull/4
