### ISSUE TITLE
The behavior regarding the waypoints has not met the expected level.

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#111]
試験走行時の動画を拝見しましたが、ウェイポイントの切り替え時の挙動があまり好ましくありませんでした。
ウェイポイントの切り替え判定に使用する距離の閾値が厳しすぎるため発生していると思いますので、パラメータの調整をすることをおすすめします。

**Comment by iou16** [comment]
waypointの通過判定をする距離(dist_err)を0.5から0.8に変更したところ，waypoint通過時に機体を左右に振るような動作がなくなり非常にスムーズに走行することを実機で確認．

**Comment by iou16** [comment]
現在、i cart-minのリポジトリに対するプッシュ権限がないと思われるので，i cart-miniリポジトリのwaypoints_nav.cppにも変更を反映していただけると幸いです．

**Comment by DaikiMaekawa** [comment]
基本的にフォークする手間が増えるだけでプルリクを送ることは出来ます。 私がやっても良いですが、練習も兼ねて修正は @iou16 の方でやってもらってもよろしいですか?

**Comment by iou16** [comment]
@DaikiMaekawa 了解しました

**Comment by DaikiMaekawa** [comment]
masterにマージしました。
