### ISSUE TITLE
リカバリ動作の検証

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#114]

**Comment by DaikiMaekawa** [comment]
何をどのように検証するのか書いておくことをおすすめします。 @ximo112

**Comment by ximomoi** [comment]
2号館3階でnav_static_map.launchを実行し、経路を遮るようにしてロボットを囲みrecoveryを動作させました

*bagfile
http://www.hayashibara-lab.it-chiba.ac.jp/member/bags/orne_recovery_verification.bag

*動画
https://youtu.be/TDekGy7BvFs

**Comment by DaikiMaekawa** [comment]
@ximo112 動画を確認しました。 waypoints_navは一定時間毎にゴールポジションをmove_baseに送るようにしていますので、そちらで試していただいてもよろしいですか? 去年はこの修正を入れることでリカバリ失敗後も動き続けるようにしてしました。

**Comment by ximomoi** [comment]
waypoints_navの動作になります

*bagfile
http://www.hayashibara-lab.it-chiba.ac.jp/member/bags/orne_recovery_verification_(waypoints_nav).bag
*動画
https://youtu.be/4a6RyapT3hs

**Comment by DaikiMaekawa** [comment]
問題無さそうですね。 @ximo112 何か気付いた点などありますか?

**Comment by ximomoi** [comment]
waypoints_nav時の動作は特に問題は感じませんでした。
少し気になる点として、突然前方に障害物が現れた際に少しバックすることがあったのですが、これはローカルコストマップ上でコストの沼に入った時、後方にコストが無いと判断された場合に起こる動作なのでしょうか？

**Comment by DaikiMaekawa** [comment]
後方移動の優先度は低いですが、0には設定していないので前方の候補が全て無くなった場合にバックする挙動は発生します。

**Comment by DaikiMaekawa** [comment]
waypoints_navに以前実装したmove_baseの失敗検出処理がうまく働くことにより、自律移動は継続可能であることがわかったため閉じます。
