### ISSUE TITLE
スタート/リスタート時にコストを消したい

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#126]
/syscommandで"start"や"restart"を送った時点でコストをクリアしてスムーズにスタートするようにしたほうが良い気がする

**Comment by DaikiMaekawa** [comment]
@Nasupl 運用でカバーできませんか? どのような問題が起きているのか報告していただけると助かります。

**Comment by Nasupl** [comment]
特にスタート時に、前のチームが直前に出走している場合、その前にplay_waypoints_navなどを立ち上げているとスタート地点がコストまみれでリカバリ動作をしてからスタートすることになり、動作が不安定になります。
スタートまでの時間が決められている以上、あまりスタート地点に長居したくないので、スタート地点についてからplay_waypoints_navを立ち上げたくはありません。
リスタート時においても同様です。看板が目の前に置かれるため、スタート時に経路上にコストが発生して大きく迂回して横断歩道に進行する形となり、あまりよくないです。

**Comment by DaikiMaekawa** [comment]
なるほど。 去年はあまり気にしていなかった問題ですね。 それについては対処しておきます。

**Comment by DaikiMaekawa** [comment]
実装しました。 動作確認をお願いします。
https://github.com/open-rdc/icart_mini/pull/102

**Comment by Nasupl** [comment]
コールバックの中でサービスを呼ぶようにする

**Comment by Nasupl** [comment]
実装した
https://github.com/open-rdc/icart_mini/pull/103

**Comment by DaikiMaekawa** [comment]
https://github.com/open-rdc/orne_navigation/issues/126 にも実装されました。 こちらはストップポイントの取り扱いに関しても改善されているため優先してテストを行う。

**Comment by DaikiMaekawa** [comment]
https://github.com/open-rdc/orne_navigation/pull/129 にてコストマップのクリア処理が問題なく行われることを確認しました。
