### ISSUE TITLE
使用している車検シートが古いので更新する

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#127]
公式サイトに上がっているらしい

**Comment by ShotaroTerato** [comment]
ここからダウンロードできました
https://www.google.co.jp/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0CB4QFjABahUKEwiRm6ypnfbIAhUDHZQKHSQXDp8&url=http%3A%2F%2Fwww.tsukubachallenge.jp%2Fwordpress%2Fwp-content%2Fuploads%2F2015%2F09%2F04-safetycheck.xlsx&usg=AFQjCNFWWqonIgnu7vd5QHQxAL6ibV4MzA&sig2=mob2nrsxoMWvdO2WWIKh6g&bvm=bv.106379543,d.dGo&cad=rja
