### ISSUE TITLE
ROS上でIMUを制御するためのプログラムを開発する

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#13]
自己位置推定のパッケージに繋げられるようにtfで姿勢を吐き出すようにしましょう。

**Comment by Nasupl** [comment]
@taki4416 先輩から受け取ったプログラムを改良して、tfを吐き出すようにしました。
https://github.com/open-rdc/adis_imu_drivers

**Comment by Nasupl** [comment]
とりあえずクローズします

**Comment by DaikiMaekawa** [comment]
https://github.com/open-rdc/icart_mini_driver/pull/11 にてIMUのシミュレーションも行えるようにした。
しかし、シミュレータ側のIMUがパブリッシュするメッセージの型はsensor_msgs/Imuなので互換性を保たせるためには実機側を修正する必要がある。

@Nasupl その辺りはこちらで対処しておきます。

**Comment by DaikiMaekawa** [comment]
https://github.com/open-rdc/adis_imu_drivers/pull/1 にて対処を完了した。
実機での動作確認を終了したためこのタスクを完了とする。
