### ISSUE TITLE
A robot to go the long way around waypoint when goal and obstacle overlapped.

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#131]
機体のピッチ方向の傾きにより地面を障害物として検出、障害物とウェイポイントが完全に重なりそれを回りこむようなパスが生成されています。

[![rosbag](http://img.youtube.com/vi/cqAval7k7_o/0.jpg)](https://www.youtube.com/watch?v=cqAval7k7_o)

**Comment by Nasupl** [comment]
この地点で再検証し，ウェイポイントを減らすなどしても問題が発生するようなら高い位置に取付けたコストマップ用URGを稼働させる

**Comment by DaikiMaekawa** [comment]
この地点固有の現象であったため、ウェイポイントを間引くことで暫定的に対処した。 来年度に向けては障害物回避用に高めのURGを設置するなどシステムの改善が求められる。

**Comment by Nasupl** [comment]
とりあえず閉じます
