### ISSUE TITLE
ゴール付近で自己位置推定がうまく行かずにゴールに入れない

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#132]
- 要bagファイル添付

**Comment by Nasupl** [comment]
動画
https://youtu.be/UkhlSZ2UllM

**Comment by Nasupl** [comment]
@ShotaroTerato 
bagファイルお願いします

**Comment by DaikiMaekawa** [comment]
@iou16 そちらでバグファイルを元に検証してお手上げだったら私が引き継ぎます。 今日は他の問題も合わせて長い戦いになりそうですので、出来れば負担を軽減したいと考えています。

**Comment by ShotaroTerato** [comment]
bagファイルになります
http://www.hayashibara-lab.it-chiba.ac.jp/member/bags/2015-11-06-21-50-57.bag

**Comment by ShotaroTerato** [comment]
#139 にて対応。
![screenshot from 2015-11-06 23 27 04](https://cloud.githubusercontent.com/assets/7301081/11000080/0607c0f6-84e3-11e5-922f-baa31ef43913.png)

**Comment by DaikiMaekawa** [comment]
@iou16 amclのパラメータ調整はいかがでしょうか？

**Comment by iou16** [comment]
@DaikiMaekawa z_hitのパラメータを変更して対応しようとしたのですが，そうすると，その他の環境で自己位置推定が不安定になり,困っています.

**Comment by DaikiMaekawa** [comment]
開けた場所でパーティクルの分散が広がりすぎる問題は結局解消されなかったが、ウェイポイントの調整によりゴールの枠には間違いなく入るよう暫定的に対処した。 まっすぐ走行しない問題にはmove_baseの制御周期エラーなども影響しているためそちらの問題を解消することを優先して行う。 開けた場所に於ける自己位置推定のパラメータ改善は来年度の重要な課題である。

**Comment by DaikiMaekawa** [comment]
開けた場所に於けるamclのパラメータの最適化に関する検討を2016年度に向けて再開する。

**Comment by Nasupl** [comment]
#113 に引き継ぎ
