### ISSUE TITLE
Recovery behaviorを変更する

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#134]
@ximo112 詳細を記述してbagファイルを添付してください

**Comment by ximomoi** [comment]
bagも動画も撮っていない状態でしたので文章のみの記述になります。
一番目の橋の直前の直線において、点字ブロック上を走行中のロボットが障害物回避を行った際に回避動作がスローになっているため点字ブロックにスタックし動けなくなることが起こった。

**Comment by ximomoi** [comment]
#138 こちらで対処しました

**Comment by ximomoi** [comment]
マージされたので閉じます

**Comment by DaikiMaekawa** [comment]
実機での動作報告をしてから閉じる。

**Comment by ximomoi** [comment]
動作を確認しました、問題ありません。
