### ISSUE TITLE
ストップポイントを通過してしまう

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#137]
おそらくストップポイントのタイミング依存の仕様のせいでストップポイントを通過してしまうことがある
- bagファイルと動画添付する

**Comment by Nasupl** [comment]
@ShotaroTerato bagを頼みます
@Nasupl 動画を上げる

**Comment by ShotaroTerato** [comment]
ストップポイントを通過してしまう時のbagになります
http://www.hayashibara-lab.it-chiba.ac.jp/member/bags/2015-11-06-21-17-00.bag

**Comment by Nasupl** [comment]
動画
 https://youtu.be/6vcdXwn5cpA

**Comment by DaikiMaekawa** [comment]
bagファイルを解析しました。 結論をいいますとミーティングでも述べたようにタイミング依存の問題でした。
ストップポイントとウェイポイントの送信タイミングがほとんど同じであったため、ウェイポイント側で上書きされて停止しないかったようです。 サービスによるノード間の同期処理やactionlibの後始末等をきちんと行う修正を行っているところです。 完成次第、実機でのテストを依頼します。

**Comment by DaikiMaekawa** [comment]
https://github.com/open-rdc/orne_navigation/pull/129 の修正でナビゲーションのモード遷移に関するノード間連携を同期的に行うことにより解消した。
