### ISSUE TITLE
move_base outputs the warning of planning rate.

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#147]

**Comment by DaikiMaekawa** [comment]
EKFのtf更新周期が10Hzと他に比べて低いことが影響していると推測される。

**Comment by DaikiMaekawa** [comment]
https://github.com/open-rdc/orne_navigation/blob/indigo-devel/orne_bringup/launch/includes/base.launch.xml#L4 を修正して警告が出なくなることを確認すること。

恐らく30Hzくらいが妥当。

**Comment by iou16** [comment]
@DaikiMaekawa 
質問なのですが，読み込むmapファイルのサイズによって"，map update loop missed its desired rate of 1.000Hz... the loop actually took ◯◯ seconds"というwarnが出るかどうかは左右されるでしょうか？

**Comment by DaikiMaekawa** [comment]
グローバルプランニングの探索空間が変わる場合は関係あるかもしれませんね。 その質問をするということはホテルで警告が再現出来ないということでしょうか? @iou16

**Comment by DaikiMaekawa** [comment]
マップの大きさ、そして解像度はプランニングの処理の負荷に影響します。

**Comment by DaikiMaekawa** [comment]
因みにメッセージを吐いている箇所がどこだか特定できますか? rqt_consolでノード名と発生箇所をデバッグしてみてください。

**Comment by iou16** [comment]
node名はmove_baseです，発生箇所とはどういった意味でしょうか？

**Comment by DaikiMaekawa** [comment]
メッセージをクリックすると警告を出しているプログラムの行数まで絞り込めます。

**Comment by iou16** [comment]
![screenshot from 2015-11-07 23 01 24](https://cloud.githubusercontent.com/assets/7301090/11015470/9a00a5be-85a3-11e5-962f-d21e64d8a465.png)

**Comment by DaikiMaekawa** [comment]
costmap2d内に問題の発生箇所があるようですね。 ざっとコードを確認してきますので少々お待ちを。

**Comment by DaikiMaekawa** [comment]
@iou16 costmap_2dの解像度が一番効いてきそうです。 デフォルトは0.05meters/cellなので屋外用途では少し小さすぎたかもしれませんね。
以下にプルリクエストを送りましたので検証おねがいします。
https://github.com/open-rdc/orne_navigation/pull/148

**Comment by iou16** [comment]
検証してみましたが，同じメッセージが出ます．

**Comment by DaikiMaekawa** [comment]
解像度をかなり大きめに設定してみたら警告は無くなる? @iou16

**Comment by iou16** [comment]
@DaikiMaekawa 解像度を0.5に変更して検証してみます．

**Comment by iou16** [comment]
解像度をどれだけ落としても同じエラーメッセージが出ます．

**Comment by iou16** [comment]
![screenshot from 2015-11-08 00 11 58](https://cloud.githubusercontent.com/assets/7301090/11015740/89db17d2-85ad-11e5-8138-1b5571306e64.png)

**Comment by DaikiMaekawa** [comment]
https://github.com/open-rdc/orne_navigation/pull/148 にて対応完了。 
グローバルコストマップとローカルコストマップの解像度を下げて、EKFノードのtfの周期も上げた。
機体標準のPCではなく @Nasupl のPCを使用することで警告が表示されなくなり、CPUの使用率が下がることを確認。 

つまり、以下の環境で最低限の要求スペックを満たした。 

```
Core-I5, 10GB memory, Hybrid-HDD
```

**Comment by DaikiMaekawa** [comment]
@Nasupl のPCは雨により破損、共有PCでは https://github.com/open-rdc/orne_navigation/issues/151 で挙げたように安定して完走することは困難。

**Comment by Nasupl** [comment]
こちらの問題はRAMの不足が原因であると断定し，2016年度は各PCのRAM容量を増加することで解決としました．一旦閉じます．
