### ISSUE TITLE
i-Cart miniの外装作成

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#15]
防水のためにT-frogの外装を作成する。

**Comment by DaikiMaekawa** [comment]
明日、オープンキャンパスだけど今の外装で見た目的にいいのかなぁ．．．

**Comment by ximomoi** [comment]
...最低限の防水加工を施しました。

**Comment by ximomoi** [comment]
ステッカーなど貼った方がいいのでしょうか...

**Comment by DaikiMaekawa** [comment]
ステッカーもだけど緑の素材が丸見えなのが一番まずいと思います。
MegaRoverのような外装の方がまだマシかな  :sweat_drops:

**Comment by ximomoi** [comment]
...はい、がんばります。

**Comment by DaikiMaekawa** [comment]
第4回試走会までにお願いします。

**Comment by DaikiMaekawa** [comment]
@iou16 @ximo112 第四回試走会は悪天候が予想されるため、防水対策は必須となります。
今日中に外装の発注が出来なければ、現状の外装を改良する代替案が必要になりますがそちらは非効率ですね。
無駄な労力を割かなくてもいいように図面の作成を急いでいただければと思います。

**Comment by Nasupl** [comment]
ミスミへの外装部品の発注は完了していますが、届くのはだいぶ先になりそうです。

**Comment by DaikiMaekawa** [comment]
@Nasupl なるほど．．． :skull: 
防水処理を今日中に施す必要がありますね。

**Comment by DaikiMaekawa** [comment]
重量の増加によりキャスターの沈みこみが激しいため、代替案を考えているところです。

**Comment by DaikiMaekawa** [comment]
新しい外装だとつくばチャレンジのコースにある橋付近の坂が登りづらいですね。
原因は１０kg以上の重量増加にあると思いますので、軽量化を検討していただけると助かります。
また、ソフトウェア的にトルクの上限値を上げられるかどうかは調査してみます。

**Comment by DaikiMaekawa** [comment]
@iou16 
20kgの荷重はソフトウェア的な調整ではどうしようもないですね。
つくばチャレンジのコースにおける橋の前の坂と同程度の傾斜を用意して走行実験を重ねましたがモータのトルクが足らず途中で停止しました。
再度、モータのスペック等から所要できる荷重を算出し自律走行可能な程度まで軽量化する必要があります。

**Comment by DaikiMaekawa** [comment]
軽量化したバージョンで大会に参加しました。
作製は終了したのでこのタスクを閉じます。
