### ISSUE TITLE
Introduce an initialpose configuration file.

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#152]

**Comment by DaikiMaekawa** [comment]
https://github.com/open-rdc/orne_navigation/issues/145 の設定をyamlで記述出来るようにしておく。

**Comment by Nasupl** [comment]
@iou16 
これって結局AMCLの立ち上げ時にparamで設定できるんでしたっけ？

**Comment by iou16** [comment]
@Nasupl  paramで設定可能です．

**Comment by iou16** [comment]
対処したので閉じます.
