### ISSUE TITLE
手押し棒の開発

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#173]
地図作成においては，ジョイスティックによってロボットを操作するよりも，モータ配線をドライバから切断して手押しによって地図を作成するほうが効率がよいと考えられるため，ロボットを押すための棒を開発しロボットに取り付ける．
@Shiina-Shiotani が担当しβについては完成，αは接着して完成の見込み．
@Shiina-Shiotani は完成したら写真とともにここに報告すること．

**Comment by Nasupl** [comment]
とれたので接着しなおし

**Comment by Nasupl** [comment]
αも上から挿せるようにしてほしい

**Comment by Shiina-Shiotani** [comment]
αの接続部をL字にした際、前輪部分が浮きやすくなった

**Comment by Shiina-Shiotani** [comment]
車軸中心に力がかかる位置に設置する

**Comment by Shiina-Shiotani** [comment]
現在αはこのようになっている.
![s_4731833333384](https://cloud.githubusercontent.com/assets/12287214/17501095/7098b508-5e16-11e6-95ed-44b9e05213c4.jpg)
![s_4731833346738](https://cloud.githubusercontent.com/assets/12287214/17501097/74784936-5e16-11e6-8663-7e5e2949f4f8.jpg)

**Comment by Nasupl** [comment]
完成
