### ISSUE TITLE
ORNE-βの防水対策

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#174]
ORNE-βは現状でPC搭載部と電子回路搭載部が露天であり雨天時の防水性に難がある．

**Comment by buzzshima** [comment]
回路の部分は終了

**Comment by Hiroki-Goto** [comment]
７/9の天気予報が雨のため防水グッズの購入

**Comment by Nasupl** [comment]
#186 でタッパ内に水が侵入し電装が水没しそうになったので，配線穴等の位置変更が必要

**Comment by Nasupl** [comment]
配線穴部分はゴムブッシュで構成されている．ミスミで探す．

**Comment by Nasupl** [comment]
穴径はΦ32くらい

**Comment by Nasupl** [comment]
ゴムブッシュみっけた http://jp.misumi-ec.com/vona2/detail/110500128760/?HissuCode=C-30-SG-32A-5P&PNSearch=C-30-SG-32A-5P&searchFlow=results2products

**Comment by Nasupl** [comment]
とりあえずタッパへの配線投入位置をタッパ下部に変更した。これでケーブルを伝ってタッパ内に水が浸入することはないはず。配線をもうちょっとしたら出来上がり。
