### ISSUE TITLE
ORNE-βの電装

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#175]
- [x]  IMUの搭載
- [x] 緊急停止スイッチの取り付け及び配線
- [x] 3D URGの電源回路
- [x] icart-miiidle回路の防水対策(タッパで)

**Comment by Nasupl** [comment]
どれもまだ

**Comment by buzzshima** [comment]
防水対策終了

**Comment by Nasupl** [comment]
IMUのソフトウェア対応完了( #185 )
緊急停止スイッチの配線は明日Robocup資材回収後に実施．
また，IMUのUSBケーブルとバッテリーが干渉する問題も明日までに部品を購入して実施予定．

**Comment by Nasupl** [comment]
全部終わったっぽい
