### ISSUE TITLE
障害物の回避がギリギリ

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#177]
base_local_plannerが計画する経路が，特に歩行者等がロボットの前に突然現れた時などにおいて，障害物のギリギリを通るようなものになっていて，安全性の面で課題がある．
場当たり的であるが，つくばチャレンジにおいては狭路を通過するようなコースはないため，move_baseのfootprintパラメータを現状より大きくすることによって対処する．

**Comment by Hiroki-Goto** [comment]
後藤が担当します

**Comment by Nasupl** [comment]
middleは #187 URGの挙動がおかしい（後藤談）ため検証ができず止まっている．

**Comment by Nasupl** [comment]
alphaは狭い場所でbase_local_plannerがアボートする問題があるらしいのでその検証まち

**Comment by Nasupl** [comment]
alphaについては #193 で解決．

**Comment by Nasupl** [comment]
βは @Hiroki-Goto が担当

**Comment by Nasupl** [comment]
βも #196 で解決
