### ISSUE TITLE
ORNE-βのバッテリーもうワンセット買うか確認

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#182]
長時間動かしてどのくらいバッテリーが減るかわからないので，チェックして，減りが早そうだったらもうワンセット買う．

**Comment by buzzshima** [comment]
電圧のチェック
13.05   13.03   16:00
この時モータの線を抜いた
～３階地図作成～
12.80   12.78   16:20
～外の地図作成～
12.79   12.77
～waipoint～
12.77   12.75   17:58
19:00に再開まで電源スイッチoff(その時は特に降下してない)
～自律移動～
12.84       12.85          19:50
以上の結果となりました

地図作成とwaypointは手押しで行った

**Comment by buzzshima** [comment]
@Nasupl この件は今週長く動かしてためしてから購入するか決める感じですか？

**Comment by Nasupl** [comment]
@buzzshima お願いします

**Comment by Nasupl** [comment]
#186 に示したように多分いらない
