### ISSUE TITLE
icart-miniで自律走行させる際、2D Pose Estimate を押しても何も反応が起きない

### ISSUE THREAD

**Issue by KentaKubota** [open-rdc/orne_navigation#183]

**Comment by Nasupl** [comment]
当該時刻のbagファイルは記録してありますか？

**Comment by KentaKubota** [comment]
あります。
slack #general に上げた16_06_21_test_run.zipです。

**Comment by Nasupl** [comment]
その際，rvizからmove_baseに/initial_poseトピックはpublishされていますか？

**Comment by KentaKubota** [comment]
確認方法がわかりません。どのように確認できますか？
bagファイルを再生しながらrostopic list -v で確認しましたが

Published topics:
  /initialpose [geometry_msgs/PoseWithCovarianceStamped] 1 publisher

があるのは確認できました。

**Comment by KentaKubota** [comment]
Fixed Frameをbase_linkにした状態で2D Pose Estimateを行っていたのが原因でした
