### ISSUE TITLE
結界の実装

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#189]
走行禁止箇所に結界を設定できるようにしてほしい

**Comment by ShotaroTerato** [comment]
amclとcostmap2dはそれぞれmapを受け取っている．
amclは今までどおりのmapを受け取り，costmap2d側で編集済みmapを受け取らせる方法が一番簡単な対処法か

**Comment by Nasupl** [comment]
launchファイルを書いてください

**Comment by Nasupl** [comment]
memo: map_serverを2つ建てる

**Comment by ShotaroTerato** [comment]
map_serverを２つ建てた
今度はcostmap側に別のmapを受け取らせる
![two_maps](https://cloud.githubusercontent.com/assets/7301081/17238209/c4139bc4-5594-11e6-9af8-d23180b24398.png)
![rosgraph](https://cloud.githubusercontent.com/assets/7301081/17238211/c81a2b0c-5594-11e6-9568-edea388a2902.png)

**Comment by ShotaroTerato** [comment]
navigationのstatic layerのプラグインを直書き換えしたところ
うまくグローバルコストマップとしてもうひとつのマップが読み込まれた
と思ったが，元マップがmove_baseに渡されていない…←（追記）move_baseは別に自己位置推定してないし元マップ読む必要ないのか
![1_001](https://cloud.githubusercontent.com/assets/7301081/17239513/ad57305c-559f-11e6-858d-49a3cfe4cda4.png)
![rosgraph_costmap](https://cloud.githubusercontent.com/assets/7301081/17239524/b91512d8-559f-11e6-91cd-36712ac23862.png)

**Comment by ShotaroTerato** [comment]
マップの占有してるとこをpoint cloudに変換して障害物として認識させるほうが早いかも

**Comment by ShotaroTerato** [comment]
amclがちゃんと元マップを受け取れているか確認をする

**Comment by ShotaroTerato** [comment]
global costmap として別のマップを受け取れた
amclもちゃんと動いてるっぽい
![workspace1_002](https://cloud.githubusercontent.com/assets/7301081/17283358/69cd33c0-57ea-11e6-965e-36712676686f.png)

**Comment by ShotaroTerato** [comment]
運用時にいちいち2つのマップファイルを指定するの面倒になりそう

**Comment by ShotaroTerato** [comment]
argを使ってうまい具合に読み込ませるようにする

**Comment by ShotaroTerato** [comment]
![nav rviz- - rviz_004](https://cloud.githubusercontent.com/assets/7301081/17319950/f909bfd6-58cb-11e6-9331-cf11d0620a80.png)
![nav rviz- - rviz_005](https://cloud.githubusercontent.com/assets/7301081/17319952/fad0c846-58cb-11e6-9856-9d4239623e47.png)

**Comment by ShotaroTerato** [comment]
efc2090 でmap_file指定時に自動的にmap_file_for_costmapの指定がなされるようにした
運用法が少し変わりmap_fileを指定するときは

・従来
map_file:=/フルパス/map.yaml
・変更後
map_file:=/フルパス/map

となった．
この時，mapファイルとmap_for_costmapファイルを同じディレクトリに保存しておくこと
また読み込ませたいコストマップ用マップの名前は
"（元マップの名前）_for_costmap.yaml"
とすること

**Comment by Nasupl** [comment]
地図を用意すれば使える

**Comment by Nasupl** [comment]
とりあえず検討は完了したので一回閉じる
