### ISSUE TITLE
戦略の改良

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#195]
現在のorne_strategyを，信号/探索対象者へのアプローチ/自己位置推定の尤度低下時の復帰動作及びmove_baseの制御が可能なように改良する

**Comment by Nasupl** [comment]
wait_near_pointに状態が遷移した後，ロボットがゴールに向かわない．その時のゴールはtargetからmost_nearじゃないところに出ている．

**Comment by Nasupl** [comment]
2回目以降のアプローチにおいて，waypoints_navが停止していないためにコストに引っかかってもたもたしているとwaypoints_navが動いて進んでいってしまう問題がある

**Comment by Nasupl** [comment]
そもそも、waypointsをgoalとしていちいちsubscribeしてるのがおかしいので、https://github.com/open-rdc/fulanghua_navigation にwaypointsをnav_msgs/PoseArrayで要求できるserviceをつくって、起動時に全waypointsをもらって計画できるようにしたい。

**Comment by buzzshima** [comment]
B3から募集

**Comment by Nasupl** [comment]
別の問題に移行しているので閉じます
