### ISSUE TITLE
ORNE-αの電源問題

### ISSUE THREAD

**Issue by Shiina-Shiotani** [open-rdc/orne_navigation#197]
αのURGが故障する事案が連続して発生した.

**Comment by Shiina-Shiotani** [comment]
モータドライバ側で5Vが正常に流れるか確認

**Comment by Shiina-Shiotani** [comment]
4.88Vだった

**Comment by Nasupl** [comment]
Top-UIRG電源供給部以外はとりあえず問題なさそうなので，Top-URGの電源供給部だけMegaroverのものに取り替えて運用する．
