### ISSUE TITLE
αの緊急停止スイッチの高さ変更

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#198]
緊急停止スイッチが付いているフレームの高さを変更する．
@KentaKubota がフレーム発注中

**Comment by Nasupl** [comment]
棒が届いた．

**Comment by KentaKubota** [comment]
フレームの高さ変更  終了
![5045903480354](https://cloud.githubusercontent.com/assets/12063148/19301682/a9654646-909b-11e6-8d9e-661607e67cfb.jpg)
