### ISSUE TITLE
ORNE-α電源回路検証

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#201]
取り外して負荷かけて検証

**Comment by Nasupl** [comment]
今日取り外してチェック

**Comment by Nasupl** [comment]
新しい電源届いたけどURGは別電源のまま

**Comment by Nasupl** [comment]
とりあえず交換はした

**Comment by yasuohayashibara** [comment]
とりあえず担当者がいなければ林原が問題の究明を行います．
どなたかできればお任せします．

私が行う場合は，問題のある電源を机の上に置いて下さい．

**Comment by Nasupl** [comment]
電子負荷で挙動をみたところ、12Vのレギュレータが50mA負荷時に500mVドロップし、120mA負荷をかけたところでシャットダウンしてしまった。定格1A品なのでレギュレータの故障であると考えられる。
また、正常品も同様にテストしたが、こちらも950mAでシャットダウンしてしまった。定格消費電流700mAで1A以上の容量を持つ電源が推奨されているTop-URGにおいてこの性能はいささか不安がある。レギュレータの変更や、またこれまでのトラブルを考慮すると絶縁型のDCDCを使った電源回路に変更するべきなのかもしれない。

**Comment by yasuohayashibara** [comment]
多くの人に影響する問題だと思いますので，渡辺先生（確か設計は渡辺先生でしたよね）にフィードバックしたほうが良さそうですが，夏迫くんにお願いして良いですか？
難しければ林原が行います．

**Comment by Nasupl** [comment]
@yasuohayashibara やりましょう

**Comment by Nasupl** [comment]
TF-2MD3-R6のMLに投稿しました

**Comment by Nasupl** [comment]
更に解析した結果ポリスイッチが故障していたので、交換する。bel Fuseの0ZCJ Series。

**Comment by yasuohayashibara** [comment]
届きましたので机の上に置いておきます．

**Comment by Nasupl** [comment]
交換した
