### ISSUE TITLE
機体にスポンサーのシールを貼る

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#202]
本走行までに貼る

**Comment by NamikiHiroaki** [comment]
シール用紙検収済みです

**Comment by Nasupl** [comment]
高解像度なロゴのデータがないのでそれ待ち

**Comment by yasuohayashibara** [comment]
一応ロボカップで問合せてみましたが反応がないおそれがあります．
もし間に合わないようでしたら，ウェブ上のものを利用して下さい．

あと，フォーラムエンジニアリングのロゴだけだと「フォーラムエンジニアリング」チームになってしまいますので，千葉工業大学（もしくはORNE？）のロゴは最低限必要だと思います．

サイズや見え方に注意しないとみなさん「フォーラムエンジニアリング」の社員と間違われることになります．

ちなみに，未来ロボティクスのロゴを見つけました．（使わなくても良いが．．．）
![default](https://cloud.githubusercontent.com/assets/5755200/19712442/d6169892-9b78-11e6-9a17-53f77fe1bcf7.jpg)

**Comment by yasuohayashibara** [comment]
高画質のロゴ手に入れました．

https://drive.google.com/file/d/0B1R8y8aFBfUdSnNJMmNyZERPb1E/view?usp=sharing
https://drive.google.com/file/d/0B1R8y8aFBfUdeE4tQjVaU0JZWFk/view?usp=sharing
https://drive.google.com/file/d/0B1R8y8aFBfUdVFR5ODhPQkUzbWM/view?usp=sharing

**Comment by Nasupl** [comment]
貼った
