### ISSUE TITLE
不足している備品の補充

### ISSUE THREAD

**Issue by Shiina-Shiotani** [open-rdc/orne_navigation#209]

**Comment by Shiina-Shiotani** [comment]
10/15, 16 試走会前でのチェック
・ビニール袋
・マジックテープ
・両面テープ
・雑巾(予報では晴れなので必要ないかも)

**Comment by buzzshima** [comment]
マジックテープ大量

ロール状やつで

**Comment by ShunShimamura** [comment]
- [x] マジックテープ
- [x] ゴミ袋、ビニール袋
- [x] タオルor雑巾
- [x] 両面テープ

**Comment by NamikiHiroaki** [comment]
ポリ袋（65cm×80cm 0.012mm 45L）40枚入り
雑巾（20cm×30cm）3枚入り
両面テープ（15mm×6.5m）
各１つずつ購入
マジックテープについては新習志野・津田沼周辺にはロール状のものがないのでネット購入になるかと

**Comment by Nasupl** [comment]
@NamikiHiroaki マジックテープ，南船橋のスーパービバホームか船橋競馬場のコーナンまでいけばロールのやつ売ってるはず．

**Comment by NamikiHiroaki** [comment]
Vivaホームの方は今日確認したのでコーナンの方寄ってみます

**Comment by Nasupl** [comment]
あー，ロールというか切り売りのやつでいいと思う． @buzzshima, @ShunShimamura 両面テープ何m必要ですか？具体的に．

**Comment by buzzshima** [comment]
最低5㍍ですかね

欲を言えば切り売りだと小さな余分なやつをなくしてすぐストックなくなりそう

**Comment by buzzshima** [comment]
あと#202のシール用紙もお願いします

**Comment by Nasupl** [comment]
切り売りって店頭にロールで置いてあって店員さんに切ってもらって買うタイプのやつのことですよ．
@buzzshima が言ってる切り売りは20cmごとにパッケージに封入されているやつのことでは？

**Comment by buzzshima** [comment]
@nasupl  予想してるとおりです

**Comment by Nasupl** [comment]
@NamikiHiroaki ということで1m辺りx円みたいな感じで売ってるロール切り売りのマジックテープを5mお願いします

**Comment by NamikiHiroaki** [comment]
マジックテープの幅は15mmとかそのくらいで大丈夫でしょうか？

**Comment by buzzshima** [comment]
なので@nasupl の言ったとおりで

**Comment by Nasupl** [comment]
15mm細くない？25mmがベストだけどなければ15mmでいいです．

**Comment by buzzshima** [comment]
@NamikiHiroaki 20ミリ以内であればできるだけ太めで割りにいいやつで

**Comment by NamikiHiroaki** [comment]
了解しました

**Comment by buzzshima** [comment]
25mmだとフレームからでるので少し嫌ですね

**Comment by NamikiHiroaki** [comment]
切り売りは幅25mmが最小のようです

**Comment by Nasupl** [comment]
@NamikiHiroaki それでいいです

**Comment by NamikiHiroaki** [comment]
マジックテープ5m 検収済みです

**Comment by Nasupl** [comment]
全部揃った
