### ISSUE TITLE
膨張リセットを導入してからウェイポイントでの経路生成が遅い

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#220]
要因は不明
* 膨張リセットによってパーティクルが増えていて，計算リソースが消費されている
  * パーティクルの数をもうひと桁減らしてもいいかもしれない
* navigationパッケージ全体をローカルでビルドしているため，バイナリ配布より重くなっている（？）
  * 最適化オプションをつけてビルドすれば解決するかもしれない

**Comment by iou16** [comment]
Gazeboで試している分にはそこまで遅くならない気がするんだけど, 何故だろうか？

**Comment by Nasupl** [comment]
@iou16 地図サイズは？

**Comment by iou16** [comment]
@Nasupl デフォのmymapです. 地図サイズの影響か.

**Comment by Nasupl** [comment]
そうね，地図サイズの影響は明らか．
しかし，同じ地図でも前回はここまで遅くなかったのでは？

**Comment by Nasupl** [comment]
2号館北側から東側を通って南側までコの字状に同じ初期位置から同じWaypointsで走行させたときの時間を測定した
- navigationパッケージすべてローカルビルド: 8分40秒
- amclのみをローカルビルド、それ以外はバイナリ配布版navigationパッケージ: 7分46秒

1回のみしか走行させていないので偶然かもしれないが、Waypointにおける次のWaypointへの経路計画は歴然と速い気がした。

**Comment by Nasupl** [comment]
膨張リセットをビルドするときに最適化オプションをつけてビルドしてあげたほうがいいかも知れない
