### ISSUE TITLE
膨張リセットにおける誘拐状態判定の閾値を調整する

### ISSUE THREAD

**Issue by iou16** [open-rdc/orne_navigation#225]
膨張リセットが頻発し過ぎる. でも膨張リセットがないと完走できない. 閾値を少し高くして対処.

**Comment by iou16** [comment]
そもそも, paramで閾値を設定できるようにすべきかも知れない.

**Comment by Nasupl** [comment]
navigation側はhttps://github.com/open-rdc/navigation/pull/3 で対応済み
