### ISSUE TITLE
New_機体　要求仕様　要望

### ISSUE THREAD

**Issue by buzzshima** [open-rdc/orne_navigation#237]
思いつくこと箇条書きでいいのでどんどん書いてください
参考の写真やURLあると助かります

**Comment by buzzshima** [comment]
29日のミーティングで話を詰めて行きたいと思います

**Comment by buzzshima** [comment]
キャスターの位置（前後）
タイヤ径
スイングアーム
モータは変更?

**Comment by Nasupl** [comment]
仕様を決定していく前に要件を定義しないといけないと思う．
新機体については，つくばチャレンジの環境，ひいては市街地におけるミニマムなロボットにできるといいと思っていて，そのためにはどのくらいの段差を登れなきゃいけなくて，どの程度の環境で自己位置推定できなきゃいけなくて，どのくらいの障害物を見つけられなきゃいけないのか，そういうところから考えなくてはならないんだと思う．

**Comment by buzzshima** [comment]
# コンセプト  
 小さくて走破性のたかい機体．  
- i-Cart middleをベースに設計

## middleからのおもな変更点  
- キャスターサイズの変更
- ホイールベースを短く
-  駆動輪を後部に変更
-  PCのモニタを見やすくするために斜めに設置
-  重心を低く設定
