### ISSUE TITLE
最低加速度の設定

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#240]
icart_mini_controlでは，最低加速度を設定することが可能だが，現在は設定されていないため速度指令がでなくなった場合急停止する．このパラメタを設定することでこの問題を解決する．

**Comment by Nasupl** [comment]
ORNE-αは勝手にゆっくり止まるので必要なさそう．βの狭幅化が終わったらβで調整する．

**Comment by iou16** [comment]
https://github.com/open-rdc/icart/blob/indigo-devel/icart_mini_control/config/icart_mini_control.yaml#L34
↑このファイルをこのまま変更するか, 必要であればαとβで分けるか, 意見お願いします.

**Comment by Nasupl** [comment]
@iou16
そもそもβにおいてはこのパラメータ有効に機能するの？

**Comment by iou16** [comment]
βには効き目ありそうですよ

**Comment by Nasupl** [comment]
@iou16 
βで有効なパラメータをαで使ったときに、αの動作に影響がでないならそのまま変更すればよいのでは

**Comment by iou16** [comment]
それもそうだな、影響なさそうなのでこのまま変更する.

**Comment by iou16** [comment]
最低加速度の設定前の挙動
![img_1359_short](https://cloud.githubusercontent.com/assets/7301090/26146626/d0d551d6-3b2b-11e7-815c-ea021c30b756.gif)

**Comment by iou16** [comment]
最低加速度の設定後の挙動
![img_1358_short](https://cloud.githubusercontent.com/assets/7301090/26146715/22e35d10-3b2c-11e7-945c-1ac0901fbf35.gif)

**Comment by yasuohayashibara** [comment]
あまり加速度を下げすぎると応答が遅くなり障害物回避などに問題が発生するかもしれませんが，オドメトリの精度を考えると最大加速度はできるだけ下げたほうが良いです．

**Comment by Nasupl** [comment]
マージした (https://github.com/open-rdc/icart/pull/117)
