### ISSUE TITLE
モバイルバッテリーの追加購入

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#242]
PCに給電可能なモバイルバッテリーが一台しか無いので，２台のロボットを運用するには不足している．
もう１台モバイルバッテリーを購入する．

**Comment by Nasupl** [comment]
来年度予算につける

**Comment by Nasupl** [comment]
土浦プロジェクトはこれを使っているらしい．デカくて安い．
 http://amzn.asia/5ZD4hsH

**Comment by iou16** [comment]
発注していたモバイルバッテリーが届いた(検収済)

**Comment by buzzshima** [comment]
動作確認をする

**Comment by Hiroki-Goto** [comment]
動作確認を行った（問題なかった）

モバブの出力が12Vと20Vの二種類があるためPCを充電するときは確認を行った方がいい

**Comment by Nasupl** [comment]
@Hiroki-Goto PCは20Vでいいですね？

**Comment by Hiroki-Goto** [comment]
@Nasupl 20Vで大丈夫です

**Comment by Nasupl** [comment]
予算が決まり次第もう1台買う

**Comment by yasuohayashibara** [comment]
購入しました．
issueを閉じます．
