### ISSUE TITLE
第一回実験走行での全域bringuｐのみのbagファイル取得

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#243]
以後のデバッグをしやすくするため，第一回実験走行会でbringupのみを立ち上げたbagファイルを取得しておく

**Comment by buzzshima** [comment]
betaは次回も取得

**Comment by Nasupl** [comment]
αは取った．βはローカルからDAVに移す（消してなければ）消えてたら寺戸のを移す．

**Comment by ShotaroTerato** [comment]
2017/07/08のβのbagファイルをDAVにアップロードした

**Comment by ShotaroTerato** [comment]
補足：βのPCのローカルに保存されていたbagファイルをアップロードした
