### ISSUE TITLE
新マシン選定

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#250]

**Comment by Hiroki-Goto** [comment]
早めに候補をあげる（備品扱いにする）
CPU：i7-７世代以降
RAM：最低8GB，できれば16GB
SSD　容量は常識的なおおきさ
おおきさ：βのマシン以下（重さはとわない）
GPUはできればほしい
USBポート：3ポート以上
画面：取れたり180°以上回したい

**Comment by buzzshima** [comment]
ThinkPad P40 Yoga はどうでしょう

http://www3.lenovo.com/jp/ja/notebooks/thinkpad/p-series/ThinkPad-P40-Yoga/p/a

**Comment by buzzshima** [comment]
http://www3.lenovo.com/jp/ja/notebooks/thinkpad/p-series/ThinkPad-P40-Yoga/p/22TP2WPWP40

**Comment by Nasupl** [comment]
Quadro M500MもちゃんとLinux向けdriverがあるっぽいのでP40 Yogaでいい気がしてきた

**Comment by Nasupl** [comment]
見積もり中

**Comment by yasuohayashibara** [comment]
購入の手続きを進めていますが，申し訳ありませんが，既にウェブページがなくなっています．
発注にはカタログが必要になるのですが，もしかして販売終了でしょうか．
もし分かる方はできるだけ早めに教えてくれると助かります．
このままだと再度型番選定から始めなければならないかもしれません．

**Comment by Nasupl** [comment]
@yasuohayashibara 
Webページがなくなっているというのがよくわからないのですが、どのWebページがなくなっているのですか？
製品のWebページは存在しているようですが。 http://www3.lenovo.com/jp/ja/notebooks/thinkpad/p-series/ThinkPad-P40-Yoga/p/22TP2WPWP40

**Comment by yasuohayashibara** [comment]
￥182,218という価格が記載されていますが，間違いないでしょうか．
見積もりが224,070円ですが，差額は手数料？
カタログと見積もりを事務に出して妥当性を審査されますので弾かれるおそれがあります．

**Comment by Nasupl** [comment]
@yasuohayashibara 
今回見積もりをお願いしたのは http://www3.lenovo.com/jp/ja/static/catalog/nb-2016-p40yoga_cf_0119 の20GR0003JPで、このページには見積もりを取った製品の直販価格も書いてありますが、このページでよろしいですか？

**Comment by yasuohayashibara** [comment]
見れました．ありがとう．
こちらで発注します．

**Comment by yasuohayashibara** [comment]
転送します．

2017年5月29日 17:48 池田　大輔 <d-ikeda@chibasokki.co.jp>:
> 千葉工業大学
> 林原先生
>
> いつもお世話になっております。
> 本日用度課様よりPC発注の連絡を頂きました。
> ありがとうございます。
> 納期は確認でき次第ご連絡致します。
> よろしくお願い致します。
>
> ************************************
> 株式会社 千葉測器 船橋営業所
> 池田 大輔
