### ISSUE TITLE
バッテリーカバーの作成

### ISSUE THREAD

**Issue by ShotaroTerato** [open-rdc/orne_navigation#252]
バッテリーカバーが紛失しているため、プラスチック段ボールなど用いて再度作成する必要がある

**Comment by Nasupl** [comment]
@rakkyo1223 @nao2853 @ryotasuzuki0919 @fujisawa1933 @NamikiHiroaki どなたか主導してやっていただきたく

**Comment by nao2853** [comment]
制作しました

**Comment by Nasupl** [comment]
@nao2853 
新しいバッテリーが来たのでもう2個お願いします
