### ISSUE TITLE
新機体のdescription変更

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#253]
新機体のハードウェアに併せてurdf等を変更する必要がある

**Comment by Nasupl** [comment]
変更が必要なもの
* xacro
* ypspurのパラメータ

**Comment by Hiroki-Goto** [comment]
こちらもβと同様に最低加速度を設定する必要があると思われる

**Comment by Hiroki-Goto** [comment]
gazeboの完成などの設定ファイルの変更も行う

**Comment by ShotaroTerato** [comment]
旋回時orne-xのgazeboのモデルの動きがおかしかった（直進走行は正常）
→base_linkから駆動輪が前後方向に大きく離れていると信地旋回ができなくなる挙動がみられた
orne_x.xacro：ロボット本体､車輪ごと0.1m前方に移動させ、駆動輪軸をbase_linkに近づけたところ改善した
928102b

**Comment by Nasupl** [comment]
footprintを変える必要がある

**Comment by ShotaroTerato** [comment]
footprintを変更した
#271
