### ISSUE TITLE
新PCのセットアップ

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#255]
* Ubuntu 16.04
* ROS Kinetic Kame
* CUDA 8.0
* Open CV ( <= 3.1 )
* ZED SDK

**Comment by Nasupl** [comment]
nVidiaのドライバのインスコ中

**Comment by Nasupl** [comment]
@ryotasuzuki0919 完了でいいですか？

**Comment by ryotasuzuki0919** [comment]
PCセットアップ完了です
