### ISSUE TITLE
Kinetic対応

### ISSUE THREAD

**Issue by Hiroki-Goto** [open-rdc/orne_navigation#261]
ROSのバージョンがkineticの場合，今までの導入方法だとパッケージ等が足らないためcatkin buildできない問題が発生する

そのためwikiを変更する必要がある

**Comment by Hiroki-Goto** [comment]
忘れないうちにメモ
・hokuyo_nodeの入れ方
http://answers.ros.org/question/243232/how-to-install-hokuyo_nodeurg_node-on-kinetic/
を参考に導入する
・icart_mini_driverのCMakeList.txtの24行目YPSpur->ypspur
・icart_mini_gazeboのCMakeList.txtに「add_definitions(-std=c++11)」の追加
・navigationパッケージのvoxcel_gridディレクトリの削除（？）
・YPSpurの導入時にcatkin build を行わない（依存関係の解決時に問題が起きる）

**Comment by Nasupl** [comment]
@Hiroki-Goto navigation stackはkinetic-develなら通るのではないですかね？（膨張リセットをなんとかする必要がありますが）

**Comment by Hiroki-Goto** [comment]
ｔｆ周りの対応

**Comment by ShotaroTerato** [comment]
旋回時orne-xのgazeboのモデルの動きがおかしかった（直進走行は正常）
→base_linkから駆動輪が前後方向に大きく離れていると信地旋回ができなくなる挙動がみられた
orne_x.xacro：ロボット本体､車輪ごと0.1m前方に移動させ、駆動輪軸をbase_linkに近づけたところ改善した

**Comment by ShotaroTerato** [comment]
bringupのみのときのtf
nav_static_mapしたときのtf

![frames_only_bringup](https://user-images.githubusercontent.com/7301081/29354969-35998784-82aa-11e7-841c-b0b4c0842d24.png)
![frames_with_map](https://user-images.githubusercontent.com/7301081/29354988-444f25fe-82aa-11e7-8481-001250372feb.png)

**Comment by ShotaroTerato** [comment]
https://answers.ros.org/question/259341/frames-not-shown-using-view_frame-node-but-in-rviz/
このページを参考に
rosrun tf2_tools view_frame.py
を実行した結果
![tf2_frames](https://user-images.githubusercontent.com/7301081/29395916-5d814bc4-834f-11e7-8699-193191910463.png)
配信されているtfトピック
/tf
/tf_static

**Comment by Nasupl** [comment]
@Hiroki-Goto 
https://github.com/open-rdc/orne_navigation/issues/261#issuecomment-313697900 について，kinetic-develブランチを作成して反映してください．

**Comment by Nasupl** [comment]
具体的作業
- [x]  orne_pkgs.installの変更
- [x] 依存関係の解決
  * hokuyo_nodeはdeprecatedなのでurg_nodeに変える
- [x]  navigationパッケージの対応
  * https://github.com/open-rdc/navigation/issues/7
- [x]  icartパッケージの対応
  * icart_mini_driverのCMakeList.txtの24行目YPSpur->ypspur
  * icart_mini_gazeboのCMakeList.txtに「add_definitions(-std=c++11)」の追加
  * icart_mini_drive.launchでもurg_nodeが立ち上がるようにする
- [x]  #269 
- [x]  #274 のurg_node関連対応

**Comment by Hiroki-Goto** [comment]
rvizの読み込むファイルを元に戻す

**Comment by Nasupl** [comment]
@Hiroki-Goto icartパッケージにもkinetic-develを立ち上げたので，CMakeLists周りの変更をお願いできますか？

**Comment by Hiroki-Goto** [comment]
@Nasupl プルリクを送りましたので確認をお願いします.

**Comment by Nasupl** [comment]
@Hiroki-Goto 動作はKinetic環境で確認済みですよね？

**Comment by Nasupl** [comment]
https://github.com/open-rdc/icart/pull/119 と https://github.com/open-rdc/icart/pull/118 でicart周りは終わり

**Comment by Pethon** [comment]
ROS kinetic用のorne環境をインストールスクリプト

#!/bin/bash

mkdir -p ~/catkin_ws/src
cd ~/catkin_ws/src
catkin_init_workspace
cd ~/catkin_ws/
catkin build
cd ~/catkin_ws/src
git clone https://github.com/DaikiMaekawa/ypspur.git
git clone https://github.com/open-rdc/orne_navigation
wstool init
wstool merge orne_navigation/orne_pkgs.install
wstool up
rosdep install --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y
catkin build
sed -i -e 's/find_package(ypspur)/find_package(YPSpur)/g' ~/catkin_ws/src/icart_mini/icart_mini_driver/CMakeLists.txt
catkin build
sed -i -e 's/find_package(YPSpur)/find_package(ypspur)/g' ~/catkin_ws/src/icart_mini/icart_mini_driver/CMakeLists.txt
catkin build
catkin build
echo "source ~/catkin_ws/devel/setup.bash" >> ~/.bashrc
exit
