### ISSUE TITLE
βの地図作成

### ISSUE THREAD

**Issue by Hiroki-Goto** [open-rdc/orne_navigation#262]
第1回試走会で取得した地図と前回までの地図を合成する

**Comment by iou16** [comment]
合成した. 出来は7/25のミーティングで確認. 自動ドアを消し忘れたので消す. https://github.com/open-rdc/orne_maps にアップロードしようとしたが, git lfsが容量オーバであげられないので, 研究室マシンをgitサーバにし, そちらに上げる.

**Comment by Nasupl** [comment]
@rakkyo1223 
編集した地図コミットだけしとく
