### ISSUE TITLE
orne_mapsのレポジトリ移転

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#264]
#262 で，Githubでは容量が足りなくなってしまったので研究室のサーバにレポジトリを移転する

**Comment by Nasupl** [comment]
普通のremoteレポジトリをつくってlfsで管理して，httpsでアクセスしようとしてもうまくいかない．sshだったらうまく行きそうだけど，鍵の管理とか悩みどころ．めんどくさい．
GitLabを導入してどうにかしようとしているけどうまくいっていない．

**Comment by Nasupl** [comment]
@yasuohayashibara にお願いしてgithubに課金してもらう

**Comment by yasuohayashibara** [comment]
課金プランに加入しました．
ご確認下さい．
