### ISSUE TITLE
StateTriggerPanelをkineticで読み込むとrvizが落ちる

### ISSUE THREAD

**Issue by Hiroki-Goto** [open-rdc/orne_navigation#272]
kineticでnav.rvizを読み込んだ場合，おそらくStateTriggerPanelが原因でrvizが落ちる

**Comment by Hiroki-Goto** [comment]
今のところの対応
kineticはnav.rviz以外のファイルを読み込むことで対応
自律移動する際はサービスを送ってる（wikiのコマンドではスタートしない）

**Comment by Nasupl** [comment]
@Hiroki-Goto orne_toolsを最新にしてビルドしましたか？

**Comment by Hiroki-Goto** [comment]
最新にしてみてやってみた結果です
・orne_toolsのSaveTriggerPanel->読み込むことはできた
・orne_rviz_pulginsのStateTriggerPanel->rvizは落ちる

あとnav.rvizですが，StateTriggerPanelだけを読み込んでいるっぽいです

**Comment by Nasupl** [comment]
@Hiroki-Goto Hiroki-Goto orne_rviz_pluginも#270 で対応しているはずですが、そのテストはどのブランチで試していますか？

**Comment by Hiroki-Goto** [comment]
テストのブランチですが，change_orne_x_descriptionでやっています

**Comment by Nasupl** [comment]
@Hiroki-Goto そのブランチには #270 がマージされていないからだと思います。なぜKinetic develではなくそのブランチなんですか？

**Comment by Hiroki-Goto** [comment]
kinetic develのブランチはαのURDFの変更などが適用されていなかったため，変更を適用しているchange orne x description でテストをしていました

最新版のindigo develでやってみしたが落ちませんでした

**Comment by Nasupl** [comment]
@Hiroki-Goto indigo-develをkinetic-develにマージしてください

**Comment by Nasupl** [comment]
#273 が終了したら終了

**Comment by Nasupl** [comment]
#273 マージした
