### ISSUE TITLE
テントの錘を買う

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#277]
先生にお願いする

**Comment by ShotaroTerato** [comment]
https://www.amazon.co.jp/%E3%82%A2%E3%82%A4%E3%83%AA%E3%82%B9%E3%82%AA%E3%83%BC%E3%83%A4%E3%83%9E-%E3%82%A6%E3%82%A9%E3%83%BC%E3%82%BF%E3%83%BC%E3%82%BF%E3%83%B3%E3%82%AF-10%E3%83%AA%E3%83%83%E3%83%88%E3%83%AB-%E3%80%902%E5%80%8B%E3%82%BB%E3%83%83%E3%83%88%E3%80%91-WAT-10L/dp/B00TDKRUAG/ref=pd_sim_200_11?_encoding=UTF8&psc=1&refRID=XMZBPNX82R4NTRXN2XFQ

10L　2個セット　ウォータータンク　880円

**Comment by yasuohayashibara** [comment]
購入しました．
issueを閉じます．
