### ISSUE TITLE
オープンキャンパスのデモ用に i-Cart miniの開発環境を構築する

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#29]
オープンキャンパスのデモに備えて三年生だけでもi-Cart miniの運用ができるようにする必要がある。

**Comment by DaikiMaekawa** [comment]
@ximo112 まずはi-Cart miniのパッケージを以下のコマンドでインストールしてください

``` sh
$ cd CATKIN_WORKSPACE/src
$ wstool init
$ git clone https://github.com/open-rdc/t_frog_ros_pkgs
$ cd t_frog_ros_pkgs
$ wstool merge t_frog_ros_pkgs.install
$ wstool update
$ cd CATKIN_WORKSPACE
$ rosdep install --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y
$ catkin_make
```

まだ作りかけなので不具合が出たらただちに報告してください。迅速に対処します。

**Comment by ximomoi** [comment]
自分のPCにyp-spurがインストールされていなかったので
yp-spurをインストールしたら出来ました。

**Comment by DaikiMaekawa** [comment]
以下にセットアップ方法と実行手順を書きます。
手順は暫定的なものなので今後修正する可能性があります。

## セットアップ

``` sh
$ roscd t_frog_ros_pkgs
$ ./install.sh
$ ./t-frog.sh #icartとPCを繋いでから
```

## 自律走行

予め作成したマップファイルを読み込ませてT-frogを自律走行させることができます。
ファイルの完全パスを指定する必要があります。
以下にカレントディレクトリにあるbazというマップファイルを読み込む場合の例を示します。

``` sh
$ roslaunch t_frog_navigation nav_static_map.launch map_file:=$PWD/baz.yaml
```

## 記録走行

ジョイスティックでT-frogを走行させ、マップを作成することができます。

``` sh
$ roslaunch t_frog_slam build_map_teleop.launch
```

**Comment by ximomoi** [comment]
``` sh
$ ./t-frog.sh
```

を、T-frogとURGのusbを挿して実行した結果

``` sh
++++++++++++++++++++++++++++++++++++++++++++++++++
YamabicoProject-Spur
 Ver. 1.13.5
++++++++++++++++++++++++++++++++++++++++++++++++++
Device Infomation
 Port    : /dev/sensors/t_frog 
Error: Cannot read pipe 'pkg-config --variable=YP_PARAMS_DIR yp-robot-params'.
Error: Cannot find parameter file.
ypspur restart
```

とエラーが出てしまいます。

**Comment by DaikiMaekawa** [comment]
おそらく、ypspurの動作に必要な手順が抜けていますね。
#30 にてインストールスクリプトを改良したのでもう一度install.shを実行してみてください。

**Comment by ximomoi** [comment]
もう一度install.shを実行してからt-frog.shした結果、今度は
Error: Can't open serial port.
と出てしまいました。

**Comment by DaikiMaekawa** [comment]
デバイスは認識されていますか？

``` sh
$ ls -l /dev/sensors/t_frog
$ ls -l /dev/ttyACM* #上が認識されていなかったら
```

**Comment by ximomoi** [comment]
map_server
ros_control
ros_controller
が不足

**Comment by DaikiMaekawa** [comment]
依存パッケージが不足していたので追加しました。
https://github.com/open-rdc/t_frog_driver/pull/6
https://github.com/open-rdc/t_frog_navigation/pull/9

また、動作させるための手順を @ximo112 に指導して自律走行させることができることを確認しました。

**Comment by DaikiMaekawa** [comment]
@ximo112 デモで使用するマップをあらかじめ作成しておきましょう。

**Comment by ximomoi** [comment]
6号館の前から池の周りのマッピングを行いました。
自律走行に移ろうとしたところ雨が降ってきてしまったため中断しました。

**Comment by DaikiMaekawa** [comment]
@yasuohayashibara オープンキャンパスのデモとして提示された要求仕様を満たすための修正を行いました。#28
複数のウェイポイントを設定できるようにしたのでこれで決められたコースを巡回させることが可能になります。

**Comment by DaikiMaekawa** [comment]
使い方を動画にまとめました。参考にしてください。 @ximo112 
[![youtube](http://img.youtube.com/vi/JwD3BvwEAJ0/0.jpg)](https://www.youtube.com/watch?v=JwD3BvwEAJ0)

**Comment by DaikiMaekawa** [comment]
オープンキャンパスで無事デモを終えたためこのタスクを完了とします。
