### ISSUE TITLE
テントの雨漏り

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#290]
ポツポツ雨漏る
縫い目から雨漏りするらしい
防水スプレー買ったほうがいい

**Comment by Nasupl** [comment]
@buzzshima 対応完了してますよね？

**Comment by buzzshima** [comment]
対策していないところからもれたので改善

**Comment by buzzshima** [comment]
@iou16  アイロンを持ってくる

**Comment by Nasupl** [comment]
@atsushi10mino 「これ以上アイロンかけるところはない」
