### ISSUE TITLE
足りないものを買う

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#294]
* 布テープ
* ダクトテープ
* 防水スプレー( #290 )
* PPシート

**Comment by yasuohayashibara** [comment]
長島君からのメールを転送
---
M1 長島です．

この前のミーティングで話した購入品です．
添付ファイルの発注お願いします．

よろしくお願いします．

[tc発注リスト.xlsx](https://github.com/open-rdc/orne_navigation/files/1394699/tc.xlsx)

**Comment by yasuohayashibara** [comment]
発注しました．

**Comment by buzzshima** [comment]
届いた
