### ISSUE TITLE
地図の編集

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#296]
* βの全体マップとセンター広場マップのマージ
* ノイズ除去

**Comment by ShotaroTerato** [comment]
open-rdc/orne_maps@1a35f63 open-rdc/orne_maps@7a7cefe で #295 も合わせて対応。

**Comment by Hiroki-Goto** [comment]
PRを投げる

**Comment by ShotaroTerato** [comment]
open-rdc/orne_maps#31
プルリクエスト

**Comment by Nasupl** [comment]
@ShotaroTerato αについてはノイズ除去は必要ないということでよろしいですか？
