### ISSUE TITLE
すべてのマシンをKineticに移行する

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#299]
複数のメインストリームで開発していると混乱を招くので、現在ROS Indigoが動いているマシンをROS Kineticにすべて移行する。
この移行を持ってIndigo-develはEOLとする。

**Comment by Hiroki-Goto** [comment]
x240は予備用にindigoのままにする

**Comment by Hiroki-Goto** [comment]
２月中旬ごろから開始する

**Comment by Hiroki-Goto** [comment]
wikiは @Hiroki-Gotoが変更する
インストールは3年生がやる

**Comment by Nasupl** [comment]
@Hiroki-Goto インストールとWikiの更新だけでなく、indigoとkineticのブランチが分かれてからindigoのブランチで行われた開発・変更をkineticのブランチにマージする作業も必要になります。

**Comment by Hiroki-Goto** [comment]
[diff.txt](https://github.com/open-rdc/orne_navigation/files/1718308/diff.txt)
diffで確認できた変更

**Comment by Hiroki-Goto** [comment]
現状の状況
- [x] icart側のマージ 
- [x] orne_navigationの変更
- [x] wikiの変更

**Comment by Hiroki-Goto** [comment]
移行できる状態になった
