### ISSUE TITLE
yp-spurを使ったt-frogの動作確認

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#3]
任意の軌道を描かせたり、オドメトリを取得するためのプログラムを作成する。

**Comment by DaikiMaekawa** [comment]
yp-spurのAPIドキュメントに目を通し、一通り仕様を理解した。
また、任意の軌道を描かせるテストプログラムの作成を行った。
組立後のt-frogで動作確認を行おうとしたが、バッテリーがチャージされていなかったため今後時間ができた時に行う予定

**Comment by DaikiMaekawa** [comment]
@open-rdc/tsukuba-challenge チャージャーの置いてある場所が分かる方は教えていただけると助かります。
また、この時期は台車の使用頻度が上がると思いますのでバッテリーの過放電を防ぐ意味でもこまめに充電することにしましょう。

**Comment by DaikiMaekawa** [comment]
yp-spurでT-frogを制御するための開発環境を構築し、実際にプログラムを書いて動かしてみました。

#### 動画はこちら

[![youtube](http://img.youtube.com/vi/TbPHzoo9trI/0.jpg)](https://www.youtube.com/watch?v=TbPHzoo9trI)

**Comment by DaikiMaekawa** [comment]
yp-spurを自分のプログラムに組み込んでT-frogを制御することができたためこのタスクは閉じます。
今後はyp-spurをROS上で動かすための仕組みについて開発を行います。

**Comment by yasuohayashibara** [comment]
さすがspurですね．きっちり90度回転していますね．たしか，フィードバックだけではなく，フィードフォワードも入れて精度を高めていたと思います．
