### ISSUE TITLE
Rvizの設定ファイルをfulanghua_waypoints_navの新しい実装に合わせる

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#303]
https://github.com/open-rdc/fulanghua_navigation/pull/66 にてfulanguhua_waypoints_navから吐出される可視化用waypointsトピックがMarkerArayからPoseArrayに変わったので，こちらのnav.rvizをこれに合わせる．

**Comment by iou16** [comment]
ついでに不要と思われるtopic群も削除してしまいました. 『そのtopic必要!』と言う方は教えて下さい.

**Comment by iou16** [comment]
kinetic-develにも変更を適応する.

**Comment by Nasupl** [comment]
αでwaypointsのPoseArrayが出ない
