### ISSUE TITLE
base_local_plannerのtolerance変更

### ISSUE THREAD

**Issue by iou16** [open-rdc/orne_navigation#306]
yaw_goal_toleranceの設定がデフォルト(0.05 rad = 2.864789 deg)になっている. シビアすぎると, 向きが合わずにいつまで経ってもactionlib::SimpleClientGoalState::SUCCEEDEDしない. 
(10 deg = 0.174533 rad)ぐらいでいい.

**Comment by Nasupl** [comment]
キリがいいし0.2radでどうっすか？（10degという値にも特にエビデンスはないし）

**Comment by iou16** [comment]
了解です.

**Comment by iou16** [comment]
人物探索で問題視されている事象なので, 今回は, indigo-devel側のみにpullreqを送る.
