### ISSUE TITLE
空気圧の確認(ついでにオドメトリ)

### ISSUE THREAD

**Issue by buzzshima** [open-rdc/orne_navigation#315]
ホイールオドメトリの精度が空気圧にどれくらい依存しているかの確認

**Comment by buzzshima** [comment]
両機体ともに適正空気圧(210ｋpa)より下がっていて適正まで空気圧を入れた．(そのときbetaはもともとの空気圧が低すぎたためか空気を入れた時機体がジャッキアップしたみたいに上がった) 
また空気圧の調整前後でのホイールオドメトリのチェックした．

実験は簡易的行った．
- 2号館3階を一周し計測
- 調整前後で同じ速度で走行したが経路は異なる(コースと始点と終点は同じ)

調整前は赤いライン
調整後は黄緑ライン
alphaのホイールオドメトリ
![a pha](https://user-images.githubusercontent.com/12147191/32264185-cb124e10-bf20-11e7-97a6-6849b75c5ed2.png)
＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿
betaのホイールオドメトリ
![beta](https://user-images.githubusercontent.com/12147191/32264207-e3f0b73c-bf20-11e7-9406-7d7ae8a5c19b.png)

# 感想
両機体ともに空気圧を適正のほうが真値近くなったがだいぶかけ離れている．alphaはパラメータの設定ミスを疑うほどずれている．

**Comment by Nasupl** [comment]
@buzzshima 
現在のαのパラメータ，
RADIUS[1] 0.148569 # 0.148493 #0.150044 #0.149044 #0.150
TREAD 0.56 #old_0.449592 #0.450
ですが，合ってますでしょうか？

**Comment by yasuohayashibara** [comment]
#319 でコメントしてしまいましたが，こっちに空気圧の議論がありました．
同じ圧力でこれだけずれるのですね．
意図的に圧力を変えてずらすのもあまり良くないと思いますので，先ほどの空気圧の議論は無しで．

左右のホイールの半径の設定があるのであれば，それで対処できそうですね．
