### ISSUE TITLE
alphaの機体パラメータの変更

### ISSUE THREAD

**Issue by buzzshima** [open-rdc/orne_navigation#319]
#315 でαのホイールオドメトリがオドメトリがあまりにもずれていたので機体のパラメータを見たら違っていたのでパラメータを変更して計測した．
![param](https://user-images.githubusercontent.com/12147191/32272362-1472e504-bf41-11e7-886b-e1c9388b36ab.png)
＿＿＿＿＿＿＿＿＿＿
変更前のやつ
![a pha](https://user-images.githubusercontent.com/12147191/32272404-3d8ec14c-bf41-11e7-988e-6e60e018a94b.png)

変わってないような............

**Comment by Nasupl** [comment]
マシにはなっているのでは

**Comment by yasuohayashibara** [comment]
どちらにしてもひどいですね．100m走行すると90度以上ずれる計算ですね．
（修正前のパラメータだと180度以上）

つくばチャレンジの2kmのコースを走行すると5回転(1800度)ほどずれる計算です．
まあ実際にはIMUで方位を求めているので問題ないかもしれませんが，できるだけ直進できるようにホイールの空気圧を調整したほうがよいと思います．
（もしくは左右のアンバランスを調整するパラメータがあれば，その修正でも構わないかもしれませんが．．．）

このような基礎的なデータは問題がどこにあるかを明確にできるので重要ですね．

#315 にコメントを追加しました．

**Comment by Hiroki-Goto** [comment]
@buzzshima  がタイヤの径のパラメータを変更して実験する
