### ISSUE TITLE
BRIXにi-Cart miniの開発環境をセットアップする

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#32]
- [x] Ubuntu14.04LTSのインストール
- [x] ROS Indigoのインストール
- [x] [i-Cart mini ROS Packages](https://github.com/open-rdc/t_frog_ros_pkgs)のインストール

**Comment by DaikiMaekawa** [comment]
@ximo112 セットアップはお任せします。
早めに終わらせてください。

**Comment by Nasupl** [comment]
T-frog ROS Packagesのインストールまでは完了しました。動作確認はまだ行っていません。

**Comment by DaikiMaekawa** [comment]
@ximo112 動作確認をお願いします。

**Comment by ximomoi** [comment]
動作確認が完了したので閉じます．
