### ISSUE TITLE
BRIXの電源供給方法について

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#33]
BRIXを駆動させるためには１９Vの電源を供給する必要があります。

**Comment by DaikiMaekawa** [comment]
@Nasupl よろしくお願いします。

**Comment by DaikiMaekawa** [comment]
バッテリーの選定中です。

**Comment by Nasupl** [comment]
4A出力可能なモバイルバッテリー(ex.http://goo.gl/n27nUG ）か、現在i-Cartで使用しているバッテリーをさらに1台搭載して、インバータで昇圧するかのいずれかかと思っています。動作可能時間はあまりどちらを採用しても変わらないかなという感じですが、モバイルバッテリーの方は信頼性が・・・という感じがあるので、どうしようかという感じです。

**Comment by DaikiMaekawa** [comment]
@Nasupl どちらも運用しにくそうで悩ましいですね。

**Comment by DaikiMaekawa** [comment]
リポも視野にいれて考えましょう。
候補の選定を早急にお願いします。 @Nasupl

**Comment by ItoYusuke** [comment]
LiPoの使用は控えたほうがいいと思います．
コンスタンスに消費されるので，インバータを介した場合でも傷める可能性があります

2014-10-02 17:40 GMT+09:00 Daiki Maekawa notifications@github.com:

> リポも視野にいれて考えましょう。
> 候補の選定を早急にお願いします。 @Nasupl https://github.com/Nasupl
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/open-rdc/icart_mini_ros_pkgs/issues/33#issuecomment-57599063
> .

## 

---

千葉工業大学
工学部 未来ロボティクス学科
1126016 伊藤 裕介
Tell ：080-8852-6003
MailAddress ： itoyusuke.mobilemail@gmail.com

**Comment by DaikiMaekawa** [comment]
なるほど。しかし、悩ましいなぁ :disappointed_relieved:
始めるからノートPC買うべきだったかもね。
何かいい案ないですか？ @ItoYusuke

**Comment by ItoYusuke** [comment]
今のバッテリーの重さ次第ですが，
9kg程度のバッテリに切り替えて容量をアップし，インバータで提供するのかいいかと
インバータは12V->19V 3.5Aの既製品があります．

2014年10月2日 19:18 Daiki Maekawa notifications@github.com:

> なるほど。しかし、悩ましいなぁ [image: :disappointed_relieved:]
> 始めるからノートPC買うべきだったかもね。
> 何かいい案ないですか？ @ItoYusuke https://github.com/ItoYusuke
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/open-rdc/icart_mini_ros_pkgs/issues/33#issuecomment-57609151
> .

## 

---

千葉工業大学
工学部 未来ロボティクス学科
1126016 伊藤 裕介
Tell ：080-8852-6003
MailAddress ： itoyusuke.mobilemail@gmail.com

**Comment by Nasupl** [comment]
@ItoYusuke 
現在のバッテリーは、1個辺り2kgの鉛蓄x2個なので、合わせても4kgです。
通常の自動車用バッテリーに切り替えるのは電源の選定としては妥当なように思えますが、機体の大幅な構造の変更を要するのが問題かと感じます。
BRIXの定格を再度確認したところ、最大定格で3.4Aということですので、19V3.5A出力可能なモバイルバッテリー等（下記URL参照）複数用意し、交換しながら使用するのが（納期や構造変更等の時間を考慮すれば）妥当な着地点かと思いますが、いかがでしょうか。
参考）
http://www.jtt.ne.jp/products/original/xp18000a/index.html
http://goo.gl/n27nUG

**Comment by ItoYusuke** [comment]
そうですね．ベターな選択かと思います

**Comment by DaikiMaekawa** [comment]
モバイルバッテリーということで不安は残りますが、実用に耐えうるかどうかは使ってみなければわからないところもありますね。　最終的に購入する機種の型番をください。 @Nasupl 
まとめて購入してみましょう。

**Comment by Nasupl** [comment]
少々高価ですが、http://kakaku.com/item/K0000668775/ を2台調達できるとよいのではないかと思います。

**Comment by yasuohayashibara** [comment]
実験走行会までに時間がありませんので，もし早急に購入する場合は，早めに購入希望をお送り下さい．

**Comment by DaikiMaekawa** [comment]
@yasuohayashibara http://kakaku.com/item/K0000668775/ を2台購入してください。

**Comment by yasuohayashibara** [comment]
amazonで１個購入しました．（２つ以上は購入できないようです．）10/9着予定です．

**Comment by DaikiMaekawa** [comment]
@yasuohayashibara amazon以外でもう一つ調達出来ないでしょうか？
それが難しいのであればもう一種類別のバッテリーを選定します。

**Comment by yasuohayashibara** [comment]
ちなみに，バッテリ１個で何時間駆動できますでしょうか．２つ必要な説得力がほしいです．

**Comment by DaikiMaekawa** [comment]
@Nasupl @ximo112 本日、モバイルバッテリーが一つ届いているはずなので動作確認も兼ねて、プレ試走会時に走行した経路の地図を作成してください。
IMUが使えるようになったので精度は向上しているはずです。

**Comment by yasuohayashibara** [comment]
@Nasupl バッテリはどうでしょうか．明らかに足りないようであれば調達します．もし４時間程度持つのであれば，１個でお願いします．

**Comment by Nasupl** [comment]
@yasuohayashibara 
BRIX上でUbuntuを起動させて、ディスプレイに給電し続ける試験をしましたが、12時間程度持ちました。
あくまで憶測に過ぎませんが、通常のナビゲーションなどを行う分には、4時間程度は持つのではないかと考えられます。
しかし一方で、予備がないというのは少々恐ろしいものがあるので、小容量のバッテリーを1台予備として購入していただけると助かるのですが、いかがでしょうか。

**Comment by Nasupl** [comment]
BRIXのUbuntu上でicart_miniのrosパッケージを動かすと、デバイス回りに不具合が出ることがあるので、出力される電源の電圧や電流について調べる必要があります。

**Comment by DaikiMaekawa** [comment]
@Nasupl 
時間的にその余裕はないのでBRIXの採用は見送ります。
