### ISSUE TITLE
地図の解像度を粗くしてみる

### ISSUE THREAD

**Issue by iou16** [open-rdc/orne_navigation#335]
現在の占有格子地図の解像度は0.05[m]だが, 屋外で自律走行するならそこまで細かくなくていいのかも知れない.  少し試してみたい. どの程度の解像度が適切だが要検討.

**Comment by buzzshima** [comment]
画像編集ツールで試してみる

**Comment by ghost** [comment]
画像編集ツール、でmapの解像度って変えられるんですか？
思ったのが、build_mapみたいなのを走らせる時の解像度を0.05[m]から0.1[m]や0.2[m]などマップを複数つくってそれぞれで同じコースを自律移動させるのがよいでしょうか

**Comment by atsushi10mino** [comment]
pgm形式だと解像度を下げることができないようなので地図生成時の解像度を下げて実験する

**Comment by taishiyamamoto** [comment]
植田君にも担当してもらうことになりました。
memberに招待した後、assignする。

**Comment by hoshianaaa** [comment]
gmappingのパラメータを変更すれば解像度を変更できます
![gmapping_ch_delta](https://user-images.githubusercontent.com/40942409/70338889-13d0d880-1891-11ea-9420-4ba639c8a557.png)
orne_navigation_executor/build_map_teleop.launch内

**Comment by taishiyamamoto** [comment]
地図のリサイズを1ピクセル辺り0.1mの状態で自己位置推定を行わせて見ました．
わかったこととして，amclで占有格子地図を元に尤度場を生成する際の時間が短くなりました．
自己位置推定の精度に関してもパーティクルの広がりは従来（0.05m/pixel）のときとあまり大差ないように思いました．
個人的には地図の解像度は0.1mの分解能で生成しても特に問題ないと考えております．
https://youtu.be/VPx8Lzc-A-U

**Comment by yasuohayashibara** [comment]
分解能0.1mの採用賛成します．

**Comment by tiger0421** [comment]
今後のマップの解像度は0.1mと決定しましたので，クローズします．
