### ISSUE TITLE
後方視界の検討

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#337]
障害物の回避や衝突時の復帰にはやはり後方視界が必要だと考えられる．以下のようなセンサを搭載し後方視界を確保することを検討する．
以下に考えられる方法を例示する．

* 安価な2D LIDAR
[RP LIDAR](http://www.robotshop.com/jp/ja/rplidar-a2-360-laser-scanner.html)のような安価で小型なLIDARを搭載する．
ロボットの後方に障害物があるのかないのかさえ分かれば十分なので，安価な製品で十分．安価な製品といえど$500近くするのが難点．

* 1Dのレーザー距離センサ
[VL53L0X](https://www.switch-science.com/catalog/2894/)のような距離センサを複数搭載する．ROSで使用するための開発コストが大きい．視野が狭いので複数取り付けが必要．

* 超音波センサ
[MaxSonar](http://akizukidenshi.com/catalog/g/gM-08238/)のような超音波センサを搭載する．レーザー距離センサと比較すると指向性が低いので，１個のセンサで広い領域をカバーできる（どの方角にあるかはわからないが）のがメリット．これもROSで使用するための開発コストがは大きい．

**Comment by yasuohayashibara** [comment]
ミーティングで話しましたが，もう一つTOP-URGを搭載するという方法があります．
ロングレンジの測域センサを付けることで，自己位置推定の安定性も上がります．

**Comment by Nasupl** [comment]
Top-URGとRPLIDAR A2を比較できるようなデータを取得した（角度が若干ずれているが）
https://photos.app.goo.gl/1R4CzvfMxS0llCmk2
RPLIDARのレンジは6m程度であった．また，Top-URGと比較してデータのばらつきが大きいことがわかる．

**Comment by buzzshima** [comment]
@Pethon 
取り付け用パーツ完成
取り付け位置 姿勢(前方urgとくらて)
xとyは同じでzが- 400mm
yaw軸に180度回転

でこの位置でurdfを書いて下さい

斜めURGを参考に

**Comment by buzzshima** [comment]
後ろ向きURGのものを加工した(取り付けジグを追加するかも)
位置と姿勢は baselink

x -0.34  y 0 z 0.22
yとｚは前方urgと同様
取り付け位置

姿勢は   yaw軸に180度(3.14 radian)回転



urdfは斜めurgの参考にして(/orne_description/urdf/orne_alpha.xacro)  
 変更はβのみorne_description/urdf/orne_beta.xacro) 行う

#249 が似たもの 

@Pethon

**Comment by yasuohayashibara** [comment]
できれば図や写真を載せてください．

**Comment by Pethon** [comment]
x -0.34 y 0 z 0.22という位置で試したら、このような状態になっています。
URGが浮いているけど、大丈夫ですか？
<img width="1280" alt="screen shot 2018-07-24 at 9 25 34" src="https://user-images.githubusercontent.com/19383917/43109808-a5447a4a-8f23-11e8-8c49-7cf773f34ddb.png">

**Comment by buzzshima** [comment]
センサだけ情報を追加したから妥当だと思います

取り付け板とかの情報書いてないですよね？

**Comment by Hiroki-Goto** [comment]
あとicart_middle.gazeboも変更を行う

**Comment by Pethon** [comment]
2つのURGのデータを合成できるノードがあるようなので、そのノードが使えるかどうかを調べてみる。

**Comment by buzzshima** [comment]
取り付けたいけど後入れナットが到着しだい取り付け

**Comment by Pethon** [comment]
前と後ろのlidarをシミュレーター上で合成してみました．
[https://youtu.be/Mpz3O_LSY5k](https://youtu.be/Mpz3O_LSY5k)

**Comment by Hiroki-Goto** [comment]
@Pethon fix_scan_#337ブランチにてgazebo上でscanトピックを出ないようにしました

**Comment by Hiroki-Goto** [comment]
@Pethon が後入れの発注する

**Comment by buzzshima** [comment]
取り付け完了
![picture1](https://user-images.githubusercontent.com/12147191/46459527-27e3fa80-c7f4-11e8-9b29-ccc7abc66abc.png)

**Comment by Pethon** [comment]
後ろのlidarを利用して自己位置推定できるのをシミュレーター上で確認しました．
[https://youtu.be/1wfOm5yBxzc](https://youtu.be/1wfOm5yBxzc)

**Comment by Pethon** [comment]
実機を用いて、実験を行いました。
動画[https://youtu.be/wluyvotoV8k](https://youtu.be/wluyvotoV8k)

**Comment by yasuohayashibara** [comment]
人が後ろからついていくと，後ろにコストが残りますね．
つくばチャレンジでは問題にならないと思いますが，屋内の自律移動のときには問題になるかもしれません．
コストを残す時間を短くしたほうが良いかもしれません．

**Comment by buzzshima** [comment]
＠buzzshima レビューして閉じる
