### ISSUE TITLE
neo-navigationの検討

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#338]
#238 でやりたいことは[neo-navigation](https://github.com/at-wat/neonavigation)でできそう

**Comment by DaikiMaekawa** [comment]
@nasupl Are you guys still interested in that package? I can give you some advices if you want.

**Comment by Nasupl** [comment]
@DaikiMaekawa I have not been commit in development of this project already.
@Hiroki-Goto Are you planning to use neo-navigation?

**Comment by Hiroki-Goto** [comment]
@DaikiMaekawa I am glad about your proposal. However we are not planning to use neo-navigation.
