### ISSUE TITLE
反射的な障害物回避の実装

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#339]
move_baseはコストマップの更新が遅れるようなシチュエーションにおいて，障害物が回避できないことがある．これに対応するため，生のセンサデータから障害物を検出して停止，もしくは回避するための仕組みが必要．

**Comment by buzzshima** [comment]
@Pethon  がメインに 来週から取りかかる

**Comment by Hiroki-Goto** [comment]
停止する方向で行く

**Comment by Pethon** [comment]
障害物を認識できたら，停止のcmd_velを送るゲートノードを作成しました．
実験動画
[https://youtu.be/zkzqGFSLVlQ](https://youtu.be/zkzqGFSLVlQ)

今後の課題，停止した後の回避行動(リカバリー行動)を作成する．

**Comment by buzzshima** [comment]
@Pethon 
マージしてからクローズする
