### ISSUE TITLE
電装の改良

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#341]
電装の全体的な改良が必要
* 電源周辺
  * 12V電源の生成方法
  * 搭載したままでのバッテリー充電
* 緊急停止周辺
  * βにもつける
  * リレーが電力を食い続ける
* 意思表示関連
  * 状態を報せたい
      * パトランプ，スピーカー等
* 制御盤
  * スイッチ関連の配線

**Comment by Nasupl** [comment]
### 緊急停止周辺について
モータドライバの駆動用電源に低ESRキャパシタを入れれば誘導電流によってモータドライバが破壊されたり，手押ししている時にガタガタとすることはない．
遮断回路は更なる安全策として有用だが，回路が複雑化しメンテナンス性が低下するため廃止する．

**Comment by Hiroki-Goto** [comment]
音声
・ソフトがいいのがあれば青木に相談する
・ @buzzshima の音声をつかう（第一候補）

**Comment by Hiroki-Goto** [comment]
音声に関しては #349 と別のissueとしてたてた

**Comment by Hiroki-Goto** [comment]
@daiki-shibahara 電圧計の消費電力を確認する

**Comment by daiki-shibahara** [comment]
![5590](https://user-images.githubusercontent.com/28525055/39176320-7fd088c2-47e7-11e8-9d57-c88cd9c78887.jpg)
この画像の回路の製作を行う。
現時点では、Ltspiceを使ったシミュレーションを行っている

**Comment by daiki-shibahara** [comment]
切削基板での作成が完了したため,動作実験を行う.

**Comment by daiki-shibahara** [comment]
切削基板での動作確認が完了したため,プリント基板の発注を行う.

**Comment by Hiroki-Goto** [comment]
ellecrowで発注してから閉じる
届いたら動作テストする

**Comment by daiki-shibahara** [comment]
発注しました

**Comment by atsushi10mino** [comment]
足りない部品を購入する

**Comment by daiki-shibahara** [comment]
部品の購入を行い，基板を取り付け動作確認が取れたため，閉じます．
