### ISSUE TITLE
kinetic シリアル通信問題

### ISSUE THREAD

**Issue by buzzshima** [open-rdc/orne_navigation#347]
ボーレートが合わないとエラーが出ることも何度かあった．

しかしどのタイミングで出るのかがわからないでそれも調査

**Comment by atsushi10mino** [comment]
http://t-frog.com/forums/forum.php?ml=tf-2md3-devel&read=172
同じ症状

**Comment by buzzshima** [comment]
現状問題になっていないので閉じる

**Comment by atsushi10mino** [comment]
16.04の再インストール
ROSのインストール
ORNEの環境構築を行った

**Comment by atsushi10mino** [comment]
10分以上起動していたが特に問題は起きなかった
![screenshot from 2018-06-05 14-21-13](https://user-images.githubusercontent.com/28559070/40956888-78ca219e-68cd-11e8-9cb4-62a4eb25e0ba.png)

**Comment by atsushi10mino** [comment]
おそらく問題ない？
追記：約一時間程度起動させ続けたが通信が切れる様子はなかった
![screenshot from 2018-06-05 14-21-13](https://user-images.githubusercontent.com/28559070/40957031-2eeb7fa4-68ce-11e8-9330-bfcc2bfd8cd8.png)
