### ISSUE TITLE
不足している部品の購入

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne_navigation#348]
不足している部品を購入
故障している部品の修理

**Comment by yasuohayashibara** [comment]
以下，部品の購入と修理
- [x] 電圧計　
- [x] モータドライバ

**Comment by yasuohayashibara** [comment]
電圧計を3つ購入した
https://www.amazon.co.jp/gp/product/B00DD9W4O0/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1

**Comment by yasuohayashibara** [comment]
@Hiroki-Goto モータドライバの故障の詳細を送ってください．

**Comment by yasuohayashibara** [comment]
後藤くんから

故障診断に関しては以下のとおりとなります
現象：モータドライバとの通信はできるが、速度指令をモータが動作しない問題
がある。トラブルシューティングを見たところFETかゲートドライバの故障があ>るかもしれないと出てきました

-----

【林原】
年度始めなので，この時期に予算が使用できるか大学に確認しなければなりませんが，修理を依頼を出したいと思います．

**Comment by Hiroki-Goto** [comment]
修理の許可申請の回答まち

**Comment by yasuohayashibara** [comment]
修理の許可を得て，修理して納品されました．
issueを閉じます．
