### ISSUE TITLE
ORNEに意思表示をさせたい

### ISSUE THREAD

**Issue by Hiroki-Goto** [open-rdc/orne_navigation#349]

**Comment by Hiroki-Goto** [comment]
今まで
ROSのパッケージのの一つにaudio_commonがあったが日本語を使う場合テキスト読み上げソフトを使う必要があり、個人利用の範疇を超えるかもしれず利用規約的に面倒

この問題に対し
- 青木さんに相談してみる
- @homeで使用したソフトを用いる
- 誰かの音声を録音し編集する
が挙げられた

**Comment by Hiroki-Goto** [comment]
青木さんに相談したところ、
- @homeで使用したソフトは研究室製のため共有はできない
- openjtalkが修正BSDライセンスで比較的使いやすい
と意見という意見をもらった
ひとまず、openjtalkを使ってみる方針で進める

**Comment by Hiroki-Goto** [comment]
英語でも問題なさそうなのでaudio_commonを使う

**Comment by Hiroki-Goto** [comment]
音声だと聞こえない可能性があるので電子音を試す

**Comment by Hiroki-Goto** [comment]
最初はstart wp points navから

**Comment by Hiroki-Goto** [comment]
サービスだとひとつのノードしか送れなかったため, sound_play側は最初のゴール（waypoint）が送られたらスタートしたと認識するノードの作成を行った。

（音声はまだ鳴らしていない）

**Comment by buzzshima** [comment]
aplayを使用して見る

**Comment by Hiroki-Goto** [comment]
wp通過時に電子音をならせてみた
[実機での動画](https://youtu.be/2kMenJaMxOs)

**Comment by daiki-shibahara** [comment]
launchfile作成の次にpull requestを送る

**Comment by Hiroki-Goto** [comment]
wp通過時のみ鳴らすようにする（tfを使う）
