### ISSUE TITLE
i-Cart miniのURG振りサーボ交換

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#35]
現在t-frogには故障したサーボが搭載されているので、交換する必要があります。

**Comment by DaikiMaekawa** [comment]
@yasuohayashibara  futabaサーボとRS485の変換器をロボカップからもらいます。

**Comment by yasuohayashibara** [comment]
どうぞご利用下さい．ロボカップ側で数が減って支障が出そうであれば，お知らせ下さい．

**Comment by Nasupl** [comment]
取り付け完了したので閉じます
