### ISSUE TITLE
つくばチャレンジ2018に向けた開発

### ISSUE THREAD

**Issue by Hiroki-Goto** [open-rdc/orne_navigation#351]

**Comment by yasuohayashibara** [comment]
１）幾何学的に正しい地図　　　　　　　　　　　　【長尾，美濃】
　　専有格子地図
　　反射強度地図 → 学習により分類できるか？
２）経路生成　　　　　　　　　　　　　　　　　　【近藤】
３）GPSリセット 　　　　　　　　　　　　　　　　【後藤】

４）反射強度を用いた自己位置推定 or 障害物回避　【芝原】
５）信号機検出　　　　　　　　　　　　　　　　　【赤松】
６）探索対象者の発見　　　　　　　　　　　　　　【阿部，中村】

**Comment by buzzshima** [comment]
白線での一時停止機能追加　【パシン　長島】 #346  の流用

**Comment by buzzshima** [comment]
プラスアルファとして
visual SLAM 【ワタナベ　小笹】
