### ISSUE TITLE
経路計画（+navigation）

### ISSUE THREAD

**Issue by Norihiro02** [open-rdc/orne_navigation#353]
取り敢えずturtlebot_navigationでは、経路が塞がれても自動で再度経路計画をおこなうということが分かった。
↓
どの様に移植するか。

**Comment by Norihiro02** [comment]
turtlebot_navigation
https://github.com/turtlebot/turtlebot_apps/tree/indigo/turtlebot_navigation

**Comment by yasuohayashibara** [comment]
後で見返した時に，そのときの状況が分かるように，できれば動画をYoutubeなどにアップしてリンクを張っておいてもらえると助かります．
言葉だけだと忘れてしまいますので．．．

> 取り敢えずturtlebot_navigationでは、経路が塞がれても自動で再度経路計画をおこなうということが分かった。
> ↓
> どの様に移植するか。

**Comment by Norihiro02** [comment]
turtlebot_navigationの動画です。　
https://www.youtube.com/watch?v=LPhcNcJsR5w&feature=youtu.be

**Comment by Hiroki-Goto** [comment]
https://github.com/open-rdc/fulanghua_navigation/blob/indigo-devel/fulanghua_waypoints_nav/src/waypoints_nav.cpp
にclear costmapのサービスがあるっぽい

**Comment by Norihiro02** [comment]
turtlebotとorneの比較してわかった事
1. 使用しているplanner系のplaginは同じ
2.  waypointの間隔が異なる
　turtlebot：実験時に設定しているのはstartとgoolだけ
　orne:細かくwaypointを設定している(数メータ単位)

現状ではwaypointを細かく設定し、1つの経路としている。
　別のwaypointを設定しないと別経路を生成することができない。

仮説
選択課題(項目B)をおこなう場合チェックポイントのみにwaypointを設置すればOK？
　globalPathの生成に時間がかかりそう...

**Comment by Norihiro02** [comment]
通過しなければならないチェックポイントまでのwaypointを求める。

チェックポイントをnode、道をedgeとするグラフを作成。
現在地から指定チェックポイントをまでに通るチェックポイントを求め、それをwaypointにする。
（指定チェックポイントのみwaypointを設置するよりも生成するGlobalPathが短くなる。）
行き止まりに遭遇した場合、直前に通ったチェックポイント（node）からの経路（waypoint）を再度生成。

**Comment by Norihiro02** [comment]
メモ：やることリスト

- [x] スタートからゴールまでwaypoint無しで100m位で動かしたときにどうなるか。
- [x] globalplannerの時間周期の調査（１[Hz]より遅くても良いのでは？）

**Comment by Norihiro02** [comment]
公園内に関しては
チェックポイントをnode
道をedge
とするグラフを作成し、各nodeに位置情報を加える。
このグラフを使用すれば「任意のチェックポイントを通る最短経路」を生成することができる。
さらに各node(チェックポイント)の位置情報をwaypoinファイルに出力すれば現状のシステムでも課題達成できそう。

**Comment by Norihiro02** [comment]
5分前ルールは無し（こっちの思い込みであった）
現状：ロボットは一つの経路をたどる事しかできない。
やりたい事：ロボットが任意の経路を選択できるようにする。

以前作ったwaypointファイル生成プログラムを移植して作る

**Comment by Norihiro02** [comment]
グラフは手動で作り、以下のようにnavigationをすることができた。
https://youtu.be/5KtCJokeFvY

**Comment by Hiroki-Goto** [comment]
計算に関しては一旦閉じる
