### ISSUE TITLE
電装の改良（スイッチ版）

### ISSUE THREAD

**Issue by Hiroki-Goto** [open-rdc/orne_navigation#356]
逆起電力防止装置（#341 で作成したリレー）などがないとモータドライバの故障が頻繁に起きるため、防止用の回路（？）を作成する

スイッチでモータの線を切断する方向で作成

**Comment by Hiroki-Goto** [comment]
必要な部品
- LED（径が大きいやつ）
- トグルスイッチ（４接点）

**Comment by Hiroki-Goto** [comment]
トグルスイッチは最低10A耐電流あるもの

**Comment by Hiroki-Goto** [comment]
#192 にあった回路を追加する

**Comment by daiki-shibahara** [comment]
ミスミでは売っていなかったため,千石でセメント抵抗12個購入お願いします.
https://www.sengoku.co.jp/mod/sgk_cart/detail.php?code=2ADT-6UKM
リレーですが,γ用で使うかもしれないため,6つ購入お願いします.
https://jp.misumi-ec.com/vona2/detail/222000863520/?HissuCode=LY2%20DC12
リンク間違えていました.

**Comment by daiki-shibahara** [comment]
![img_20180719_224618](https://user-images.githubusercontent.com/28525055/42947043-63877ce4-8ba7-11e8-8ae1-edaec6847b3f.jpg)
#192 の追加回路作成し,セメント抵抗つけるだけです.
動作確認はその後行います.左:追加作成した回路   右:#192で作成した回路

**Comment by yasuohayashibara** [comment]
ミスミで販売していますよ．
例）SQMW51R0J

リレーのリンク先ですが，１３５個の候補があるそうです．
![image](https://user-images.githubusercontent.com/5755200/42976700-1020acb8-8bfe-11e8-8e49-15e312c7105c.png)

**Comment by daiki-shibahara** [comment]
リレーのリンク先間違えていました.以下を6個お願いします.
https://jp.misumi-ec.com/vona2/detail/222000863520/?HissuCode=LY2%20DC12
ミスミでセメント抵抗見つけました.5個単位での発注のため15個お願いします.
https://jp.misumi-ec.com/vona2/detail/222005596090/?HissuCode=SQBW2010RJ&PNSearch=SQBW2010RJ&KWSearch=SQBW2010RJ&searchFlow=results2products

**Comment by yasuohayashibara** [comment]
リンク先を見直してください．
![image](https://user-images.githubusercontent.com/5755200/43029593-a40391b0-8cc2-11e8-9a25-fde879ac5e84.png)

> ミスミでセメント抵抗見つけました.5個単位での発注のため15個お願いします.
> https://jp.misumi-ec.com/vona2/detail/222005596090/?HissuCode=SQBW2010RJ&PNSearch=SQBW2010RJ&KWSearch=SQBW2010RJ&searchFlow=results2products

**Comment by daiki-shibahara** [comment]
リレー(LY2 DC12)を6個
セメント抵抗'(SQBW2010RJ)を15個ミスミで発注おねがいします.

**Comment by yasuohayashibara** [comment]
シャーシマウントの抵抗になっていますが正解？
https://jp.rs-online.com/web/p/panel-mount-fixed-resistors/1614267/

**Comment by yasuohayashibara** [comment]
こちら回答が来てから発注しますので，回答お願いします．
以下を見る限り，シャーシマウントの抵抗では取り付けにくいのではないかと思います．
https://github.com/open-rdc/orne_navigation/issues/356#issuecomment-406287103

**Comment by daiki-shibahara** [comment]
![img_20180815_144827](https://user-images.githubusercontent.com/28525055/44135182-f8a04cb0-a0a2-11e8-82c9-35adadd2e759.jpg)
回路の方作成し終わりました．
動作確認お願いします．
上　従来の　下新しく作成したもの

**Comment by Hiroki-Goto** [comment]
αのほうには実装しました
![8531212051071](https://user-images.githubusercontent.com/12184572/45201977-52ed3400-b2b2-11e8-9f78-d3d953520798.jpg)

**Comment by daiki-shibahara** [comment]
リレーに電源が入っていない時は緩やかに押すように
