### ISSUE TITLE
velodyneの搭載

### ISSUE THREAD

**Issue by Hiroki-Goto** [open-rdc/orne_navigation#358]
つくばチャレンジでvelodyne(VLP-16)を使えるようにする

**Comment by Hiroki-Goto** [comment]
![velodyne_test](https://user-images.githubusercontent.com/12184572/41964573-4956bd0e-7a35-11e8-9d36-7e52cb849bbb.png)

RVIZで表示できた
ただ、PCの電源をると再設定[velodyne wiki](http://wiki.ros.org/velodyne/Tutorials/Getting%20Started%20with%20the%20Velodyne%20VLP16)する必要があるかもれない（要検証）

**Comment by Hiroki-Goto** [comment]
αのPCで使える用にURDFを編集した

**Comment by Hiroki-Goto** [comment]
ゴール
- orne_bringupにvelodyneのlaunchの追加
- wikiを書く

**Comment by Hiroki-Goto** [comment]
wikiは書いた

**Comment by Hiroki-Goto** [comment]
bringupに追加した
実機で動いたらプルリクを送る
ただし、gazebo上で動かすと地図座標系から座標変換ができないバグがある

**Comment by Hiroki-Goto** [comment]
実機、gazeboで動くことを確認したので、プルリク(#366 )を送った

**Comment by buzzshima** [comment]
斜め付けURGのコメントアウトしてプルリクエスト

**Comment by Hiroki-Goto** [comment]
斜め付けURGの部分をコメントアウトしたのでレビューおねがいします
