### ISSUE TITLE
move_baseのグローバルパスの生成周期の検討

### ISSUE THREAD

**Issue by Norihiro02** [open-rdc/orne_navigation#360]
グローバルパスの生成周期をどれだけにするか。
デフォルト：0Hz(初回のみ実行)
現：1Hz

この変化によってどの様な影響を受けるのか

**Comment by Norihiro02** [comment]
この前(5月頃?)に行ったTurtlebotを使った実験では、1[Hz]の時は0[Hz]と比べCPUの使用率が1%ほど高かった。~~(1[Hz]:7.5%,0[Hz]:6.3%)~~
(1[Hz]:7.2%,0[Hz]:6.01%)
　Pathの生成に関しては、経路を見失ったときに両者とも再度経路を生成した。
　ただ、「Pathの生成頻度が高くて制御がうまくいかない(演算が追い付かない)問題」はglobal_plannerじゃなくてlocal_plannerの制御周期に問題ありそう(実際にcmd_valを送っているのはmove_baseのlocal_plannerであるため)

**Comment by Norihiro02** [comment]
CPU使用以外も比較(表にするとわかりやすい)

- [x] メモリ使用量も比較

**Comment by Norihiro02** [comment]
|*|*|
|||

**Comment by Norihiro02** [comment]
|| 0Hz | 1Hz |
|:---|:---|:---|
| VIRT(プロセスの仮想メモリサイズ)[KiB] | 937294.9 | 938995.5|
| RES(プロセスが使用している物理メモリ)[KiB] | 55033.6 | 56061.33|
| SHR(プロセスが使用している共有メモリ)[KiB] | 17612 | 17835.87|
| ％CPU(CPUの使用率) | 6.013333 | 7.2|
| ％MEM(実メモリ使用率) | 1.373333 | 1.386667|

**Comment by Norihiro02** [comment]
CPUの使用率とメモリの使用率(量)は0Hzより1Hzの方が若干高いが、大きな違いは現れなかった。(動作に関しても)

**Comment by yasuohayashibara** [comment]
地図データが大きくなると，急速に処理時間が長くなるような気がします．
もしできましたら，大きな地図データでも試してみていただければと思います．
（できればで構いません．）

**Comment by atsushi10mino** [comment]
確認したのでとりあえず閉じる
