### ISSUE TITLE
ガンマの製作

### ISSUE THREAD

**Issue by Hiroki-Goto** [open-rdc/orne_navigation#361]
８月の試走会に間に合わせる（予定）

**Comment by JinyaIseki** [comment]
10/13の試走会は雨がふるため防水を行う

カメラ
https://www.amazon.co.jp/gp/aw/d/B01MA1Y0FV/
で防水する

非常停止スイッチ
グルーガンで端子を覆う

基盤、バッテリー
PPシートを本体上部に貼る

ノートPC
袋に入れる

**Comment by JinyaIseki** [comment]
小さい方のγの車輪の固定をする

**Comment by JinyaIseki** [comment]
学内でのデータを使用してニューラルネットワークの学習を行った
テスト用データでaccuracyが0.80程度
これから学内での走行実験を行う

- [x] カメラのrosノードの動作確認
- [x] ニューラルネットワークのrosノードの作成
- [x] 台車制御用ノードの作成　@Pethon

**Comment by taishiyamamoto** [comment]
小さいほうのγの車輪の固定の件ですが、以下のワッシャを使えば固定することができると考えられます。
WSSS14-5-2
URL:https://jp.misumi-ec.com/vona2/detail/110302677010/ 
よろしければ2つ発注していただけると助かります。

**Comment by yasuohayashibara** [comment]
発注しました．

**Comment by buzzshima** [comment]
走行できたので終了
