### ISSUE TITLE
地図の作成

### ISSUE THREAD

**Issue by Hiroki-Goto** [open-rdc/orne_navigation#362]
- [x] 確認走行用
- [x] 公園に行くまでの地図
    - [x] 作成
    - [x] 合成
- [ ] 公園内の地図
    - [x] 固定経路用
    - [ ] すべての経路用

**Comment by Hiroki-Goto** [comment]
公園までの地図：7/１５まで
公園の地図：9/1

**Comment by daiki-shibahara** [comment]
公園までの地図合成完了しました.

**Comment by daiki-shibahara** [comment]
[kenkyugakuen_maybe_ok.zip](https://github.com/open-rdc/orne_navigation/files/2210956/kenkyugakuen_maybe_ok.zip)

**Comment by daiki-shibahara** [comment]
![screenshot from 2018-09-15 13-04-43](https://user-images.githubusercontent.com/28525055/45570326-31d1a800-b89d-11e8-8dfc-28fc5997a4ef.png)

**Comment by daiki-shibahara** [comment]
![screenshot from 2018-09-15 13-18-11](https://user-images.githubusercontent.com/28525055/45570674-77db3b80-b89e-11e8-9c83-1fe900a20bfb.png)

**Comment by daiki-shibahara** [comment]
公園内の地図合成は現状地図が足りないため，明日取得必要があります
市役所から公園内までの地図の合成はできました

**Comment by daiki-shibahara** [comment]
9/15に市役所から公園までの地図で自律移動させた所
https://youtu.be/jHe5Dy7pzJs　
途中から地図の合成が上手くいってなかった
そのため、新しく合成しなおした
9/15に足りない箇所の地図を取得していないため、公園内の地図の合成は完了していない
![shiyakusho_1](https://user-images.githubusercontent.com/28525055/45725154-5eb2f180-bbf4-11e8-966e-000ee1ad05ff.jpg)

**Comment by yasuohayashibara** [comment]
新しい発見があったので，共有します．
先日1/10でrosbagを再生すると地図の精度があがるというtipsを教えてもらったのですが，一例ですが効果絶大です．

大学の芝生周辺の地図を作成した様子です．
https://youtu.be/4iisqSt_rYo

rosbagを1/10で再生して作成した地図です．
https://youtu.be/jkyltQa8-xo

一例ですが素晴らしく精度が上がりました．

**Comment by yasuohayashibara** [comment]
どうしたら歪みの少ない地図が作成できるかを検討するために，以下のbagファイルで地図を作成した．
http://www.hayashibara-lab.it-chiba.ac.jp/member/bags/2018-05-26_Experiment_Tsukuba_orne-beta/

確認走行区間のデータ（２周走行？）
2018-05-26-10-59-15.bag

※以下，別のPCで作業をして現在そのデータが閲覧できないため，後で追記します．
１）bagファイルからrosbag filterを使用して，/map, /map_metadata, /tfの/mapフレームを削除
　　すでに生成した地図のデータが入っていたが，再生成するためにはじめに削除
```
rosbag filter 2018-05-26-10-53-17.bag converted.bag "topic != '/map' and topic !='/map_metadata'"
rosbag filter converted.bag converted2.bag 'topic != "/tf" or (topic == "/tf" and m.transforms[0].header.frame_id != "map")'
```

２）条件を変更しながら，gmappingで地図を生成
　　条件１　ジャイロオドメトリのみで作成
　　条件２　デフォルトのパラメータで作成
　　条件３　試行錯誤したパラメータで作成

```
roslaunch slam.launch
rosbag play --clock test2.bag
```

条件１　ジャイロオドメトリのみで作成
slam.launch
```
<launch>
    <param name="use_sim_time" value="true"/>
    <node pkg="gmapping" type="slam_gmapping" name="slam_gmapping" output="screen">
      <param name="lskip" value="1000000"/>
    </node>
</launch>

```
動画
https://youtu.be/HXimcyC5mLw

条件２　デフォルトのパラメータで作成
slam.launch
```
<launch>
    <param name="use_sim_time" value="true"/>
    <node pkg="gmapping" type="slam_gmapping" name="slam_gmapping" output="screen">
    </node>
</launch>
```
動画
https://youtu.be/zJW2WrYmXy8

条件３　試行錯誤したパラメータで作成
slam.launch
```
<launch>
    <param name="use_sim_time" value="true"/>
    <node pkg="gmapping" type="slam_gmapping" name="slam_gmapping" output="screen">
      <param name="lstep" value="0.05"/>
      <param name="astep" value="0.05"/>
      <param name="minimumScore" value="500.0"/>
      <param name="maxUrange" value="60.0"/>
      <param name="maxRange" value="60.0"/>
      <param name="srr" value="0.01"/>
      <param name="srt" value="0.01"/>
      <param name="str" value="0.01"/>
      <param name="stt" value="0.01"/>
    </node>
</launch>
```
動画（途中までだった．．．）
https://youtu.be/ldJ_Z1nOtpY

結果
１）ジャイロオドメトリのみでもある程度地図が作成できる．
ただし，１周すると20deg程度のズレが発生するので，そのままでは使用できない．
逆にアナデバのIMUであれば，もっとズレの少ない地図が生成できるかもしれない．

２）gmappingのデフォルト値では歪みの無い地図は生成できない．
屋内を想定しているので，レーザレンジで検出される物体が少なすぎる．

３）ジャイロオドメトリに重きをおいたgmappingでは改善するものもあるが，一致はしない．
ということで，切り貼りの作業が発生していると思われる．
ただし，地図の切り貼りはある程度の整合性は取れるかもしれないが，全体的な歪をなくすことにはならない．

あと．実はTOP-URGは60mまで距離が検出できることを発見した．
※データには60m近い距離のデータが含まれています．
https://www.hokuyo-aut.co.jp/search/single.php?serial=21

解決策
１）/tfの/odomフレームを衛星地図を参照しながら手動で修正できる機能を実装する．
２）ジャイロのズレによるものであるため，よりドリフトしないジャイロに変更する．
　　アナデバのジャイロに変更したが，すでに解決しているかもしれない．

アナデバのジャイロを使用した以下のデータに関しても同様の作業を行い，地図のズレを検証する．
http://www.hayashibara-lab.it-chiba.ac.jp/member/bags/2018-10-02/

**Comment by daiki-shibahara** [comment]
確認走行区間から信号機までの地図合成したものです
https://drive.google.com/file/d/1tZYNv8spjAQ1Rbtjy99bBbCRV0-OwBWU/view?usp=sharing

**Comment by yasuohayashibara** [comment]
以前から気になっていたIMUの精度が高ければ，ジャイロオドメトリだけで地図ができてしまうのではという疑問に関して調査しました．

結果は「できました．」

おそらくはレーザレンジセンサを用いたSLAMより幾何学的に正しい地図が描けているのではないかと考えます．
公園は十分な距離データが得られないことが原因と思いますが，gmappingで地図作成すると，かえって地図を歪ませてしまっていると思います．
（パラメータを調整すれば改善すると思いますが．．．）
なお，データが不足しているのかエラーによりgmappingが動きませんでした．

 以下地図生成のコマンド
（１行目は必ずしも必要ないが，とりあえずファイルサイズを小さくしたかったので．．．）

あと，rvizはrosbag playの前に立ち上げて下さい．hokuyo_linkのtfが最初に１回しか投げられないため，/scanがエラーとなります．（少々ハマりました．．．）

```
rosbag filter 2018-08-04-13-35-47.bag converted.bag "topic != '/velodyne_packets' and topic !='/velodyne_points'"
rviz
rosbag play converted.bag
```

![image](https://user-images.githubusercontent.com/5755200/46731418-8eba5580-ccc5-11e8-9bb2-0a834052fabe.png)
黄色がSLAMを使用せずにジャイロオドメトリだけで作成した地図

元の画像ファイル
https://photos.app.goo.gl/ECQYbi5KBjB2Ect49

木や建物，道の形を見る限りほぼ完全に一致していると思います．
テーブルに見える丸い造形物だけずれていますが，もしかして移動した？
gmappingで地図を作成しているわけではありませんので，動的障害物（安全管理責任者など）も写り込んでいます．

上記はアナデバのIMUを使用して作成した地図で，参考までにインベンセンスのIMU6050で作成した確認走行区間の地図を示します．
![image](https://user-images.githubusercontent.com/5755200/46732882-ad225000-ccc9-11e8-8dfc-2174587a4d68.png)

**Comment by yasuohayashibara** [comment]
訂正しました。

以下のファイルに関してジャイロオドメトリを使用した地図を作成しました。
2018-10-02-14-24-20.bag （最近計測したbagfile）
http://www.hayashibara-lab.it-chiba.ac.jp/member/bags/2018-10-02/

```
rviz
rosbag play 2018-10-02-14-24-20.bag
```

作成して気づいたのは、

原因は特定できませんが、レーザレンジセンサの点が横にずれていきます。
動画に見られるように、前に進めば進むほどレーザの点が横にずれていきます。
IMUセンサのドリフトは作成された地図を見る限りありませんので、何か横方向にずれるような要因があるのだと思います。

以下のどちらかの可能性が高いと思います。

１）レーザレンジセンサとロボットの正面がずれている
２）ロボットが斜め方向に進んでいると計算されている

１）のおそれが高いと思いますが、調査をお願いします。

動画
https://youtu.be/zgRSvJx3ReA

作成した地図
![image](https://user-images.githubusercontent.com/5755200/46772411-dd520900-cd32-11e8-95bc-793258eb26f9.png)

**Comment by yasuohayashibara** [comment]
続報
やはりvelodyneの取り付け角度の問題でした。
0.12rad(7deg)程度ずれています。
以下のコマンドにより、強制的に/velodyneフレームを動かして作成される地図を確認しました。

```
static_transform_publisher 0 0 0.0377 -0.12 0 0 /velodyne_base_link /velodyne
```
※rosbag再生後に実行してください。

動画
https://youtu.be/os3v4__x0z0

作成された地図
![screenshot 2018-10-11 10 15 44](https://user-images.githubusercontent.com/5755200/46774833-5a837b00-cd3f-11e8-9eb6-a6d09f48b8e6.png)

少々ドリフトしていますが，まあ許容範囲ではあります．
![image](https://user-images.githubusercontent.com/5755200/46775206-34f77100-cd41-11e8-90dc-6dc301d19eaa.png)
※少し暖機運転してから開始すると改善することもあります．

**Comment by ToshihiroNagao** [comment]
https://github.com/open-rdc/orne_navigation/issues/373#issuecomment-428826151
https://github.com/open-rdc/orne_navigation/issues/373#issuecomment-432906367
のコメントの通り地図の作成を行いました。

**Comment by buzzshima** [comment]
作成済んだ
