### ISSUE TITLE
stop waypoint を試す

### ISSUE THREAD

**Issue by Hiroki-Goto** [open-rdc/orne_navigation#363]

**Comment by buzzshima** [comment]
stop waypoint からorne_strategy側に移行されてた。
そちらを確認

**Comment by atsushi10mino** [comment]
orne_strategyのsuspendディレクトリ内のyamlファイルに止まりたい座標を入力すれば止まることを確認した
複数は確認していないが,suspend_pose,resume_poseをそれぞれ指定すればできる？

問題：・止まったあとにナビゲーションを再開,ゴールにたどり着いた際のfinish_poseの向きが反映されていない
　　  （・resume_poseがいまいちよくわからない）

動画：https://youtu.be/tAFvAwkpOyE

**Comment by buzzshima** [comment]
試せたので終了
