### ISSUE TITLE
人物探索

### ISSUE THREAD

**Issue by Hiroki-Goto** [open-rdc/orne_navigation#364]

**Comment by buzzshima** [comment]
@ibukichi  進捗はどうですか？

**Comment by ibukichi** [comment]
北陽3DLIDARが使えるかどうか試したところ接続が失敗したためかpointcloudで指定してもエラーが出て点群が表示されないです。 
![screenshot from 2018-09-17 15-02-55](https://user-images.githubusercontent.com/29033482/45608063-7c187c00-ba8b-11e8-9f86-2a909c0f6a1c.png)

**Comment by ibukichi** [comment]
![screenshot from 2018-09-19 11-57-47](https://user-images.githubusercontent.com/12184572/45728621-b147da00-bc03-11e8-9ff6-1217716120f5.png)
![screenshot from 2018-09-19 11-58-40](https://user-images.githubusercontent.com/12184572/45728624-b3119d80-bc03-11e8-85b4-8e814a38ceee.png)
![abe_hokuyo3d](https://user-images.githubusercontent.com/12184572/45728630-b6a52480-bc03-11e8-9728-6843c44c2544.png)


orne_bringupとhokuyo3dを立ち上げてもう一度実験したところ。
接続はできて、値も出てきている。
しかし、rvizに表示されない。
エラーを見てみるとtfの変換ができてないと出ていますが、tf＿treeを見た限り繋がっているのでtf内での変換がうまく言ってないorその他のところに飛ばしている可能性があることがわかりました。
センサ自体は最初赤点滅はするが、時間が経つと赤点滅は消える。つまり、センサは壊れてないかもしれないです。

**Comment by ibukichi** [comment]
orne_bringupにあるhokuyo3d.launchをいじった結果、3次元点群が表示できました。どうやらvalueで指定したlink先がhokuyo3d_linkではなく、hokuyo_linkになっていたためでした。お騒がせして申し訳ございません。
![screenshot from 2018-09-19 12-08-13](https://user-images.githubusercontent.com/12184572/45728937-32ec3780-bc05-11e8-8ec0-f63d294f727d.png)

**Comment by ToshihiroNagao** [comment]
10月 4日に人物探索の実験を行いました。下のリンクが実験動画です。
https://youtu.be/f7cLNp4Ccbg

**Comment by ibukichi** [comment]
探索対象者へアプローチ動作の確認ができたため閉じる
