### ISSUE TITLE
三次元位置推定をやってみる

### ISSUE THREAD

**Issue by Hiroki-Goto** [open-rdc/orne_navigation#365]
navigation パッケージに3d_navigaitonのブランチがあったので集中開発期間に試してみる

**Comment by Hiroki-Goto** [comment]
候補１　[hdl localization](https://github.com/koide3/hdl_localization):カルマンフィルタを用いた位置推定（スキャンマッチングはNDT）
候補２　[Autoware](https://github.com/CPFL/Autoware/)：自動運転に関するパッケージ（[日本語のチュートリアルっぽいもの](https://github.com/CPFL/Autoware/)）

**Comment by daiki-shibahara** [comment]
候補2のAutowareについてhttp://4c281b16296b2ab02a4e0b2e3f75446d.cdnext.stream.ne.jp/randc/mirai/3_Autoware_LP.pdf

**Comment by ToshihiroNagao** [comment]
3次元の自己位置推定を実機での確認(Autowareで)

**Comment by Hiroki-Goto** [comment]
厳しいなら[3次元のMCL](https://github.com/at-wat/mcl_3dl)もありかもしれない

**Comment by ToshihiroNagao** [comment]
期間を設定しました。(9/30まで)

**Comment by JinyaIseki** [comment]
#405　に引き継ぎ
