### ISSUE TITLE
地図のノイズ削除

### ISSUE THREAD

**Issue by Hiroki-Goto** [open-rdc/orne_navigation#367]
地図に計測のノイズが残っていると、経路計画に支障が出る。
なので、地図のノイズを消す

**Comment by yasuohayashibara** [comment]
問題が分かりにくいので，写真などを貼ってくれると助かります．

**Comment by atsushi10mino** [comment]
![rviz_screenshot_2018_08_07-17_23_28](https://user-images.githubusercontent.com/28559070/43764968-c5fba69a-9a69-11e8-80dc-c6f0307002c9.png)
左右ともに何もない場所にコストが乗っています
原因として地図にノイズ(黒い点)があり障害物があると認識されています

右図はそのせいで経路が右に逸れて、芝生に入りそうになっていました
なので動画等をみながら障害物があるのかノイズなのかを判断しノイズ除去する必要があると思われます

**Comment by buzzshima** [comment]
地図の編集関連でいうと経路計画用も必要
もしかしたら駐車場に侵入してしまう

**Comment by Hiroki-Goto** [comment]
地図を削除する区間
- [x] 市役所〜公園

- [ ] 公園内

**Comment by daiki-shibahara** [comment]
#362 で地図合成を行う際に並行して市役所~公園までのノイズ削除を行った。
公園内のノイズ削除はまだ行っていない
