### ISSUE TITLE
βの電装をきれいにする

### ISSUE THREAD

**Issue by buzzshima** [open-rdc/orne_navigation#368]
βの電装をきれいにする　(USB周りも)

**Comment by atsushi10mino** [comment]
βの電装置き場の大きさ300mm×140mm×100mm
現在のタッパーの大きさ200mm×140mm×50mmくらい
注:電装置き場の下には台がないためタッパーの縁で固定している

**Comment by daiki-shibahara** [comment]
電装の置き場（箱）のCAD 図を作成して貰いましたので青木研の人に頼むか外注の方お願いします。https://cit-outdoor-mr.slack.com/files/U5B71ASM6/FCWP77Y3F/image.png
寸法は下記リンクを参照してください
https://cit-outdoor-mr.slack.com/archives/C7D3QL4AW/p1537355685000100

**Comment by nakamuratomoya** [comment]
@daiki-shibahara 分かりました。ご協力ありがとうございます。

**Comment by yasuohayashibara** [comment]
電気回路を入れるケースは市販していますので，それを利用したほうが良いと思います．
あと，ケースに穴が空いていますが，防水は大丈夫？

http://www.takachi-el.co.jp/?gclid=CjwKCAjwio3dBRAqEiwAHWsNVQ09iG8iOpR7ObhnSD4HeP-8HDb7K0g16SMrVTr9gW589Ix7roKEfRoCwNAQAvD_BwE

密閉すると放熱が問題になるかもしれませんが，サーマルインターフェイスシートなどを使用してケースを介して放熱すると良いと思います．
（タッパーで囲っていて大丈夫であれば，放熱は必要ないかもしれませんが．．．）

**Comment by daiki-shibahara** [comment]
今のケースではケーブルを通す穴が小さく追加のケーブルを入れることが不可能なため少し大きくあけました．防水に関しては上から蓋をかぶせる形で考えています．そのため，穴が開いた部分への防水対策は考えていません．

電気回路を入れるケースが販売されているのであればそちらが良いですが，ケーブルを通す穴が必要となるため，そこの防水対策を考える必要がありますね．

**Comment by yasuohayashibara** [comment]
防水に関しては，検索すれば様々な製品があります．

αのように防水のコネクタを付けても良いですし，以下のような製品でケーブルを覆えば防水できます．

https://jp.misumi-ec.com/vona2/detail/222005037595/?KWSearch=%E9%98%B2%E6%B0%B4&searchFlow=results2products

**Comment by daiki-shibahara** [comment]
![img_20181001_200057](https://user-images.githubusercontent.com/28525055/46783365-f1166300-cd64-11e8-8ad5-59716898665e.jpg)
![img_20181001_195551](https://user-images.githubusercontent.com/28525055/46783366-f1166300-cd64-11e8-9a8c-cab7fadf4c73.jpg)

**Comment by yasuohayashibara** [comment]
あまり大きいのはおすすめしませんが，以下のようなものもあります．

https://www.monotaro.com/p/0738/8403/?utm_medium=cpc&utm_source=Adwords&gclid=CjwKCAjwjIHeBRAnEiwAhYT2h8o4gsZSnF2pAuDnNjnoGu3KIrwifvf8o7M1DMfw6tmIQhp6qwY_jRoCOHIQAvD_BwE

**Comment by daiki-shibahara** [comment]
安全停止スイッチの取り付けと電装の入れ物を作成してもらう

**Comment by taishiyamamoto** [comment]
安全停止スイッチを取り付けました

![img_1494](https://user-images.githubusercontent.com/25315656/47151668-5b0aab80-d315-11e8-8c0e-0861321ba13d.JPG)

**Comment by yasuohayashibara** [comment]
お疲れ様です．
最後に尖ったところにカバーを付けるようにしてください．

**Comment by nakamuratomoya** [comment]
報告が遅くなり、また、タスクに取り組むのが遅すぎましてご迷惑をおかけしまして大変申し訳ございません。深くお詫び申し上げます。
以下に（参考までに）タッパーなどのurlを貼らせて頂きます。（現状の報告（選定中）です.

https://www.monotaro.com/g/00496088/

https://www.monotaro.com/g/00496087/

https://www.monotaro.com/k/store/%83%5E%83b%83p%81%5B%20%97e%8A%ED%20%83T%83C%83Y/

**Comment by buzzshima** [comment]
緊急停止スイッチ動作確認

https://drive.google.com/file/d/1UueFDIr00iaI16z0HByn6oAf0fR9cxRC/view?usp=sharing

**Comment by nakamuratomoya** [comment]
タッパーについて（候補１）

https://www.monotaro.com/p/8869/5196/

https://www.monotaro.com/p/3959/3127/

https://www.monotaro.com/p/3959/3163/

https://www.monotaro.com/p/0287/9177/?t.q=%83%5E%83b%83p%81%5B%20%97e%8A%ED%20%83T%83C%83Y

*amazonは現在調査中・・・

**Comment by nakamuratomoya** [comment]
タッパー購入しました。
すみません。本日、購入したものと領収書を自宅に忘れたので、月曜日に検収及び取り付け行います。

**Comment by nakamuratomoya** [comment]
![image1](https://user-images.githubusercontent.com/29033619/47861204-9ccb4400-de35-11e8-8237-2e6ceb2229e0.png)

↑寸法:130mm＊150mm＊60mmぐらい・・・

**Comment by nakamuratomoya** [comment]
検収は通したが、体調不良のため取り付けと加工が終わってませんので、本走行終了後に行うつもりです。大変申し訳ございません。
領収書は後で渡します。

**Comment by taishiyamamoto** [comment]
@yasuohayashibara 
回路ボックスですが以下の型番の発注をお願いします。
寸法は250x150x75.4mmです。

FC8-25-15GS

**Comment by taishiyamamoto** [comment]
@yasuohayashibara 
回路ボックスですが以下の型番の発注をお願いします。
寸法は300x200x50.4mmです。

型番
FC5-30-20GS

URL
https://jp.misumi-ec.com/vona2/detail/222000228525/?HissuCode=FC5-30-20GS&PNSearch=FC5-30-20GS&KWSearch=FC5-30-20GS&searchFlow=results2products

**Comment by yasuohayashibara** [comment]
反応が遅れて申し訳ありません．
発注しましたが，受注生産らしく納期が未定です．


ミスミからの回答
申し訳ございません。出荷日調整の結果、3/20出荷が最短となりますが、ご了承いただけますでしょうか。

@taishiyamamoto 
３月末は予算が使用できないおそれが高いので，４月以降でも構いませんでしょうか．
もしくは別のものに変えますか？

キャンセルしました．どこかのタイミングで再度依頼してください．

**Comment by taishiyamamoto** [comment]
簡易的にですが回路ボックスの設計をしました。
@yasuohayashibara 
よろしければ以下の型番の発注をお願いします。

FC10-25-20GS　　　　回路ボックス　　　　　　 1個
SBD-J3-10　　　　　   ジュラコンスペーサ　　     30個
EA949AJ-235　　　　  M3ネジ　　　　　　　　　2パック
EA949SD-21　　　　   M3ナット　　　　　　　　2パック


![回路ボックス組立図](https://user-images.githubusercontent.com/25315656/55056631-f9135680-50a9-11e9-8eac-b52ebb0960fb.png)

![回路](https://user-images.githubusercontent.com/25315656/55056648-04ff1880-50aa-11e9-8060-21a9b5fe3338.jpg)

**Comment by yasuohayashibara** [comment]
4/1に発注します．
その前に，おおまかで良いので，放熱は大丈夫かを確認してもらえればと思います．
熱くなる部品は，ファンを使用して空冷したり，ケースを使って放熱するなどしてあげた方が良いことがあります．

**Comment by taishiyamamoto** [comment]
箱の穴あけ終わりました。
4番の基板以外はネジで固定できることを確認しました。
@daiki-shibahara 
新しい4番に該当する基板が固定できるかどうか確認したいです。あと、放熱に関して意見をもらいたいです。
![IMG_0337](https://user-images.githubusercontent.com/25315656/55726547-084fb800-5a4b-11e9-8bcd-09f09f878f39.JPG)

**Comment by atsushi10mino** [comment]
使用したときの温度を確認

**Comment by taishiyamamoto** [comment]
回路をボックスに移し替えました。
![m_curcuitbox](https://user-images.githubusercontent.com/25315656/58006645-7d6edc80-7b23-11e9-9513-b8764058d605.png)


icartとimuと前方後方URGの動作確認はできました。
3DLiDARは以下を参考にしましたが接続できない状態です。
https://github.com/open-rdc/orne_navigation/wiki/YVT-X002%E3%81%AE%E9%81%8B%E7%94%A8

![image](https://user-images.githubusercontent.com/25315656/58005385-84482000-7b20-11e9-982c-b30fc5df5d69.png)

**Comment by atsushi10mino** [comment]
3dURGの接続の確認
