### ISSUE TITLE
resume suspendの位置を複数位置に対応

### ISSUE THREAD

**Issue by buzzshima** [open-rdc/orne_navigation#370]
つくばチャレンジで複数停車箇所あるため対応する

**Comment by ibukichi** [comment]
fulanghua_navigationのfulanghua_waypoints_navのwaypoints_nav.cppを以下のように編集しました。
・すでに置かれているwaypointを指定してsusupend_waypointに
・suspend_waypointに移動する間の30秒間と確実に到着したと仮定した30秒間、あわせて60秒の間次のwaypointに移動しない　
なお、編集する前のwaypoints_nav.cppはwaypoints_nav_before.cppとして保存しております。
youtubeにシミュレータで動作させた動画をupしました。
URL:https://youtu.be/qd5_IyiiJxs

**Comment by buzzshima** [comment]
まず内容以前にgitでバージョン管理しているのでwaypoints_nav_before.cppとか無駄なファイルを作らずにブランチを切って開発してください
あとで見直すときにややこしくなるので、、、

話はそこからかな…

gitの使い方がわからないなら相談なり検索してください。

**Comment by ibukichi** [comment]
現在のブランチを切って開発を行っています。
停止するwaypointの近くまで走行してから停止するようにして、1のキーを入力した時のみ次のwaypointに行くようにしました。
ですが、この入力する所をサービスとして送ることをどうすれば実現できるかwikiを見てもさっぱり分かりません。

**Comment by ToshihiroNagao** [comment]
動作実験を行いました。行った動画をYoutubeに限定公開しました。リンクを載せておきます。
https://youtu.be/en9A5sa69ac

**Comment by buzzshima** [comment]
新しく実装しマージ した
