### ISSUE TITLE
アナデバのIMUの動作確認

### ISSUE THREAD

**Issue by Hiroki-Goto** [open-rdc/orne_navigation#371]
アナデバさんから提供されたIMUの挙動調査だがwindows版では動いた

しかし、PCとIMUをつなぐ基板EVAL-adis2Zがlinuxに対応していないため、SPI-USBのものを別途購入する必要がある
使っていた基板はおそらく[これ](https://www.elefine.jp/SHOP/USB-ISS-SV.html)

**Comment by yasuohayashibara** [comment]
Windows版って何？
具体的にソフトウェア名を記載して下さい．
また，後から見た人の参考になるように，できるだけ型番を示したほうが良いです．

**Comment by yasuohayashibara** [comment]
以下のROSパッケージを用いて姿勢を検出する．
https://github.com/tork-a/adi_driver

Ubuntuで値を読み取るために以下を購入します．
Devantech USB-ISS-SV USB I2C・SPI・UART変換器

**Comment by yasuohayashibara** [comment]
以下を１つ購入しました．
Devantech USB-ISS-SV USB I2C・SPI・UART変換器

動作確認の後，追加で２つ購入します．

**Comment by Hiroki-Goto** [comment]
Devantech USB-ISS-SV USB I2C・SPI・UART変換器を使って動作確認を行いました

[アナデバさんのROSパッケージ](https://github.com/tork-a/adi_driver)で動作確認を行ったときのbagファイル
https://drive.google.com/open?id=1E5T_3gMpYTju9SjLjxeQOK3_5_LNheAA

**Comment by yasuohayashibara** [comment]
動作の様子です．
https://youtu.be/uHPApUICayw

ADIS16470用に開発されたROSノードですので，そのままでは利用できないということかもしれません．
現在使用しているIMUはADIS16465-2となります．

**Comment by yasuohayashibara** [comment]
ADIS16470の動作の様子です．
http://wiki.ros.org/adi_driver

以下，ADIS16460シリーズに関する議論もされていました．
https://github.com/tork-a/adi_driver/issues/10

**Comment by Hiroki-Goto** [comment]
柿沼さんのアドバイスを参考に、感度の調整を行ったあとの動作結果
https://drive.google.com/open?id=1WNCXVoIzDQDtgK4_5P6YYLnBIDge9_Zi

**Comment by yasuohayashibara** [comment]
同じ動画をYoutubeにもアップロードしました．
https://youtu.be/3h07mi7UVEQ

あとは実機で試したいと思います．

**Comment by daiki-shibahara** [comment]
αに取り付けられるか確認する

**Comment by Hiroki-Goto** [comment]
取り付け版を作成しαに取り付けた
#372 にて動作確認を行う
![dsc_0888](https://user-images.githubusercontent.com/12184572/45414792-1efd7e80-b6b7-11e8-8691-286f3da7a928.JPG)

**Comment by Hiroki-Goto** [comment]
WIKIを追加し終わったら閉じる

**Comment by Hiroki-Goto** [comment]
β側は 赤松くんがやる
・URDF(orne_beta.xacro)
・bring up 
・Udev rule
・adi_driverのソースを変更

**Comment by Hiroki-Goto** [comment]
wikiを追加した
ただ、[adi_driver](http://wiki.ros.org/adi_driver)の中身を書き換える必要があるのでforkする必要があるかも・・・

**Comment by Hiroki-Goto** [comment]
open-rdcにforkしました
