### ISSUE TITLE
提供されたIMUを使用し自律移動

### ISSUE THREAD

**Issue by buzzshima** [open-rdc/orne_navigation#372]
動作確認が終了したので，実機に取り付けて既存ものとの比較．(amclの回転のパラメータとekfののパラメータの変更したほうがより推定が頑健になる可能性がある)

**Comment by yasuohayashibara** [comment]
実験の様子の動画です．
2号館3Fを3周して開始と同じ方向にロボットを向けて終了しました．
https://youtu.be/vmSNoaiCAwo

@Hiroki-Goto IMUのデータをお願いします．

**Comment by Hiroki-Goto** [comment]
https://drive.google.com/open?id=1n8wfvDi5QmOg83N_mRy2xyuPhJBsXD0i　
にIMUのデータ（クオタニオンとrpyの２種類）をアップしました

**Comment by yasuohayashibara** [comment]
グラフ化しました．
![image](https://user-images.githubusercontent.com/5755200/45538198-5304ab00-b841-11e8-935d-1141eff25284.png)

時間的には4分半ですが，かなり信頼性の高い値が計測できていると思います．

**Comment by JinyaIseki** [comment]
共分散行列を一万分の一でもいいかも

**Comment by yasuohayashibara** [comment]
美濃君と行っていた研究において，gmappingで用いた値ですが，以下のような小さい値が良い地図が描けました．

```
      <param name="srr" value="0.000001"/>
      <param name="srt" value="0.000002"/>
      <param name="str" value="0.000001"/>
      <param name="stt" value="0.000002"/>
```

https://github.com/open-rdc/create-map-with-landmark/issues/6

**Comment by Hiroki-Goto** [comment]
統合している箇所 combine drの共分散行列を０変更

**Comment by buzzshima** [comment]
自律走行して問題がなかったため終了
