### ISSUE TITLE
早急に行うタスク

### ISSUE THREAD

**Issue by Hiroki-Goto** [open-rdc/orne_navigation#376]
- [x] チェックシート
- [x] 持ち物リスト
- [ ] 購入品の確認
- [x] やることリスト

**Comment by Hiroki-Goto** [comment]
チェックシート作成完了
置き場所 https://drive.google.com/open?id=1taetjefbDHvtQvALUUBnaJY8bge_5d6g

**Comment by Hiroki-Goto** [comment]
持ち物リストを更新しました

**Comment by daiki-shibahara** [comment]
αの安全装置が断線していたため取付し直した
動作確認済みです
![imag0090](https://user-images.githubusercontent.com/28525055/46246419-040d6700-c438-11e8-98b1-e9ca3734c96d.jpg)


250型の圧着端子(平型)が無くなった為，発注お願いします
ミスミの方確認したら丸形しかなく　https://jp.misumi-ec.com/vona2/result/?Keyword=250+%E5%9C%A7%E7%9D%80%E7%AB%AF%E5%AD%90&isReSearch=1

今まで使っていたのは平型です　https://www.customjapan.net/shop/g/g13214234/

平型のオスメスか丸形のオスメスどちらが良いでしょうか？

**Comment by yasuohayashibara** [comment]
ミスミでもあります．
https://jp.misumi-ec.com/vona2/result/?seriesPage=1&Keyword=%E5%B9%B3%E5%9E%8B%E7%AB%AF%E5%AD%90

あと，過去に平型端子を調達したことがこちらのissueに残っていますが，そのときは夏迫君が買いに行ったと思われます．林原の発注履歴にはありません．

**Comment by daiki-shibahara** [comment]
amazonで見つけました
オスメスの6セット発注お願いします
https://www.amazon.co.jp/%E3%82%A8%E3%83%BC%E3%83%A2%E3%83%B3-%E5%B9%B3%E5%9E%8B%E7%AB%AF%E5%AD%90%E3%82%BB%E3%83%83%E3%83%88-250%E5%9E%8B-30%E3%82%BB%E3%83%83%E3%83%88-1156/dp/B001VNW3JQ?th=1

**Comment by yasuohayashibara** [comment]
購入しました．

> amazonで見つけました
> オスメスの6セット発注お願いします

**Comment by yasuohayashibara** [comment]
@daiki-shibahara 
検収して，芝原君の机の上に置きました．

> 購入しました．
> 
> > amazonで見つけました
> > オスメスの6セット発注お願いします
