### ISSUE TITLE
揺動URGの設計製作

### ISSUE THREAD

**Issue by ShotaroTerato** [open-rdc/orne_navigation#38]
URGを揺動させるための機構を設計製作する必要がある

**Comment by Nasupl** [comment]
アクチュエータですが、制御部分の簡略化のため、無限回転のサーボを使いたいですね。
DynamixelならROSのパッケージもありますし、以下のサーボ等どうでしょうか。
http://www.besttechnology.co.jp/modules/knowledge/?BTX032%20Dynamixel%20AX-18A

**Comment by ShotaroTerato** [comment]
良いと思います。とりあえず、このサーボを基に設計しようかと思います。

**Comment by DaikiMaekawa** [comment]
@Nasupl 使用する場合は早めに発注依頼をお願いします。

**Comment by Nasupl** [comment]
@yasuohayashibara 
http://www.besttechnology.co.jp/modules/onlineshop/index.php?fct=photo&p=130 x 2
http://www.besttechnology.co.jp/modules/onlineshop/index.php?fct=photo&p=151 x 1
以上2点、発注お願いします。

**Comment by yasuohayashibara** [comment]
揺動機構にはモータが付いていたような気がしますが，そちらは利用できませんでしょうか？また，サーボモータを購入する場合は，まずは図面を見たいです．作りなおしを最小限にしたいと思います．
あと，1秒間に1.5回転しかしませんが，それで大丈夫でしょうか．fuRoは1秒間で4回転ぐらいしていたような気がします．
動画を見つけました．
https://www.youtube.com/watch?v=BVgqQRt7_0o

**Comment by ShotaroTerato** [comment]
（株）移動ロボット研究所で製品化されている「測域センサ揺動装置：Gim30°」の回転速度(ジンバル機構揺動速度)が1rpsということでそちらを参考にしました。
図面はこのようになっています。
![btx032-dim](https://cloud.githubusercontent.com/assets/7301081/4593305/c162af58-5084-11e4-894c-389a91246a58.png)
http://www.besttechnology.co.jp/modules/knowledge/gate.php?way=ref&_nodos&_noumb&page=BTX032%20Dynamixel%20AX-18A&src=BTX032-dim.png

**Comment by yasuohayashibara** [comment]
図面は組み立てた時の図です．また，取り付けてあるモータは使えませんでしょうか．

**Comment by Nasupl** [comment]
@yasuohayashibara 
取り付けてあるモータはmaxonのEC-maxとなっていて、ドライバ回路の開発やROS側の開発に時間がかかりそうです。当該サーボを選定したのは、すでにROS用にパッケージが存在していて、新たな回路の開発の必要がないという理由もあります。

**Comment by yasuohayashibara** [comment]
モータドライバとしては，EPOSが使用できます．研究室には予備も含めて何台かあったと思います．USBで制御できます．また新たなモータを使う場合は，回路は開発しなくても良いですが，メカニズムが必要となります．

**Comment by ShotaroTerato** [comment]
細部はまだですが、Dynamixel版のおおまかな設計が終わりましたので、facebookの方にInventor内で回転させている様子をアップしました。

maxon EC-max版はこれを基に設計しようかと思います。

![urg](https://cloud.githubusercontent.com/assets/7301081/4602525/6c99d53a-513f-11e4-88d5-03b396aa4691.png)

**Comment by Nasupl** [comment]
URGのサイズが異なるので、メカニズムはどちらにしても必要になります。
EC-maxを使用する場合、EPOS側のコネクタ形状が異なるので、その入手が必要となりそうです。

**Comment by yasuohayashibara** [comment]
知能ロボに使用しているモータを使用して構いません．また，AX-12に関しては，もしかしたら角度を検出できない角度があるかもしれません．あとポテンショは摺動しますので，すぐに寿命が来てしまいそうな気がします．

**Comment by Nasupl** [comment]
@taki4416 余っているEPOSの場所をご存知でないでしょうか。また、UbuntuをEPOSで利用する際の注意点等ご存知でしたらお教えください。（Ubuntu14.04でEPOSが認識されてない）

**Comment by ghost** [comment]
@Nasupl 余ってる扱いなのかわかんないけど、3回のマシンにたくさんついてる。認識されないのはmodprobeあたりっぽいけど、あやふやなんで持ってきてくれたら見るよ

**Comment by ShotaroTerato** [comment]
a-max22版の回転機構設計ができました。
facebookの方に回転様子の動画をアップしました。
![urg2](https://cloud.githubusercontent.com/assets/7301081/4628325/af999098-5395-11e4-9a5e-74c064a2137e.png)

**Comment by yasuohayashibara** [comment]
EPOSですが，余っているものはありませんでしたでしょうか．つくばチャレンジ向けのロボットはモータとモータドライバの予備を用意して行っていたような記憶がありますので，探せば出てくると思います．

**Comment by Nasupl** [comment]
@yasuohayashibara 
EPOSについてですが、@taki4416 先輩から余っている（？）分を受け取りました

**Comment by ShotaroTerato** [comment]
知能ロボコンに使用しているDC-max22には減速比4.4:1のギアヘッドがついており、十分なトルクを得るには、さらなる減速をしなければならないが、EC-max22 についているギアヘッドの減速比が157:1あり、最低でもボールジョイントの部分で69.93N出るので、このURG(350g)を振るのには十分なトルクが得られると考えられるため、EC-max22を使用しようかと思います。

**Comment by ShotaroTerato** [comment]
ミスミのフレームに取り付けられるようにしました
![yodo_urg_frame](https://cloud.githubusercontent.com/assets/7301081/4787282/8f3e9aec-5da8-11e4-84b8-06d65526d408.png)

**Comment by ShotaroTerato** [comment]
ミスミの30°の角度付きアルミフレームを用いるものに変更しました
![urg3](https://cloud.githubusercontent.com/assets/7301081/4855498/6c5ae53e-60a6-11e4-9214-e16ee724df8d.png)

**Comment by ShotaroTerato** [comment]
ジンバル機構部の製作が完了
![img_1264](https://cloud.githubusercontent.com/assets/7301081/4870973/7ebe9376-6194-11e4-8e59-033a1de23563.JPG)

**Comment by ShotaroTerato** [comment]
@yasuohayashibara 現在動作を試みているEPOSですが、CAN通信をしてPC側のポートが開いているのは確認できるのですがEPOS側が何の反応もなく、それ以上うまくいっていない状況です
EPOSの不具合の可能性もあり他のEPOSでも試してみたかったのですが、探しても見当たりません．もしご存知でしたら何処にあるか教えていただけないでしょうか

**Comment by yasuohayashibara** [comment]
EPOSですが，新習志野１１号館にあります．

**Comment by ShotaroTerato** [comment]
他のEPOSでも試してみましたが、同じ症状が出るのでEPOSの不具合ではなかったようです
また動作しない原因としてEPOS側のCAN-IDの設定かとも考え設定を様々変えて動作を試みましたが、変更後も何の変化も見られず、よくわからない状況です

**Comment by DaikiMaekawa** [comment]
@ShotaroTerato 完成したようなのでこのタスクは完了ですか？
