### ISSUE TITLE
TOP-URG用の電源基板の選定

### ISSUE THREAD

**Issue by Hiroki-Goto** [open-rdc/orne_navigation#381]

**Comment by Norihiro02** [comment]
メモ:
入力24[Ⅴ]
出力12[V]

**Comment by Norihiro02** [comment]
とりあえず候補
+ 村田：表面実装ＤＣ－ＤＣコンバーター（５Ｖ／１２Ｖ切替・２Ａ出力）ＭＰＤ６Ｍ００７Ｓ
    + http://akizukidenshi.com/catalog/g/gM-06515/
+ DROK：dcdc　降圧モジュール　DROK DC 24V / 12V / 5V　降圧降圧電源　モジュール　8-35V〜1.5-24V　可変コンバータ
    + http://u0u1.net/MFQX

**Comment by yasuohayashibara** [comment]
村田製作所で手頃そうと考えましたが，外付け部品が必要なので少々大変です．
選定したらメンションつけてコメントしてください．

> 村田：表面実装ＤＣ－ＤＣコンバーター（５Ｖ／１２Ｖ切替・２Ａ出力）ＭＰＤ６Ｍ００７Ｓ
> * http://akizukidenshi.com/catalog/g/gM-06515/

**Comment by Norihiro02** [comment]
以下のモジュールを購入していただきました。
ありがとうございました。
https://www.marutsu.co.jp/pc/i/826652/

**Comment by yasuohayashibara** [comment]
到着しました．
林原が持っていますので，できれば取りに来てください．

**Comment by Norihiro02** [comment]
やる事リスト

- [x] モジュールの組み立て

- [x] 通電・絶縁テスト

- [x] 電源に接続し、動作確認（2時間位連続稼働させてみる。）

**Comment by Norihiro02** [comment]
電源モジュールのテスト終わりました。
24Vを入力した時に12Vが出力されることを確認しました。
![ios 1](https://user-images.githubusercontent.com/38202582/47548357-c7983280-d933-11e8-9ccc-3b8ac251cc52.jpg)
↑動作確認風景

![default](https://user-images.githubusercontent.com/38202582/47548511-4beab580-d934-11e8-86c1-bcb9cac9dcd5.jpg)
↑配線図

**Comment by Hiroki-Goto** [comment]
URGのコネクタの取り付け

**Comment by Norihiro02** [comment]
実際にURGに接続し、動作確認しました。

**Comment by ToshihiroNagao** [comment]
防水をする
