### ISSUE TITLE
α外装の改良

### ISSUE THREAD

**Issue by linevael** [open-rdc/orne_navigation#382]

**Comment by linevael** [comment]
α外装（FRP）の穴あけを本日行います．

**Comment by yasuohayashibara** [comment]
新しく製作して，新たに加工はしないとなったような．．．

**Comment by MasayaOkada** [comment]
ORNE-αの外装で２枚発注していただきました。
http://amzn.asia/d/dJitKDe

**Comment by tiger0421** [comment]
![orne 1](https://user-images.githubusercontent.com/20837922/47915399-1fabd780-dee6-11e8-9e2c-19c4c673761f.jpg)
![orne 2](https://user-images.githubusercontent.com/20837922/47915408-2b979980-dee6-11e8-9211-6dff7f3577b8.jpg)
![orne 3](https://user-images.githubusercontent.com/20837922/47915410-2b979980-dee6-11e8-99dc-5b45864090fb.jpg)
![orne 4](https://user-images.githubusercontent.com/20837922/47915412-2c303000-dee6-11e8-8c12-68ec4d111f08.jpg)
![orne 5](https://user-images.githubusercontent.com/20837922/47915417-2c303000-dee6-11e8-84f6-ae536d98d367.jpg)
![orne 6](https://user-images.githubusercontent.com/20837922/47915419-2cc8c680-dee6-11e8-82a9-287b18b2e166.jpg)


orne-αの外装はこんな感じになりました

**Comment by MasayaOkada** [comment]
PCの下のアルミの箇所が危ないと指摘されたので横の部分をリアラボードで隠します

前回の走行で破れている部分があったため、今回は間に合いませんが、次回からは素材を変えたほうがいいと思います

**Comment by ToshihiroNagao** [comment]
作成終了次第、コメントをして閉じる

**Comment by MasayaOkada** [comment]
作成終了したため、closeします。
