### ISSUE TITLE
#381 (電源モジュール)のドキュメントの作成

### ISSUE THREAD

**Issue by Norihiro02** [open-rdc/orne_navigation#392]

**Comment by Norihiro02** [comment]
↓URG用電源モジュールのドキュメント作成中...(未完成)
https://drive.google.com/file/d/159S7ZcFutwprg4liXVtEtiUzWxqfNg4p/view?usp=sharing

**Comment by taishiyamamoto** [comment]
ドキュメントを更新しましたのでcloseします．
https://github.com/open-rdc/orne_navigation/wiki/ORNE%E8%A8%AD%E8%A8%88%E4%BB%95%E6%A7%98%E3%81%AA%E3%81%A9
