### ISSUE TITLE
velodyneを用いたMCLのリセットパラメータの調整

### ISSUE THREAD

**Issue by buzzshima** [open-rdc/orne_navigation#394]
頻繁にリセットが起きるので調整する

**Comment by ToshihiroNagao** [comment]
引継ぎを行いましたので、担当者を変更します。

**Comment by atsushi10mino** [comment]
撮影した動画とパラメータをのせる

**Comment by hoshianaaa** [comment]
0.001 [https://www.youtube.com/watch?v=darooOaQ5Fw](url)
0.002 [https://www.youtube.com/watch?v=hMn1pB1Q1XQ](url)
0.003 [https://www.youtube.com/watch?v=MfNCDsPO-FY](url)
0.004 [https://www.youtube.com/watch?v=i77ORQtg8Bc](url)
0.005 [https://www.youtube.com/watch?v=gSK6XqKA4yM](url)
0.006 [https://www.youtube.com/watch?v=dwg9xNh6DVk](url)
0.007 [https://www.youtube.com/watch?v=OLoNjVU0EKg](url)
0.008 [https://www.youtube.com/watch?v=LCWAtFZfc_g](url)

**Comment by hoshianaaa** [comment]
0.001 https://www.youtube.com/watch?v=darooOaQ5Fw&t=71s

**Comment by hoshianaaa** [comment]
0.001 https://www.youtube.com/watch?v=darooOaQ5Fw&t=71s
0.002 https://www.youtube.com/watch?v=hMn1pB1Q1XQ
0.003 https://www.youtube.com/watch?v=MfNCDsPO-FY&t=13s
0.004 https://www.youtube.com/watch?v=i77ORQtg8Bc

**Comment by hoshianaaa** [comment]
0.005 https://www.youtube.com/watch?v=gSK6XqKA4yM
0.006 https://www.youtube.com/watch?v=dwg9xNh6DVk
0.007 https://www.youtube.com/watch?v=OLoNjVU0EKg
0.008 https://www.youtube.com/watch?v=LCWAtFZfc_g

**Comment by JinyaIseki** [comment]
誘拐問題を発生させ、実験を行う

**Comment by hoshianaaa** [comment]
[https://www.youtube.com/watch?v=C5AsjfL-WFc](url)

**Comment by hoshianaaa** [comment]
https://www.youtube.com/watch?v=C5AsjfL-WFc

**Comment by hoshianaaa** [comment]
アドバイスを受け、つくばの環境に近い図書館前で調整を行った。
0.002,0.003はパーティクルが発散
0.001でパーティクルが発散しなくなった。

**Comment by hoshianaaa** [comment]
動画

0.001:https://www.youtube.com/watch?v=vlxj5OSpE0w (0:47 ~ 1:17 )
0.002:https://www.youtube.com/watch?v=89fqQfcVjRU (0:26 ~ 0:50 )
0.003:https://www.youtube.com/watch?v=Kx7OCuJGWJc (0:40 ~ 1:15)

＊カッコ内の時間は、パーティクルの発散の様子が見られる時間です。

**Comment by hoshianaaa** [comment]
他にリセットの起こりそうな場所で試した
場所は駐輪場前の芝生
この場所では、0.001でも発散した。
0.0009では、発散しなくなった。

0.001：https://www.youtube.com/watch?v=XymxQThBK5o (0:36 ~ 1:08 )
0.0009：https://www.youtube.com/watch?v=8rhYYHUEnR0 (0:24 ~ 0:50)

**Comment by daiki-shibahara** [comment]
茜浜公園や新習志野校舎で試してみる

**Comment by Akito-Shirai** [comment]
とりあえず0.001で実行し、それから変えていく。
