### ISSUE TITLE
α外装の要求仕様の検討

### ISSUE THREAD

**Issue by Takuyakataoka** [open-rdc/orne_navigation#395]
αの外装を作るにあたり、必要な機能や希望などを検討する。

現時点で把握している最低限の機能
・PC画面用のクリア素材の窓設置
・防水
・メンテナンス性

そのほかに何か希望等ありましたらこちらでお願いします。

**Comment by yasuohayashibara** [comment]
上記の３つで構わないかと思いますが，これを満たす設計にするにはかなり大変です．
土砂降りの中でも中が濡れないようにするためには，選択できる方法は限られてしまいます．
ちなみに本体は60cm以上無いといけなかったと思いますので，現状の形状を保とうとすると必ず飛び出す部分ができてしまいます．

**Comment by Takuyakataoka** [comment]
暫定的に3DCADで構想したものを作成しました

正面
![image](https://user-images.githubusercontent.com/43669105/55131365-b1500600-5161-11e9-8ed7-6eb6c7cb258e.png)
裏
![image](https://user-images.githubusercontent.com/43669105/55131385-c5940300-5161-11e9-9c36-b33efa675654.png)

天板が一回り大きくなっていて傘の役割を果たす
![image](https://user-images.githubusercontent.com/43669105/55131495-2f141180-5162-11e9-8e83-a452a50f6f72.png)

クリア樹脂板のはまり
隙間はシリコンコーキングでふさぐ
![image](https://user-images.githubusercontent.com/43669105/55131777-55867c80-5163-11e9-82df-f460af9e67cd.png)


ミーティング後の改良点
・丸みを帯びた設計にする
・タイヤが被るところまで外装を伸ばす
・シリコンからワイパーのようなゴムに付け替えられるのでは

**Comment by yasuohayashibara** [comment]
まだイメージしにくいところがありますが，
以下，指摘です．

１）雨が降ったときには，風により横からも，跳ね返りにより下からも水がきます．
　　かなり下まで覆わないと，濡れるおそれがあります．
２）安全チェックで巻き込みを指摘されないか確認してください．
３）自転車と同じで車輪からの水もある程度飛び散ります．
４）サイズを大きくしたと書かれていましたが，大きくすると，その分衝突のリスクが高まります．
５）重量が重いと坂を移動できなくなることがあります．
　　ちなみに，iCart-miniのときははじめにアクリルでカバーを作りましたが，重くて坂が登れなくなりました．
６）角があると，スポンジを貼ることになります．スポンジの配置を考えないと，分解することが非常にめんどくさくなります．
７）Velodyneを搭載することを前提の設計にしたほうが良いと思います．

**Comment by Takuyakataoka** [comment]
外装v2の概要図を作成

全面（黄色）と背面（白色）の2つからなる構造

＞＞黄色
・全面にPC操作のための穴（透明塩ビ板設置）
・黒いものはゴム板で外装の内側一周に設置

![image](https://user-images.githubusercontent.com/43669105/56560305-00f9e400-65df-11e9-81b9-6e7f4f70a7c8.png)

＞＞白色
・velodyne,URG,非常停止スイッチ用の穴
・ゴム板を外装の外側一周に設置

![image](https://user-images.githubusercontent.com/43669105/56560395-47e7d980-65df-11e9-9f7b-a0bada9ea4c6.png)

＜防水について＞
外装の接続部のゴム板は互い違いに設置されており水の侵入を防ぐ
図面には載っていないが接合面にゴムパッキンを付けて防水性の向上を図る

![image](https://user-images.githubusercontent.com/43669105/56560784-597db100-65e0-11e9-873e-db6570b96a60.png)


＞＞アセンブリイメージ
![image](https://user-images.githubusercontent.com/43669105/56560457-72399700-65df-11e9-83ba-4a7b5be5906b.png)

**Comment by Takuyakataoka** [comment]
今後の検討内容
・velodyne.URG,非常停止スイッチの防水はどうするのか
（現段階の解：テーピングてカバー）
・前後の外装の接合部分に蝶番を付けて開閉式にしたらどうか
　（検討中）

必須のタスク
・USBアクセスのために黄色いほうの前方を変更
・PCスペースに余裕を持たせる
　（そもそもUSBハブの固定を行えばいい可能性もあり）
・取手を移動したときの持ちはこびやすさの検討

**Comment by Takuyakataoka** [comment]
FRPで何か小さいものを作ってみる

**Comment by Takuyakataoka** [comment]
FRPでこちらを作成する
α外装を作成する際に必要な加工点を設けてある
![image](https://user-images.githubusercontent.com/43669105/57568022-7a396980-741c-11e9-893b-453976eb8389.png)

サイズ 20×20×20 mm

**Comment by Takuyakataoka** [comment]
[FRP 発注表.xlsx](https://github.com/open-rdc/orne_navigation/files/3168881/FRP.xlsx)

模型作成のため発注お願いします

**Comment by yasuohayashibara** [comment]
キットではなく，個別に購入する場合，前回の残りがあると思いますので，無いものだけ購入したいと思います．
3号館3Fと新習志野にあります．新習志野のものは次回行った時に持ってくるようにします．

**Comment by Akito-Shirai** [comment]
現在の状況はどうでしょうか？
更新されていないようですが、今から製作して間に合いそうですか？

**Comment by Takuyakataoka** [comment]
αのPCが決まったのでハードウェアの見直しを行う．

　https://www.dospara.co.jp/5shopping/detail_prime.php?tg=13&tc=143&ft=&mc=8944&sn=2861&st=1&vr=10&tb=1#tabContents
　（↑ PCの仕様や端子の位置詳細）



＞PC変更に従い，考慮すべき点
　・従来のPCのように逆折り畳みが出来ない．
　・PC操作のために外部ディスプレイを設置する必要がある．
　・外装製作が控えているため，短期間で改良できるように．
　・配線時の端子の位置
　　
以下に設計したハードを示す（急いで作ったため雑です）
全体図
![image](https://user-images.githubusercontent.com/43669105/66415945-ba3a6200-ea37-11e9-9fd8-bb1f461c51f8.png)
側面図
![image](https://user-images.githubusercontent.com/43669105/66415967-c1fa0680-ea37-11e9-8846-01ac9666af92.png)
正面図
![image](https://user-images.githubusercontent.com/43669105/66415989-cde5c880-ea37-11e9-8023-5038d1ba7d53.png)
マガジンラック着想 PCディスプレイ置き
![image](https://user-images.githubusercontent.com/43669105/66416470-d7236500-ea38-11e9-8431-87f3a14c62e1.png)



＞構造の説明
　・マガジンラックの容量で上からカセットのように畳んだPCを挿入し
　　外部ディスプレイに接続することで操作を行う．
　・ディスプレイ固定方法：両面テープ
　・PC固定方法：両面テープ？
　（※URG，Velodyne，非常停止スイッチの位置は書いてないが従来の位置から変更なし）
　・回路の位置は要相談



　＞＞長所
　　　・パーツ製作は３Dプリンタとバンドソー・ボール盤のみで加工可能．
　　　・外装の設計を変えなくてよい．
　　　・購入するPCの端子の位置に適しており配線を整理しやすい．
　＞＞短所
　　　・バッテリーの取り入れがしずらくなる．
　＞＞外部ディスプレイの選定
　　　・新たなバッテリーを置くスペースがないのでバッテリー内蔵 or PC給電
　　　・PCと同じく15.6型？（13.3型も可）（https://www.amazon.co.jp/dp/B07SK67BZR/ref=cm_sw_em_r_mt_dp_U_NqfNDbK21BQ9Z とか？）

**Comment by Takuyakataoka** [comment]
外装の製作を考えると時間がないのでこちらで問題なければ回路の設置位置だけ議論を行い本日中に発注表を提出します．
議論がある場合や，疑問点がある場合も10/9までにお願いします．

**Comment by Takuyakataoka** [comment]
外装アセンブリイメージ
![image](https://user-images.githubusercontent.com/43669105/66424873-68023c80-ea49-11e9-8f1d-f1d7197b37a1.png)
![image](https://user-images.githubusercontent.com/43669105/66424884-6b95c380-ea49-11e9-8c1c-3705da92064f.png)

**Comment by yasuohayashibara** [comment]
片岡君には昨日直接話しましたが，時間の関係もあり変更は最小限にしたほうが良いと思います．ディスプレイを搭載して配置を変える案となっていますが，無線ルータにつないでVNCでアクセスすることが現実的な解のような気がします．リモートでモニタリングした方がおそらく状況も把握しやすいと思います．

実績のある無線ルータとしては，WRH-583BK2-Sがあります．
複数接続できますので，実験走行中に各自が手元のディスプレイで挙動を確認できます．

なお，リモートで<b>操作する</b>ことは禁止ですが，<b>見るだけ</b>なら問題ありません．また，有線で繋げばスタートなども手元のコンピュータを使用して操作することができます．

あと，iPadでもVNCは使用できますので，どうしても本体にディスプレイが必要な場合は，iPadを外部に貼り付けるという方法もあります．

あと，排熱が心配な場合はファンを付けたほうが良いと思います．
雨を避けながら排熱するためには，わりと面倒な形になりますが．．．
