### ISSUE TITLE
2019年度の方針

### ISSUE THREAD

**Issue by atsushi10mino** [open-rdc/orne_navigation#397]
・３D LIDAR (芝とコンクリート区別) 保科
・3次元自己位置推定 => 美濃
・PFoE 岡田M
・βの人物探索(発見方法: 3D LIDAR 山本or YOLO 近藤
・βの反射的な回避動作 => 芝原
・γの学習 => 井関
・パーティクルの広がりに応じて経路計画の変更（コーナー）
チェックポイント通過＋封鎖経路回避

**Comment by daiki-shibahara** [comment]
実験走行会を経て決めた機体ごとの方針
・人物探索 ZEDを使いYOLOで学習させる
αの方針
・3次元自己位置推定(Autoware)
・反射的な回避動作
・パーティクルの広がりに応じて経路計画の変更（コーナー）
・3次元地図の生成(Cartgraoher)
・手動トリガーの実装
・列に並ぶ動作の実装

βの方針
・芝とコンクリートを区別する2次元地図を生成することにより，地図上に結界を貼る作業を軽減させる=>保科
・人物探索(3DLIDAR)：今の実装でマネキンの識別が出来るか試してから決める
・反射的な動作回避
・パーティクルの広がりに応じて経路計画の変更（コーナー）
・チェックポイント通過＋封鎖経路回避
・2次元地図の生成(gmappingかCartgraoher)
・手動トリガーの実装
・列に並ぶ動作の実装

方針から外れた開発
・PFoE

**Comment by daiki-shibahara** [comment]
今年から外れた開発
・信号認識
・GNSSリセット

**Comment by taishiyamamoto** [comment]
つくばチャレンジ2019が終了したのでcloseします。
