### ISSUE TITLE
シリアルサーボをROSで制御する方法の検討

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#4]
今のところ例年通りURGを振ることを想定しているためシリアルサーボを制御するためのノードを流用、もしくは新規開発を行う必要がある。

**Comment by DaikiMaekawa** [comment]
@Nasupl 使用するサーボはRS405でいいですか？
とりあえず任意の角度にサーボを制御するサンプルプログラムを作成してください。

**Comment by DaikiMaekawa** [comment]
@taki4416 そういえばサーボでURGを振って上側のデータのみを使うプログラムは昨年度で完成していたんでしたっけ？

**Comment by ghost** [comment]
@DaikiMaekawa サーボが同じなら多分あるよ．じゃぁ今度渡そう

**Comment by DaikiMaekawa** [comment]
@taki4416　動いていたものがあるのなら流用した方が早いのでありがたくいただきます。

**Comment by DaikiMaekawa** [comment]
@Nasupl 受け取ったプログラムの動作確認を来週までに済ませてください。

**Comment by DaikiMaekawa** [comment]
ビルドのエラーメッセージを張り付けてください @Nasupl

**Comment by DaikiMaekawa** [comment]
ビルドが通ったためこれから動作チェックに入ります。

**Comment by Nasupl** [comment]
@taki4416 先輩が使用していたプログラムをうまく組み替えれば動作しそうですが、まだうまく動いていません。

**Comment by Nasupl** [comment]
@taki4416 先輩が使用していたプログラムを組み替えて、URGを振りながらPointCloudを生成することに成功しました。
また、futabaのサーボをROSから使用するためのリポジトリを開きました。
https://github.com/open-rdc/futaba_servo

**Comment by DaikiMaekawa** [comment]
仮実装を完了して、動作を確認したため閉じます。
