### ISSUE TITLE
ベータの挙動がおかしい

### ISSUE THREAD

**Issue by JinyaIseki** [open-rdc/orne_navigation#401]

**Comment by JinyaIseki** [comment]
git diff　で変更を調べる

**Comment by taishiyamamoto** [comment]
βで使っていたPCをαに移してlaunchを起動させたところ、問題なく動作したのでハードウェアの問題であると考えられる。
尚、車体を浮かしてタイヤを無負荷回転させた場合、問題なく動作した。
また、相違点としてicart-middleのモータードライバに実装されているLEDのランプが設置している時のみ点滅することがわかった。

モータードライバのドキュメントを参照してLED点滅の意味と原因を特定する。

**Comment by taishiyamamoto** [comment]
ドキュメントのリンクと参照先を添付しておく
http://t-frog.com/products/motor_driver/files/TF-2MD3-R6_Manual_rev5.pdf

![Screenshot from 2019-05-28 18-56-50](https://user-images.githubusercontent.com/25315656/58469498-95290f00-817a-11e9-8431-7f634157548a.png)

**Comment by taishiyamamoto** [comment]
LEDの点滅の周期（非常に見づらいですが）
https://drive.google.com/open?id=1f4d4OYOb7Mo3FwuIq5NvUg306orKi0_k

おそらく駆動電圧低下のエラーだと考えられる。

**Comment by taishiyamamoto** [comment]
駆動電圧24Vのところに１２Vの電圧を印加していたことが原因でした。
挙動が元に戻ったのでcloseします。
