### ISSUE TITLE
βの電装の防水と固定

### ISSUE THREAD

**Issue by JinyaIseki** [open-rdc/orne_navigation#402]

**Comment by taishiyamamoto** [comment]
大まかな高層ですがシート型チューブで配線をまとめて、ケーブルグランドを使って後ろに蓋をして防水対策は回路ボックスを大きい箱に入れて二重防壁にしようかなと考えております。

シート型チューブ
https://jp.misumi-ec.com/vona2/el_wire/E1407000000/E1407010000/
ケーブルグランド
https://jp.misumi-ec.com/vona2/detail/222005037584/?KWSearch=%E3%82%BF%E3%82%AB%E3%83%81&searchFlow=results2products

**Comment by taishiyamamoto** [comment]
議論の過程で底面に穴を開けたほうが良いという結論に至った。
底面に穴を開ける場合に現在の構造で穴を開けられるかどうか検討する。

**Comment by daiki-shibahara** [comment]
充電回路を実装するに辺り，#342 で購入されたプラグとレセプタクルが必要な為，購入おねがいします．
D/MS3106A12S-3Sを２つ
D/MS3100A12S-3Pを２つ

**Comment by yasuohayashibara** [comment]
購入する前に，まずは何をするのか明確にしてください．
コネクタの追加をするということはメカニズムの修正も意味しますので，どちらにコネクタを追加するかを明確にして，議論を得てから追加したほうが良いと思います．

ちなみに，３端子のコネクタを４つ使用するというのは計１２端子となりますが，どのように接続するかがイメージできません．

**Comment by taishiyamamoto** [comment]
#416 
と一緒に防水の件を優先して取り組む

**Comment by taishiyamamoto** [comment]
本走行が近づいてきたらグルーガン等で済を埋めて対処を行う
