### ISSUE TITLE
orne_aの環境構築ができない

### ISSUE THREAD

**Issue by hoshianaaa** [open-rdc/orne_navigation#406]
wiki通りに環境構築を行ったが

ros_launch orne_bringup orne_alpha.launch実行時
Error: Cannot find parameter fileというエラーが出る

![Screenshot from 2019-06-27 00-38-38](https://user-images.githubusercontent.com/40942409/60194281-f9231e00-9873-11e9-8fa4-dac178f48773.png)

ls /dev/sensors/で"icart-mini"は出ている

![Screenshot from 2019-06-27 00-47-33](https://user-images.githubusercontent.com/40942409/60195101-7c913f00-9875-11e9-9f1a-d4f48949b115.png)

**Comment by daiki-shibahara** [comment]
https://github.com/open-rdc/orne_navigation/wiki/ORNE%E7%92%B0%E5%A2%83%E5%8B%95%E4%BD%9C%E3%81%AE%E6%89%8B%E9%A0%86
を見て動作できるか確認する

**Comment by hoshianaaa** [comment]
上の手順で動いた
