### ISSUE TITLE
αとβの軸が歪んでいるため治す

### ISSUE THREAD

**Issue by daiki-shibahara** [open-rdc/orne_navigation#409]
α，β共にハの字に歪んでいる

**Comment by yasuohayashibara** [comment]
写真を撮って載せたほうが良いと思います．

**Comment by atsushi10mino** [comment]
正面
![写真 2019-07-09 15 28 50](https://user-images.githubusercontent.com/28559070/60864613-07534000-a25f-11e9-8051-7a310490a312.jpg)

右車輪
![写真 2019-07-09 15 25 43](https://user-images.githubusercontent.com/28559070/60864633-176b1f80-a25f-11e9-91a5-46d84ebd0b95.jpg)

左車輪
![写真 2019-07-09 15 36 17](https://user-images.githubusercontent.com/28559070/60864766-792b8980-a25f-11e9-990b-2c7ac1031edd.jpg)

**Comment by JinyaIseki** [comment]
αの車輪の傾き
![IMG_20190711_193141](https://user-images.githubusercontent.com/28559030/61045088-1a0f7580-a415-11e9-9b97-149fd27746ed.jpg)

![IMG_20190711_193209](https://user-images.githubusercontent.com/28559030/61045106-2267b080-a415-11e9-8521-454969a87c53.jpg)


参考
α直進時の左ずれ
条件
２ｍの直進
場所
![IMG_20190711_184803](https://user-images.githubusercontent.com/28559030/61044853-8342b900-a414-11e9-9abd-6723d5f99b7b.jpg)

初期位置
![IMG_20190711_184810](https://user-images.githubusercontent.com/28559030/61044860-8b025d80-a414-11e9-8f5b-ad9830075b2f.jpg)

初期従動輪方向
![IMG_20190711_191014](https://user-images.githubusercontent.com/28559030/61044877-92c20200-a414-11e9-928c-588ed60ebaab.jpg)


結果
一回目
x:2.042
y:0.062
z:0.000

![run_2m-1](https://user-images.githubusercontent.com/28559030/61044628-0283bd00-a414-11e9-8239-d43d3c32048e.png)

![00100lPORTRAIT_00100_BURST20190711185035008_COVER](https://user-images.githubusercontent.com/28559030/61044929-aec5a380-a414-11e9-90f4-9459e4d1fe8e.jpg)

二回目
x:1.916
y:0.050
z:0.000

![run_2m-2](https://user-images.githubusercontent.com/28559030/61044647-0a436180-a414-11e9-914f-cd78a2c619f7.png)

![IMG_20190711_191431](https://user-images.githubusercontent.com/28559030/61044967-cc930880-a414-11e9-9cc7-b2c60ce564f1.jpg)

**Comment by daiki-shibahara** [comment]
検証し、問題がなかったため閉じる
