### ISSUE TITLE
IMUが稀に不正なデータを送信していることがある

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#41]
#40 にて発生したNavigationが途中で停止する問題はIMUが周期的に不正なデータを送信しているためだとログから判明した。

**Comment by DaikiMaekawa** [comment]
Navigationが停止している付近のバグデータを解析していたところ、IMUから周期的に不正なデータが出力されており、そのデータを受け取った結果、一時的に大きなオドメトリ誤差が発生していることがわかった。
seq: 10459はロボットのヨー軸方向の姿勢推定に大きく誤差が発生している時のIMUのデータであるが、ロボットが直進しているにも関わらず、その前後とは全く異なる姿勢が出力されていた。
![screenshot from 2014-10-12 10 00 02](https://cloud.githubusercontent.com/assets/3862239/4604721/f1f6eb18-51b3-11e4-9b24-220e56c47657.png)

**Comment by DaikiMaekawa** [comment]
現在使用しているIMUのROSドライバはIMUからの信号をシリアルで読み取り、その結果をトピックとして配信しているだけなので、この不正なデータの原因はPIC側のソフトウェアにある可能性が高いと考える。
間違った姿勢データを使用して計算したセンサーの位置がマップ外に飛んでしまったためにNavigationのcostmapにエラーが発生し、システムに大きな障害をもたらしていた。

**Comment by DaikiMaekawa** [comment]
我々が作成したIMUのインタフェース基板は十分な信頼性を保証するものではないと判断します。
@taki4416 サイズは大きいそうですがアナデバ純正のインタフェース基板が研究室にあると聞きました。
管理している場所をご存知ですか？

**Comment by ghost** [comment]
@DaikiMaekawa ごめん今見ました．その大きな基板を見たことがない（もしかしてアナデバの違う種類のIMUかも?）ので，ちょっとわからないです．
確認してるだろうけど，暖機運転してなくて温度ドリフトかかってるとかソフト直した際に初期化部が変わってしまったかも見たほうがいいかも

**Comment by DaikiMaekawa** [comment]
@taki4416 その両方とも確認済みです。 また、i-Cart miniに限らずMegaRover側でも類似の問題が発生しているとの報告を @yasuohayashibara から受けました。

**Comment by Nasupl** [comment]
@yasuohayashibara 
ADISの評価ボードですが、下記リンクのものでしょうか
http://www.analog.com/jp/evaluation/eval-adis/eb.html

**Comment by yasuohayashibara** [comment]
評価ボードEVAL-ADISですね．少なくとも羽根田君は使用していました．
評価ボードは複数枚入手していたと思います．初期のものはドライバに問題があり，あまりきちんと動作しなかった記憶があります．

**Comment by ItoYusuke** [comment]
データを基にプログラムを検証します．

2014年10月12日 16:21 Yasuo Hayashibara notifications@github.com:

> 評価ボードEVAL-ADISですね．少なくとも羽根田君は使用していました．
> 評価ボードは複数枚入手していたと思います．初期のものはドライバに問題があり，あまりきちんと動作しなかった記憶があります．
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/open-rdc/icart_mini_ros_pkgs/issues/41#issuecomment-58776055
> .

## 

---

千葉工業大学
工学部 未来ロボティクス学科
1126016 伊藤 裕介
Tell ：080-8852-6003
MailAddress ： itoyusuke.mobilemail@gmail.com

**Comment by Nasupl** [comment]
@yasuohayashibara 
EVAL-ADISですが、ドライバを開発すればLinuxから使用できるようですが、ADIのスタンスとして、現在のところEVAL-ADISのLinuxサポートをするつもりはないようで、Linux用のドライバ等は公開されていない模様です。

**Comment by yasuohayashibara** [comment]
同様のセンサを使用している千葉大の大川先生に問い合わせしました．

**Comment by yasuohayashibara** [comment]
回答が来ました．
独自の回路で対処しているようです．

---

千葉工業大学
林原 靖男 先生

　千葉大学の大川です．
いつもお世話になっております．

今日は，つくばチャレンジの第5回実験走行に参加していたため，
返事が遅れてしまいました．すみません．

さて，ジャイロに関して，メールを拝受しました．自宅からなの
で詳しい資料がないのですが，取り急ぎ，分かる範囲でお答えい
たします．

私が使用しているジャイロは， Analo gDevices の ADIS16136
です．このジャイロに，秋月電子の AKI-H8/3664F(QFP)につない
でSPI通信をしています．

H8を選んだ理由ですが，角速度を時間積分するには，時間精度が
高いほうが良いと考え，水晶発振子が付いた手近なマイコンを探
したら，このH8でした．

H8マイコンではタイマー割り込みを使い，定期的にSPI通信でジ
ャイロから角速度を得て時間積分し，角度情報しています．時間
積分は，計算処理のことを考え，台形積分はせず，あえて単純な
長方形積分しています．

また，ただ積分するだけだと，ドリフト誤差によって少しずつず
れてくるので，この誤差の影響を調べて，積分するときに微調整
（例えば，積分10回中n回はmを足して，残りはm+1を足す）をし
ています．これらの微調整の値は，ノートPCから指定可能です．

タイマー割り込みの時間についてですが，あまり速すぎると積分
誤差がたまり，あまり遅すぎるとロボットの速い回転に対応でき
ないと考え，何回か試して経験的に決めました．具体的な時間は，
ノートが大学にあるので，今は覚えていません．

ノートPCからは，必要な時に（不定期で）RS232C経由でH8マイコ
ンにアクセスし，現在の角度情報を得ています．ただし，角度情
報を radian や degree にしてから通信すると小数点の有効桁を
多くしないといけないので，積分した値（整数値）をそのまま送
ってもらい，ノートPCの方で radian に直しています．

あまり参考にならないかもしれませんが，他に知りたいことがご
ざいましたら，遠慮なくご質問ください．これらの回路やプログ
ラム作成は，すべて私が作っているのでご質問いただければ答え
られるかと思います．

取り急ぎ，ご返事まで．

---

千葉工業大学
林原 靖男 先生

おはようございます，千葉大学の大川です．

残念ながら，製品は知らないです．
お役に立てず，すみません．

以前は，積分や回路に（今よりも）自信が無かったので，
角度出力ができる光ファイバジャイロを購入しました．
学生が使っているロボット（今年のNo.1415-01）には，
そのジャイロが搭載されています．

> 時々エラーが発生していることに気づきました．

そういえば，私の所は，ノートPCとH8マイコンの通信が
追いつかず（？），1～2桁少ない角度が届いた時があり
ました．このため，私の所ではチェックサムを入れて，
チェックサムが正しくないときには等角速度運動してい
ると仮定して直線近似するようにプログラムしています．

幸い，角速度ではなく角度情報を通信しているので，し
ばらくの間しのげれば，いずれ正しい角度情報が届き，
その間の誤差は累積されていない（H8の積分は合ってい
る）ので，問題はありません．

他に，何か気づきましたら，メールいたします．
今後ともよろしくお願い申し上げます．

**Comment by Nasupl** [comment]
現状のブレークアウトボードが問題なのではないかということで、新規でブレークアウトボードを簡単に製作しています。
@ItoYusuke ADISのピンヘッダに対応したピンソケット（CLM-112-02かな？）をお持ちでしたらいただけると助かります。

**Comment by ItoYusuke** [comment]
在庫があれば本日中に津田沼にもって行きます

2014年10月15日 19:29 Kazuya N notifications@github.com:

> IMUのブレークアウトボードを簡単に製作しています。
> @ItoYusuke https://github.com/ItoYusuke
> ADISのピンヘッダに対応したピンソケット（CLM-112-02かな？）をお持ちでしたらいただけると助かります。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/open-rdc/icart_mini_ros_pkgs/issues/41#issuecomment-59186279
> .

## 

---

千葉工業大学
工学部 未来ロボティクス学科
1126016 伊藤 裕介
Tell ：080-8852-6003
MailAddress ： itoyusuke.mobilemail@gmail.com

**Comment by DaikiMaekawa** [comment]
@Nasupl が新規で作成しているインタフェース基板の進捗が芳しくないようなので、現状のまま使える方法がないかどうか検証を重ねた。
具体的には、IMUをハブを介さず接続してみたりUSB2.0ポートへの切り替えもテストした。
IMUとの通信周期も30Hz ~ 10Hzの間で試してみた。
発生頻度が少ないため検証には膨大な時間を要したがどれも改善には繋がらなかった。
今回収集したデータの中で貴重なサンプルを以下の画像に示す。

#### -0.06degから239deg

![screenshot from 2014-10-29 00 33 23](https://cloud.githubusercontent.com/assets/3862239/4814655/59447306-5ed1-11e4-8267-0f2b6868040c.png)

#### 89.9degから0.15deg

![screenshot from 2014-10-29 02 03 17](https://cloud.githubusercontent.com/assets/3862239/4814668/6aac77e2-5ed1-11e4-96e3-58c5d4119be2.png)

#### -147degから-2deg

![screenshot from 2014-10-29 00 42 13](https://cloud.githubusercontent.com/assets/3862239/4814671/7069bdc0-5ed1-11e4-9ca9-cebd2a646650.png)

これらのデータはIMUから受け取った文字列を単純にdegreeに変換したものである。
例外もあるので一概には言えないが0deg or 90deg or 180deg付近で値が一瞬だけ飛ぶことが多いように感じる。（しばらくすると正しい角度に戻る）
やはりPC側ではなくIMU側に何らかしらの問題が起きている可能性が高いのではないだろうか？
もしIMU側の問題であれば、多くの場合この現象が発生したとしても自律走行は継続可能なため、表面化していないだけでMegaRoverにも発生している可能性がある。

**Comment by DaikiMaekawa** [comment]
苦肉の策としてPC側で異常値を検出するためのフィルタを実装した。
これにより、問題が発生した際にも自律走行を継続できる確率は高まる。
しかし、データの欠損を改善に補償することは出来ないのでタイミングが悪いとコースアウトしてしまう危険性はゼロではない。

取り敢えず導入後にマップ作成のテストを2号館3Fで行った。
異常値を検出するまで動かしてみたが、フィルタでうまく処理することができた。
![screenshot from 2014-10-29 03 54 07](https://cloud.githubusercontent.com/assets/3862239/4815237/342f3da4-5ed5-11e4-9e7b-32876636d850.png)

**Comment by DaikiMaekawa** [comment]
後は時間との兼ね合いになってくると思いますが可能な限り現状のインタフェース基板の使用は控えたほうがいいと思います。
最小の労力で代替品を作るのであれば[FT221X](http://www.digikey.jp/product-detail/ja/UMFT221XA-01/768-1123-ND/3029135)というSPI to USB Serialモジュールを使用することをおすすめします。 @Nasupl 
IMUとこのモジュールは共に3.3V対応なので足のサイズを変更するだけでPCと接続が可能で大会に間に合う可能性も十分あります。

**Comment by Nasupl** [comment]
@DaikiMaekawa 
FT245RL（研究室に在庫あり）でも同様の機能があり、情報もまぁまぁあるのですが、こちらでもよろしいでしょうか（参考：http://d.hatena.ne.jp/beiz23/20131231/1388488925）
FT221Xは微妙に情報が少なくてやりづらそうです・・・。

**Comment by DaikiMaekawa** [comment]
そういう理由でしたらそちらを使用すれば良いと思います。（SPI to USBが実現できればモジュールの種類は問わない）
libftdiは使い勝手も良さそうなので、SPIをシミュレートする形で動作確認をお願いします。

**Comment by Nasupl** [comment]
@DaikiMaekawa
IMU基板が吐いている生の角速度のデータが飛んでいないか確認しようとのことでしたが、どうでしたでしょうか。ソースを再度読み直してみましたが、角速度は吐いていないように見えますよね？

**Comment by DaikiMaekawa** [comment]
@Nasupl そうですね。私もそう思います。
PIC側の積分をやめて生データをPCに送信するように修正する必要があります。

**Comment by DaikiMaekawa** [comment]
角速度データのみの送信でも不正なデータが発生するのかどうか検証をお願いします。

**Comment by Nasupl** [comment]
角速度含めた送信が可能なように、IMU基板のPICのプログラムを書き換えました。（リード線が生えてるIMU基板）
データが飛ぶかどうかの確認は検証はまだ出来ていません。

**Comment by Nasupl** [comment]
現在180度フィルタを外した状態で動かしていますが、180度を超えてしまった時に、積算がおかしくなり、0度位置がずれることがあります。

**Comment by Nasupl** [comment]
IMUからの角速度の読み出し、及び積算が  https://github.com/open-rdc/adis_imu_drivers/commit/3b8bfdc7724c956c08625a40324de57af11c2e5e にて問題なくできるようになりましたが、角度が飛んでいるときは角速度も同様に飛んでいるように見えます。
とりあえず気がつくことができたときの画像を添付しました。
![jump](https://cloud.githubusercontent.com/assets/7274407/4871958/d239d830-61d0-11e4-9566-28d653d001e2.png)
やはり、IMU基板が吐き出してくる角度情報をフィルタリングして使用するしかないのではないでしょうか・・・。

**Comment by Nasupl** [comment]
また、IMU基板が吐き出してくる角度情報は、１回飛んでもすぐ元の角度に戻りますが、ROS側で積分する場合、一回角速度が飛ぶと修正が難しそうです。

**Comment by DaikiMaekawa** [comment]
飛んだ時のデータだけrecvの長さが短いような

**Comment by Nasupl** [comment]
頭から2桁目と3桁目のデータが飛んでますね。演算の問題というよりは、データの送受信周りに問題がありそうですね。

**Comment by DaikiMaekawa** [comment]
@Nasupl データの送受信が問題なのかどうかはこれから検証してみます。
もし単純に桁落ちが問題ならば対処は簡単に出来ると思います。

因みにi-Cart miniに付いているIMUには最新のプログラムを書き込み済みですか？

**Comment by Nasupl** [comment]
@DaikiMaekawa 送られてくるデータを見ていただければいいと思いますが、書き換え済みです。

**Comment by DaikiMaekawa** [comment]
i-Cart miniに取り付けられているIMUで動作確認を行った。（ROS側のソースは以前の安定版）

符号の切り替わりが270度にシフトしているようですが、何か変更を加えましたか？
![screenshot from 2014-11-02 17 46 58](https://cloud.githubusercontent.com/assets/3862239/4874785/6d0be99e-6270-11e4-8c40-055d887941b3.png)
![screenshot from 2014-11-02 17 47 06](https://cloud.githubusercontent.com/assets/3862239/4874786/7540e77c-6270-11e4-8d55-c5f0113a21b2.png)
突発的に値が飛ぶわけではなく180度を越える角度が定常的に出力されています。

**Comment by DaikiMaekawa** [comment]
@Nasupl 
IMUから送られてくるデータに角速度情報を追加してからは、データの取りこぼしの頻度が上がっています。
IMUとの通信頻度を下げるとデータが安定することからデータ量の増加が原因と考えられる。
やりとりするデータを3軸の角度データのみに限定し、チェックサムを追加して下さい。

**Comment by Nasupl** [comment]
IMU基板のソフトウェアですが、Robocupの方から頂戴したものを書き込んだところ、温度ドリフト補償が書かれていない、出力される角度のスケールがおかしいなどの問題が発生しています。出力される角度のスケールの問題は、暫定的に解決しましたが、温度ドリフト補償の件に関しては、参考になるものが見つからず実装に苦戦しています。どなたか当該IMUの温度ドリフト補償についてご存知の方がいらっしゃいましたらご教示ください。

**Comment by DaikiMaekawa** [comment]
@open-rdc/tsukuba-challenge 
チェックサムを実装し、IMUのデータへのアクセス周期を落としたものはそこそこ安定しています。
角度が飛ぶ問題はシリアル通信によるデータ損失でほぼ間違いないでしょう。
しかし、つくばチャレンジのコース全域のマップ作成を行いましたが公園の箇所で大きくマップが歪んでいます。
これはソース書き換え後のIMUのドリフトが大きく（暖機運転後のIMUで10分で20度ほどズレる）、ランドマークが少ない領域では補正しきれないため発生する。
![screenshot from 2014-11-03 18 47 03](https://cloud.githubusercontent.com/assets/3862239/4880697/2aec0f56-633f-11e4-996d-856b5dfca679.png)

**Comment by DaikiMaekawa** [comment]
@Nasupl 元ソースが貰えるのならそれに越したことはありませんが、普通に移動平均フィルタを実装するだけで良いのでは？

**Comment by DaikiMaekawa** [comment]
この問題は解決したため閉じます。
IMUに発生している別の問題に関しては他のIssueを立てて議論しましょう。
