### ISSUE TITLE
横断歩道を横断する

### ISSUE THREAD

**Issue by JinyaIseki** [open-rdc/orne_navigation#411]
つくばチャレンジ2018での横断歩道を渡ったチームを参考にする
（土浦プロジェクト）
　横断歩道前の一時停止線で横断の可否を判断する
　minimize YOLOで信号認識
　
　迷クエ
　信号付近でモードを切り替え
　エッジを走行地ながら前方に障害物があると停止
　信号手前
　信号を認識し次のwaypointに向かう

**Comment by JinyaIseki** [comment]
信号付近に自己位置推定結果が出た後、
エッジを走行しながら前方に障害物を検知したら停止する

**Comment by hoshianaaa** [comment]
できました
https://youtu.be/mD2JtCXXhm8

**Comment by yasuohayashibara** [comment]
開発途中のものでも良いと思いますので，ソースコードも同時に公開すると良いと思います．

**Comment by hoshianaaa** [comment]
Pull requestしました

**Comment by Akito-Shirai** [comment]
https://github.com/open-rdc/orne_navigation/issues/408
