### ISSUE TITLE
orne-βのimuの故障

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne_navigation#414]
@taishiyamamoto より
orne-βのimuから値が帰ってこなかったので確認してみたらピンが抜けていた．

![iOS の画像](https://user-images.githubusercontent.com/5755200/61495946-94339180-a9f5-11e9-8672-7238fe36ef67.jpg)

**Comment by yasuohayashibara** [comment]
@taishiyamamoto より

以下のissueを参考にするとこれらの製品が必要になると思います。
https://github.com/open-rdc/orne_navigation/issues/371

ADIS16470/PCBZ
https://www.mouser.jp/ProductDetail/Analog-Devices/ADIS16470-PCBZ?qs=sGAEpiMZZMve4%2FbfQkoj%252BEMCJzhlHLpe%2FLS2P3%2FY4OM%3D

Devantech USB-ISS-SV USB I2C・SPI・UART変換器
https://github.com/open-rdc/orne_navigation/issues/371

**Comment by yasuohayashibara** [comment]
@taishiyamamoto 
故障したのはブレイクアウトボードだけですので，こちらだけ購入できればと思います．
インターネットで簡単には見つかりませんでしたので，メーカなどに問い合わせていただければと思います．

**Comment by taishiyamamoto** [comment]
アナログ・デバイセズ社のカスタマーサービスに問い合わせました。

**Comment by yasuohayashibara** [comment]
@taishiyamamoto 
issueを見直してみたら，現在のIMUは以下の型番と思います．

ADIS16465-2

**Comment by yasuohayashibara** [comment]
これでは？

https://www.analog.com/jp/design-center/evaluation-hardware-and-software/evaluation-boards-kits/eval-adis16imu4.html#eb-overview

**Comment by taishiyamamoto** [comment]
上記の製品で間違いないと思います。
対応してくださった方々に訂正とお詫びのメールを送りました。

@yasuohayashibara 
よろしければ以下のURLからブレイクアウトボードの発注をお願いします。
https://www.mouser.jp/ProductDetail/Analog-Devices/ADIS16IMU4-PCBZ?qs=%2Fha2pyFaduhs8a%2Fi9S9r%252BKgB0sZ7P4Wd3azSNlaAieaP8vurSxAPzg==&_ga=2.210611217.526459243.1563966910-134851088.1563966910

**Comment by yasuohayashibara** [comment]
発注しました．

**Comment by taishiyamamoto** [comment]
部品が届いたので、故障した部品と取り替えて動作確認を行いました。
パラメータ等の変更は行っておりません。

動作確認は以下のように行いました。
https://youtu.be/Lwn5iiUh9SY

正常に動作していると思われます。

**Comment by taishiyamamoto** [comment]
よろしければこのissueはcloseしてimuの配線処理を行いたいと考えております。
