### ISSUE TITLE
芝生の認識

### ISSUE THREAD

**Issue by hoshianaaa** [open-rdc/orne_navigation#417]
公園などでパーティクルが広がった時に、芝を認識できると安全である。

**Comment by hoshianaaa** [comment]
3D Lidar から反射強度により芝生を抽出し、local costmapに送ることができた

![Screenshot from 2019-08-13 12-51-02](https://user-images.githubusercontent.com/40942409/62914427-4aa74e00-bdcb-11e9-86b2-e233ecd73d9f.png)

**Comment by hoshianaaa** [comment]
odomフレームからobstacle_rangeというパラメータ内の距離しかコストマップに乗らない


![Screenshot from 2019-08-13 12-48-15](https://user-images.githubusercontent.com/40942409/62914842-061cb200-bdcd-11e9-8942-c681ae699f4c.png)


obstacle_range:5.0

**Comment by hoshianaaa** [comment]
https://www.youtube.com/watch?v=NRA4oS0Z9bc

**Comment by hoshianaaa** [comment]
https://www.youtube.com/watch?v=HXK5zPezZW4

**Comment by hoshianaaa** [comment]
・夕方に実験して、ノイズは見られなかった
・waypointに芝生認識する・しないの情報を追加した
動画:https://www.youtube.com/watch?v=cKqd8xtHKp8

**Comment by atsushi10mino** [comment]
認識が行えたので閉じる
