### ISSUE TITLE
ROS上でmaxonモータの動作確認を行う

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#42]
#38 で議論されている揺動URGの件で使用するモータの候補にmaxonのEC-maxが挙がっている。

ROSにはEPOSのドライバが既に存在しているので、それを用いて動作確認を行う必要がある。

**Comment by DaikiMaekawa** [comment]
IMUがなければ安定した自律走行はできていないので #41 の問題の対処の方が優先度としては高いです。
評価ボードEVAL-ADISの動作確認の方を優先して対処してください。 @Nasupl

**Comment by Nasupl** [comment]
ROSのepos_driverはダメなので、 Autonで使用されていたEPOSのドライバを使用したところ、エンコーダからの読み込みまでできました。今後リファクタリングしていきます。

**Comment by ShotaroTerato** [comment]
Windows上のEPOS Studioでのモータの駆動を確認しました．EPOSとモータには問題ないようです．
linuxの方での駆動を試みます．

**Comment by Nasupl** [comment]
もう進展ないと思うので閉じます．
