### ISSUE TITLE
IMUとAutowareの互換性

### ISSUE THREAD

**Issue by Akito-Shirai** [open-rdc/orne_navigation#420]
https://github.com/open-rdc/orne_navigation/issues/405
上記issueの内容に関連して、orneに使われているADIS16465とAutowareの互換性を調べる。
Autoware側の推奨は9軸であるが、ADIS16465は6軸であり、orientationが足りていない。
この環境でもLocalizationできるのかを調べて貰いたい。

**Comment by yasuohayashibara** [comment]
９軸というのは磁気センサを含みますでしょうか．
経験的に磁気センサは導入しないほうが自己位置推定は安定します．
念のためお伝えします．

**Comment by Akito-Shirai** [comment]
はい、含みます。
分かりました。ただ、Autoware側の要求が９軸でしたので、磁気方位なしの6軸でも利用できるのか検証してみます。

**Comment by Akito-Shirai** [comment]
Autoware推奨のIMUがこちらです。
https://www.analog.com/media/en/technical-documentation/data-sheets/ADIS16470.pdf

**Comment by tiger0421** [comment]
![icartAndAutware](https://user-images.githubusercontent.com/20837922/64097194-86b44a00-cd9e-11e9-9e39-7491b7bca3a6.png)

autware と orne_bringupで飛ぶトピックについて。
imu/data_rawをみたところ
・autoware -> x=0.628... y=-0.335... z=-49.063...
・orne        -> x=0.116... y=-0.066... z=-9.81...

5倍されてる...？

**Comment by taishiyamamoto** [comment]
AutowareのGUIで立ち上げることのできるIMUのパッケージを使うとurdfが上書きされるようだったため、以下のファイルを編集しました。
/home/icart/Autoware/ros/src/sensing/drivers/imu/packages/analog_devices/launch/adis16470.launch

９行目のpublish_tfのflagをfalseに変更しました。
![image](https://user-images.githubusercontent.com/25315656/64109108-98efb180-cdb9-11e9-956a-a582bc9794ee.png)

**Comment by tiger0421** [comment]
/home/icart/Autoware/ros/src/sensing/drivers/imu/packages/analog_devices/src/adis16470.cpp
の299~300行目の値を変更

adi_driverのhistory
https://github.com/open-rdc/adi_driver/commit/3dff6168e2257ac90d24b2efe324c8e44144cd90
を参考にした
これでAutowareとorneのIMUの値が5倍になる現象を解決できるはず

追記: ビルドできなかった

**Comment by MasayaOkada** [comment]
安定するバージョンを探して環境構築する．
今の環境をどこかに残しておく．

**Comment by tiger0421** [comment]
上記(https://github.com/open-rdc/orne_navigation/issues/420#issuecomment-527113688)
で変更した部分を元に戻して
~/Autoware/ros
$./catkin_make_release
をしたところエラーが出た

追記: 上記のプログラムを変更しても同様のエラーログが出た
![buildError](https://user-images.githubusercontent.com/20837922/64674534-fff12280-d4ab-11e9-8057-5edec175e219.png)

**Comment by tiger0421** [comment]
$rostopic echo /imu/data_raw
をそれぞれ
$roslaunch orne_bringup orne_alpha.launch
と
AutowareのGUI(Runtime manager)で実行したときの様子

結果: linear_accelerationがAutoware側は5倍されている
![imuTopic](https://user-images.githubusercontent.com/20837922/64674995-1186fa00-d4ad-11e9-8b78-2a3d9b899cee.png)

**Comment by tiger0421** [comment]
プログラムを書き換えてビルドしたところエラーログは出たものの修正箇所はビルドが通っていたみたい(?)
Autoware側での値がiCart側の値と一致した
![imuTopic2](https://user-images.githubusercontent.com/20837922/64675547-67a86d00-d4ae-11e9-9868-94d214205c0b.png)

**Comment by tiger0421** [comment]
ビルドは
$catkin_make
で通るようになりました
IMUのデータはAutowareで使えそうなのでクローズします
