### ISSUE TITLE
ベクターマップの生成

### ISSUE THREAD

**Issue by Akito-Shirai** [open-rdc/orne_navigation#421]
https://github.com/open-rdc/orne_navigation/issues/405
上記issueに関連して、ベクターマップを生成する。

**Comment by Akito-Shirai** [comment]
![スクリーンショット 2019-09-03 5 06 32](https://user-images.githubusercontent.com/42163768/64132156-ae3ffc80-ce08-11e9-8f3d-ce62b8b7d594.png)
本来はもっと多くの情報を示すが、
今回はデモ用として、簡易的なベクターマップを作成した。

**Comment by MasayaOkada** [comment]
imuが使えるようになり次第実験

**Comment by Akito-Shirai** [comment]
生成できることが確認できたので、closeする。
