### ISSUE TITLE
βの自己位置が破綻する

### ISSUE THREAD

**Issue by hoshianaaa** [open-rdc/orne_navigation#429]
本走行エリアの最初の曲がり角までの道で自己位置が破綻する。

**Comment by hoshianaaa** [comment]
https://youtu.be/MlXpuiBJHaU

**Comment by hoshianaaa** [comment]
https://youtu.be/2EljVry_VC8

**Comment by hoshianaaa** [comment]
対策
1.「~odom_alpha3 (double, default: 0.2)　Specifies the expected noise in odometry's translation estimate from the translational component of the robot's motion.」 を上げる
2.途中で回転を入れる

**Comment by taishiyamamoto** [comment]
経路を修正したところ，上記の箇所では自己位置が破綻しなくなったため，一旦閉じます．
