### ISSUE TITLE
αの放熱

### ISSUE THREAD

**Issue by hoshianaaa** [open-rdc/orne_navigation#430]
確認走行で、アルファのpcがフリーズした

**Comment by yasuohayashibara** [comment]
タイトルだけだと何が起きたかが分かりませんので，後日で構いませんので具体的な問題を書くようにしてください．

**Comment by hoshianaaa** [comment]
外装をつけて津田沼校舎を五周したが問題はなかった

**Comment by JinyaIseki** [comment]
現在、PCが不調だが、スペック不足による可能性が高い
