### ISSUE TITLE
三次元地図の編集（車、人の削除）

### ISSUE THREAD

**Issue by JinyaIseki** [open-rdc/orne_navigation#436]
ランドマークとしてふさわしくない，車や人を三次元地図から削除する

**Comment by JinyaIseki** [comment]
CloudConpare で車を削除した

before
![ori](https://user-images.githubusercontent.com/28559030/67559951-dc7cf100-f754-11e9-8540-cb8f20c2d217.png)

after
![car_d](https://user-images.githubusercontent.com/28559030/67559963-e141a500-f754-11e9-9df7-703434868ecc.png)

**Comment by Akito-Shirai** [comment]
人を削除するのはcloudcompareでは無理かと思います．
また，人を消す処理をpclを用いて既に行っていますが，これ以上フィルタをかけると確認走行エリアのランドマークの精度が落ちます．

**Comment by JinyaIseki** [comment]
CloudConpare で　人と車を削除した

original
![ori](https://user-images.githubusercontent.com/28559030/67568666-c593ca00-f767-11e9-992b-176027c4635f.png)

after
![carhum](https://user-images.githubusercontent.com/28559030/67568665-c4fb3380-f767-11e9-9832-98fa5eae208e.png)

**Comment by JinyaIseki** [comment]
自己位置推定のシミュレートにより地図の地面は削除したほうが良いとわかった
（上の地図のように地面ごと人と車を削除した場合）

上の人と車を削除した地図で自己位置推定のシミュレートした結果（以下の動画）,
17秒辺りでパーティクル群が上下２つに分裂している.（上の群が正しい）
２２秒辺りで下のパーティクル群が優勢になる.
このとき、地面にマッチングしており，自己位置推定がずれている.
45秒辺りで上のパーティクル群が優勢となり，自己位置推定に成功する．

マップ：　　　　　　　　　　　　　紫色の点（高層）↔暗い赤色の点（低層）
パーティクル（自己位置推定結果）：　動画中央付近の赤色の明るい矢印群
マッチングした点：　　　　　　　　白い大きな点
マッチングしていない点：　　　　　 白い小さな点

　動画
https://drive.google.com/open?id=1gaNNdcBSnDZs67R4yrpznP_VHAlRMYtJ



それを受け，つくば市役所付近の地面を削除した地図でシミュレートした結果，
パーティクル群が分裂することなく，自己位置推定に成功した（動画内での範囲）

　地図
![curhumgrim](https://user-images.githubusercontent.com/28559030/67761497-bb830b80-fa86-11e9-8bf9-8baf80328edf.png)

　動画
https://drive.google.com/open?id=1MqTKijxMqQ75CAP3JFmW8TbW49Q3jfIE

**Comment by yasuohayashibara** [comment]
上の動画ですが，どのように解釈すればよいかが分かりません．
２つとも同じように処理されているように見えます．
もう少し解説してもらったほうが良いです．

**Comment by JinyaIseki** [comment]
走行領域全域の地面を削除した
![cutgrp](https://user-images.githubusercontent.com/28559030/67859847-e8efb800-fb5f-11e9-82c0-a5eddf882344.png)

**Comment by taishiyamamoto** [comment]
車と人を地図上から消したためcloseします。
なお、地面成分は走行不可な領域以外は消さないほうがよい可能性がある。
