### ISSUE TITLE
つくばチャレンジ2019結果

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne_navigation#440]
つくばチャレンジの結果をこちらのissueに追加したいと思います．
記録を残す意味でできるだけ整理して追加していただければと思います．

**Comment by yasuohayashibara** [comment]
２台出場

本走行
ORNE-α　　0m (VLC-16, mcl-3dl)
ORNE-β　500m (TOPURG)

ORNE-αは前日ゴール(2km)近く走行していたが，当日USBのトラブルで出走できず．
ORNE-βは500m地点の横断歩道を渡りきれずに時間切れ．その後、縁石に乗り上げそうになったため、非常停止スイッチを押した。

**Comment by yasuohayashibara** [comment]
新たに実装した要素
※気づいたら追加して下さい．

・３次元地図生成 (google cartographer) #403 
・mcl-3dlによる走行 #418
・縦列に並び再始動する機能(orne_strategy) #413 

＊追記　山本大志
実装しようとした要素

- 人物探索（３次元点群） #419 
- 信号認識 #423 
- 迂回経路の生成 #422

**Comment by yasuohayashibara** [comment]
結果を踏まえて
- 必要と感じられる機能

・処理の軽量化 (or PCの処理性能の向上)
・ハードウェアの状態監視・再起動
・無線モニタリング
・バッテリ残量計
・防水機能
・音声出力
・画像処理の活用
・運用しやすいハードウェア
・GPSを用いたナビゲーション

- つくばチャレンジの課題として

・走行可能領域検出
・ルート探索機能
・探索対象検出
・地図無し走行
・信号機赤・青判別

**Comment by taishiyamamoto** [comment]
情報共有できたので閉じます．
