### ISSUE TITLE
回路について

### ISSUE THREAD

**Issue by ghost** [open-rdc/orne_navigation#443]
αやβに実装したい電流電圧計をγの方で実験を行います

前回のMTG(11/12)にてりゅうせい君の回路的に測定器に定格以上の電圧がかかるのでは？とのことだったが
γに搭載されている電源供給基板にて，12Vの供給ができそうなのでそれを用いることとなりました。

**Comment by yasuohayashibara** [comment]
電源に24V以上を入力できないことは確認しましたでしょうか？
もし型番を教えてくれたら調査することができます．

**Comment by yasuohayashibara** [comment]
こちらに記載されていました．
https://docs.google.com/document/d/1mCt8R_fKKehR0YAFKUCG7KNvmVjKTaYM-KgVGHul5Ic/edit#heading=h.cxch2ew1dk45

確認しました．
回路に使用しているレギュレータの定格が24Vのようですので，おそらく大丈夫なような気もしますが，安全を考えると別電源ですね．

電気回路の依存関係をできるだけ作りたくは無いとは考えていますが，仕方が無いですかね．

配線が複雑にならないようにできるだけ配慮してもらえればと思います．

**Comment by ghost** [comment]
ありがとうございます．
今回は実験も兼ねて12Vからとり，
測定器用の電源基板が出来次第そちらに移行します．

**Comment by ghost** [comment]
![IMG_4965](https://user-images.githubusercontent.com/16332145/68828176-1869fd00-06e8-11ea-8710-a3d2e8a30e07.jpg)
![IMG_4966](https://user-images.githubusercontent.com/16332145/68828177-19029380-06e8-11ea-9dac-45659b93b0f5.PNG)
無事電源基板からの供給で動作確認ができました．26Vでの確認については安定化電源を用いたいと思いましたが，改めて測定器周りの回路をいじらないとだめみたいです．

また配線が結局複雑化してしまうので改めて作り直すつもりです．
バッテリの電源をひとつの基板に集め、そこから測定器と電源供給基板に分岐させるのがいいのかなと思いました．

**Comment by ghost** [comment]
αやβの回路図はdavに上がっているかもしれない
リレー回路などを用いている後もしかしたら不要かもしれないので要確認です。

根本から見直す必要あるかもしれないです。

**Comment by yasuohayashibara** [comment]
αとβの回路図は夏迫さんがどこかにアップしてくれたような気がします．
もし必要であれば，直接夏迫さんに聞くことも可能です．

**Comment by ryuseiotsuka** [comment]
わかりました。一度回路図をdavから探し、現在実装されている機能の把握をしたいと思います。

**Comment by ghost** [comment]
@yasuohayashibara 夏迫さんに直接きく件について、先生にお願いしてもよろしいでしょうか？
それか連絡先をお教えいただければ僕から聞きます

2019/11/22 追記
林原先生が夏迫先輩に確認のメールを送ってくださいました、ありがとうございます。

**Comment by yasuohayashibara** [comment]
@shulace13 にはccしましたが，問い合わせのメールを出しました．

**Comment by yasuohayashibara** [comment]
- [x] ORNEの電子回路の回路図をアップロードする．

**Comment by ghost** [comment]
アップしましたが，このリポジトリのトップ階層にのせました．必要があれば移動をおねがいします．

**Comment by yasuohayashibara** [comment]
どこ？
見つけられませんでした．
リンクを張ってもらえれば助かります．

**Comment by ghost** [comment]
https://github.com/open-rdc/orne_navigation/blob/kinetic-devel/schema.pdf
これです

**Comment by yasuohayashibara** [comment]
なるほど．
レポジトリに含めるとしたら，docsの中となりますが，wikiに置いた方が良い内容です．
あと，masterに直接コミットするのを，実は禁止しています．
ブランチを作ってプルリクを投げてレビューを受けてからマージするというのが正式な方法となります．
手間をかけますが，一旦消してwikiに置いてくれると助かります．

**Comment by ghost** [comment]
すみませんでした，消しました．
~~ただwikiに直接画像をはれなかったのでもう少しあとになります~~\
https://qiita.com/jollyjoester/items/55a863d6b53f8ffd2d48
ここを参考にしています、一応回路図はwikiにあげてありますがmdでうまくpathがひけなくて表示できません😞

**Comment by ghost** [comment]
[orne_a_PowerToMotor.pdf](https://github.com/open-rdc/orne_navigation/files/3929867/orne_a_PowerToMotor.pdf)

**Comment by yasuohayashibara** [comment]
こちらが適切かは分かりませんが，リンクを貼っておきました．
https://github.com/open-rdc/orne_navigation/wiki

**Comment by ryuseiotsuka** [comment]
電流電圧計の定格を超えた使用ができるのかの確認を行いました
27Vまで動作を確認しました。

**Comment by taishiyamamoto** [comment]
@ryuseiotsuka @shulace13 
現在時点では電流電圧計の選定が完了したということでしょうか．
よろしければこのissueをcloseして，充電回路の設計の方をしてもらえたらと思います．

補足ですが夏迫さんが作成した遮断回路は下記issueにて廃止することを検討しています．
https://github.com/open-rdc/orne_navigation/issues/341

**Comment by ghost** [comment]
遮断回路については、次回MTGで確認したいです。
このissueは閉じても問題ないです。

充電回路の設計は別途issue建てておきますが、
αとβのドキュメント化の方を優先します。

**Comment by ryuseiotsuka** [comment]
遮断回路の回路図のドキュメントは別issueかwikiに載せます。
クローズします。
