### ISSUE TITLE
自己位置推定に使用するレーザの本数の検討

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne_navigation#444]
先日知ったのですが，amclで自己位置推定に使用するレーザの本数はたったの30本とのことです．
以下のパラメータの数字がそれになります．
- laser_max_beams 

資料
http://wiki.ros.org/amcl

UTM-30LXで1080の距離を取得して，それを30に間引いて使用していたようです．
だから複雑な形状の地形では収束しにくかったのですね．

およそですが，

- 1m先で 10cm
- 10m先で1m

の間隔でしか距離を計測していません．
壁などを検出して自己位置推定するには十分ですが，木などを検出して自己位置推定しようとする場合は不足しているような気がします．

**Comment by taishiyamamoto** [comment]
リアルタイムで処理できる程度にパラメータを増やしてみる．
それに基づいてパーティクルの個数を見直す．
