### ISSUE TITLE
melodicへの移行

### ISSUE THREAD

**Issue by taishiyamamoto** [open-rdc/orne_navigation#446]
ros kineticのサポートが2021年4月にEOLされる．
現在のORNEのシステムはkineticで動作しているのでmelodicへ移行する．

**Comment by taishiyamamoto** [comment]
navigationパッケージをmelodicに移行するとorne_navigationが正常に動作しなくなった．
そのため，orne_nabigationの修正を行った．
修正した内容は以下の通りです．
[orne_navigation](https://github.com/taishiyamamoto/orne_navigation/tree/melodic-devel)
bd48868657a382b348cb63f1a65d2a32eb1d2743

https://github.com/taishiyamamoto/fulanghua_navigation/commit/f6b5f5289c1b27ad45b6db6b6535b01ba4203001

[icart-mini](https://github.com/open-rdc/icart/tree/melodic-devel)

Ubuntu18.04LTSのマシンで動作実験を行った．
[youtube](https://www.youtube.com/watch?v=ddNPEBcc-zQ)

**Comment by taishiyamamoto** [comment]
動作しているが，kinetic-develのシステムを完全に移行できていない．

まだ実装されていないシステム
- [x] 膨張リセット法　
https://github.com/open-rdc/navigation/commits/kinetic-devel/amcl/src

- [ ] 一部の回復行動　
https://github.com/open-rdc/orne_navigation/tree/kinetic-devel/orne_recovery_behavior

- [x] 3次元自己位置推定　

- [x] シミュレーター

**Comment by taishiyamamoto** [comment]
膨張リセット法を実装した．
変更内容は以下
https://github.com/taishiyamamoto/navigation/commit/39f048581b1ef3658626fbb19ebd59c540560503#diff-f9c8b2ff23a212af56d0b3de46fcf48b

**Comment by hoshianaaa** [comment]
シミュレータを対応させた
https://github.com/open-rdc/icart/pull/124

**Comment by taishiyamamoto** [comment]
一部の回復行動に関して，このプログラムはamclの仕様（ロボットが停止していると更新を行わない）ことが原因で実装されたものだと思うので，mcl_3dlのような逐次的に自己位置推定が行われるパッケージを用いる場合はあまり必要でない可能性があります．

**Comment by yasuohayashibara** [comment]
@taishiyamamoto 
以下で動作を確認しました。
https://github.com/open-rdc/orne-box/issues/14

管理が大変ですので、open_rdcのレポジトリにもmelodicの変更を反映してもらえればと思います。

**Comment by taishiyamamoto** [comment]
変更を反映するプルリクを送りました．
@yasuohayashibara 
よろしければ確認の後，マージをお願いします．
https://github.com/open-rdc/orne_navigation/pull/463
https://github.com/open-rdc/navigation/pull/11

**Comment by taishiyamamoto** [comment]
orne_navigationはwstoolを用いているため，パスをopen-rdcのものに変える必要がある．
https://github.com/taishiyamamoto/orne_navigation/blob/melodic-devel/orne_pkgs.install

**Comment by yasuohayashibara** [comment]
#463 に関しては前川さんがマージしてくれたようです．
gazeboでは動作を確認したので，大丈夫だと思います．

**Comment by taishiyamamoto** [comment]
コンフリクトが発生していましたが，解消しました．
https://github.com/open-rdc/navigation/pull/11

**Comment by yasuohayashibara** [comment]
GitHubの操作を間違えて，こちらをいきなりプッシュしてしまいました．
すでにkineticでは検証済みで害は無いと思いますので，改めてブランチ→PRとしませんが，よろしいでしょうか．
意見のある方はお願いします．
4ad85c99e5bd440d18ee7f76370c0382e20d46b3

**Comment by taishiyamamoto** [comment]
inf_is_validのフラグの内容について書かれたサイトのリンクを添付しておきます．
http://wiki.ros.org/costmap_2d/hydro/obstacles
私はプッシュで大丈夫だと思います．

**Comment by taishiyamamoto** [comment]
現在，open_rdc/navigationのmelodic-develのブランチがビルドできない状況になっています．
https://github.com/open-rdc/navigation/tree/melodic-devel

**Comment by taishiyamamoto** [comment]
すみません，コンフリクトを無理に解消したことが原因でビルドができなくなっていました．
@yasuohayashibara 
一旦プルリクを投げなおしてのでよろしければ確認の後マージお願いします．

**Comment by yasuohayashibara** [comment]
既にPRは無いようですが解決？

**Comment by taishiyamamoto** [comment]
すみません、リンクを添付します。
https://github.com/open-rdc/navigation/pull/12

**Comment by tiger0421** [comment]
![Screenshot from 2020-04-21 16-54-25](https://user-images.githubusercontent.com/20837922/79840419-d2c90300-83f0-11ea-94a0-2a43d8956951.png)
inf_is_validのフラグを立てたのですが/scanにはInfが混じっています．
コストマップを処理するときのみInfが変わるのでしょうか？

**Comment by yasuohayashibara** [comment]
> コストマップを処理するときのみInfが変わるのでしょうか？

はいそのとおりです．

コストマップのパラメータですので，コストマップ内の処理の方法を変えます．
ローカルコストマップの生成時に，infがあると障害物が消えなくなります．
レーザレンジセンサの計測距離が環境に比べて短いと，障害物が残ったままになります．

こちらで保科さんが検証してくれています．
https://github.com/open-rdc/orne_navigation/pull/442#issuecomment-562210372

**Comment by taishiyamamoto** [comment]
melodicへの移行は終わったのでcloseします．
問題が発覚した場合は別issueを立てて対応します．
