### ISSUE TITLE
ORNE-βに発生した問題点

### ISSUE THREAD

**Issue by taishiyamamoto** [open-rdc/orne_navigation#450]
ORNE-βの本走行時の動画とデータを確認して問題点をリストアップし，それに対する手法を検討する．

**Comment by taishiyamamoto** [comment]
発生した問題点として
- 道の淵が地図に記録されていないので，waypointの配置にヒューマンエラーが生じる．
- amclだと，ロボットが停止している（速度指令が送られていない）時に観測データを破棄してしまう．
- 走行禁止領域にパーティクルがある場合それらは破棄するべきだが，それが実装されていない
- 自己位置推定の候補が複数ある場合の対処がない

**Comment by hoshianaaa** [comment]
走行禁止領域のパーティクルを消す機能を作成
プルリクエストした:https://github.com/open-rdc/navigation
[動画]
・なし: https://www.youtube.com/watch?v=zoXr5W0a1Kw&feature=youtu.be
・あり: https://www.youtube.com/watch?v=PQ0t05EA1dY&feature=youtu.be

**Comment by hoshianaaa** [comment]
問題点 https://www.youtube.com/watch?v=QvvUqTfga5c&feature=youtu.be

**Comment by hoshianaaa** [comment]
追加すべきかよくわからない

**Comment by hoshianaaa** [comment]
コストのパーティクルを消すとパーティクルの重心がコストから遠ざかり、ロボットの推定位置がコストから遠ざかる.それによってコストに近づく経路生成がされ、実際のロボットはコストに入ってしまう.

**Comment by hoshianaaa** [comment]
削除機能はない方が良さそうだ
