### ISSUE TITLE
プラットフォームロボットの設計

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne_navigation#451]
#447 で議論したプラットフォームロボットの設計を行う．

**Comment by yasuohayashibara** [comment]
まずはレーザが透過するかを検証するために，以下を購入しました．
http://www.acrysunday.co.jp/new_products/archives/cat15/cat18/post_3.html

**Comment by hoshianaaa** [comment]
マルチエコー機能があるとアクリルを通過したデータを取得できる
https://www.hokuyo-aut.co.jp/products/data.php?id=52

**Comment by yasuohayashibara** [comment]
透明度の高いアクリルが到着したのでそれで検証したいと思いますが，ガラスを透過することが問題になっていましたので，おそらくは透過するのではないかと考えています．
謳い文句では，ガラスより透過性が高いとなっています．
http://www.acrysunday.co.jp/products/pla_bord/01.html

**Comment by tiger0421** [comment]
新しく買ったアクリル板の実験
上：何も置いてないとき
下：目測5cmの場所にアクリル板を置いた結果

![image](https://user-images.githubusercontent.com/20837922/70975209-cfdd9f00-20ec-11ea-8ddb-2c72cc17d1ab.png)

**Comment by tiger0421** [comment]
1.5m先においたとき
![image](https://user-images.githubusercontent.com/20837922/70976567-83479300-20ef-11ea-8ee5-f47281bfc7b4.png)

**Comment by ghost** [comment]
台車には
Doog https://jp.doog-inc.com/product-thouzer.html
か
iCart-middleのどちらかがよろしいかと思います．

**Comment by yasuohayashibara** [comment]
iCart-middleの予定です．
開発資源を集中するために，H/Wはできるだけ揃えたいと思います．

**Comment by yasuohayashibara** [comment]
近赤外線の透過性の高いアクリルがあったが，気軽に交換できないぐらい高価です．

https://www.monotaro.com/g/04181530/

**Comment by yasuohayashibara** [comment]
遅くなりましたが，プラットフォームの案を設計しました．
まだ，細部を示せていませんが，問題なければこの構成にしたいと思います．
明日のミーティングで意見を聞いて，修正した後，部品の調達を始めたいと思います．
なお，URGに関しては島田君などの実験結果から中に入れるのが難しそうと感じましたので，とりあえず外に出しています．

![image](https://user-images.githubusercontent.com/5755200/74628897-27a29000-519a-11ea-80c9-10dcd77cd197.png)

持ち手は折りたたんで収納しやすくしました．

![image](https://user-images.githubusercontent.com/5755200/74629009-86680980-519a-11ea-839b-e3cc39878899.png)

![image](https://user-images.githubusercontent.com/5755200/74629013-89fb9080-519a-11ea-8289-eaac10df5f57.png)

寸法
![image](https://user-images.githubusercontent.com/5755200/74630129-35a5e000-519d-11ea-8cfb-24af065b6c37.png)

**Comment by yasuohayashibara** [comment]
ミーティングで特に意見が出ませんでしたので，こちらの設計で製作します．

**Comment by yasuohayashibara** [comment]
設計中のデータは以下に置きます．

https://drive.google.com/drive/folders/1FTzKjHyfmug_UDPVUtk7wh9Z_zvEPqiV?usp=sharing

**Comment by yasuohayashibara** [comment]
だいたいコンセプトに沿った設計が完了した．

主な追加は以下の３つです．

１）無線充電システム #460 
２）防水スピーカ　HERDIO 8541747086
３）タブレット　xperia z4 tablet

タブレットは防水・GPS・ジャイロセンサで絞り込んだら上記となった．
一応屋外でも見やすいとのレビューもあった．
タブレットは見やすい角度に調整できます．

![image](https://user-images.githubusercontent.com/5755200/75090063-670a1b80-55a2-11ea-9dc0-408d46808ce8.png)

**Comment by yasuohayashibara** [comment]
現時点の設計データです．

重量　30kg
速度　1.85m (時速6.6km)
登坂能力　0.67 (33.8deg)
乗り越え可能な段差　25.8mm

**Comment by yasuohayashibara** [comment]
設計が終了して，発注まで完了したためissueを閉じます．
なお，制御回路の設計が含まれていませんが，それは別issueで行います．
ちなみに，無線充電器は予算不足のため，来年度に予算があれば購入する予定です．
（まあ5年計画ですので．．．）
