### ISSUE TITLE
costmapに仮想的な壁を生成するパッケージを作成

### ISSUE THREAD

**Issue by hoshianaaa** [open-rdc/orne_navigation#452]
つくばチャレンジの「経路封鎖」、「地図なし走行」などに使えるかもしれないと思い作成した

![wall](https://user-images.githubusercontent.com/40942409/71477215-230dcb00-282c-11ea-955b-03bbe2b1d03b.png)

動画
https://www.youtube.com/watch?v=yeid-L35hc0&feature=youtu.be

パッケージ
https://github.com/hoshianaaa/move_base_virtual_wall_server

**Comment by yasuohayashibara** [comment]
open-rdcにフォークさせてもらいました．
https://github.com/open-rdc/move_base_virtual_wall_server

開発が終了しているとしたら，ミーティングで確認してissueを閉じていただければと思います．

あと，こちらコストマップの進入禁止エリアを使用するときと比べて，どこが異なるのかをミーティングのときで構いませんので教えて下さい．

**Comment by hoshianaaa** [comment]
やっぱり使えない気がしてきたので閉じる.
