### ISSUE TITLE
春休みの開発方針

### ISSUE THREAD

**Issue by Takuyakataoka** [open-rdc/orne_navigation#453]

**Comment by Takuyakataoka** [comment]
### GPS F-9Pの開発
目的：位置情報を用いたナビゲーションを行いたい
・B4メインで開発(リーダー山本)
 -> 実用可能か実証する　
・B3も積極的に参加してほしい

### α，βのハードウェアの改良
目的：PCやハブが変更になったので対応させる
・骨組みの改良（リーダー島田）
-> ガレリアが乗るようにする
・USBハブの実装

### RasPi mouseを動かす
目的：実機を用いて，実用的な経験値を得る
達成目標：未定
・ROS入門（[Raspberry Piで学ぶ ROSロボット入門](https://www.amazon.co.jp/dp/B06Y5M865L)）に従って，ミーティング後に毎回開発を行う
・ROSの勉強

### 勉強会の実施（上記目的のための開発日程）
実施日程：2/11, 18, 25, 3/3, 10, 17, 24, 31

**Comment by ryuseiotsuka** [comment]
詳細な勉強会の内容は1月29日に決定する

**Comment by tiger0421** [comment]
春休みが終わったので閉じます
