### ISSUE TITLE
GNSSモジュールの動作確認

### ISSUE THREAD

**Issue by taishiyamamoto** [open-rdc/orne_navigation#454]
#453 より，GNSSを用いたナビゲーションシステムの開発に向けて取り組む．
このissueでは購入したGNSSモジュールの動作確認を行う．

**Comment by taishiyamamoto** [comment]
ZED-F9Pを搭載した以下のGNSSモジュールを購入した．
https://www.bizstation.jp/ja/drogger/dg-pro1rw_index.html

これからモジュールの動作確認を行う．

**Comment by taishiyamamoto** [comment]
下記サイトを参考にwindowsでの単独測位による動作確認を行ったところ，GPS，GLONASS，Galileoから位置情報を受信できたことがわかった．
https://drogger.hatenadiary.jp/entry/dgpro1rw_windows
![COM6 - u-center 19 12 2020_01_20 15_04_50](https://user-images.githubusercontent.com/25315656/74130707-0552c480-4c26-11ea-966e-5c8f787f6669.png)

**Comment by taishiyamamoto** [comment]
Ubuntuでの動作確認を試みたところ，Bluetoothによる接続を行ったのち，すぐに切断されてしまう問題が起こった．

**Comment by taishiyamamoto** [comment]
LinuxではBlueZが標準的に使われているため，GNSSモジュールを接続できるようにBlueZのプログラムを変更する必要があると考えられる．
https://wiki.archlinux.jp/index.php/Bluetooth

**Comment by taishiyamamoto** [comment]
このモジュールには拡張性を考慮してUARTピンが出ているため，有線による接続ができる可能性がある．
https://www.bizstation.jp/ja/drogger/dg-pro1rw_index.html?tab=function

**Comment by taishiyamamoto** [comment]
現在，コネクタとケーブルの購入を検討しています．

**Comment by taishiyamamoto** [comment]
企業に相談したところ，接続しようとしているBluetoothプロトコルがsppでない可能性があるとの指摘をいただきました．

SPPとは、Bluetoothのプロファイルのひとつで、Bluetooth搭載機器を仮想のシリアルポート化するためのプロファイルのこと
https://www.kddi.com/yogo/%E6%83%85%E5%A0%B1%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0/SPP.html

らしいです．

また，LinuxにはrfcommというBluetoothシリアルポートデバイスと接続するために使うコマンドがあることがわかりました．
https://linux.die.net/man/1/rfcomm

**Comment by taishiyamamoto** [comment]
UbuntuでGNSSモジュールのBluetooth接続ができることを確認しました．
下記のシェルスクリプトを実行することで，LinuxでDG-PRO1RWをBluetooth接続することができます．
https://github.com/NaokiTakahashi12/connect-serialport-for-bluetooth
![Screenshot from 2020-02-12 17-16-28](https://user-images.githubusercontent.com/25315656/74315770-81324580-4dbb-11ea-8263-54c099218ca5.png)

**Comment by taishiyamamoto** [comment]
ROSでデータを取得できることを確認しました．
下記パッケージを用いることでNavSatFixで緯度や経度の情報をトピック通信で取得できます．
https://github.com/ros-drivers/nmea_navsat_driver

シリアルポートのパスとボーレートのみ変更してサンプルのlaunchプログラムを実行しました．

動作確認の様子の動画と得られた緯度と経度の画像を添付します．
https://youtu.be/Cx6mF2hoRpo
![Screenshot from 2020-02-12 17-16-44](https://user-images.githubusercontent.com/25315656/74316687-5943e180-4dbd-11ea-9d4e-704534365b04.png)

**Comment by taishiyamamoto** [comment]
動画でも間違えていますが，シリアルポートの権限をあげないとlaunchプログラムからではシリアルポートをopenできないので
`# chmod a+rw /dev/rfcomm0`  
で変更しています．

**Comment by taishiyamamoto** [comment]
モジュールの動作確認を行えたので，今後は

- [ ] データ取り（分散などの調査）
- [ ] RTK-GNSSを行う

予定です．

**Comment by taishiyamamoto** [comment]
今度の予定ですが，このモジュールにはWindowsとAndroidでアプリケーションが提供されているため，それを用いて設定及びデータ取りを行いたいと思います．
https://drogger.hatenadiary.jp/entry/drogger-gps_app_guide

**Comment by taishiyamamoto** [comment]
17時間データを取得し続けた際の散布図を添付します．
縦軸が経度，横軸が緯度となっています．
![idokeido](https://user-images.githubusercontent.com/25315656/74330738-90be8800-4dd5-11ea-8a85-4766424b7a77.png)

**Comment by yasuohayashibara** [comment]
経緯度ではズレが分かりにくいので，メートル単位（だいたいで構いません）とかにしてくれると助かります．

**Comment by taishiyamamoto** [comment]
このサイトで測量計算すると大体55mほどの偏差があるみたいです．
屋内窓際での測量データなので，あまり参考にはならないかもしれませんが...
https://vldb.gsi.go.jp/sokuchi/surveycalc/surveycalc/bl2stf.html

**Comment by yasuohayashibara** [comment]
なるほど．
屋内ならずれることが分かりましたので，今度は屋外（条件の良さそうなところ）でできれば計測してみてください．
それで自己位置推定に使用できそうなぐらいの精度が出たら，積極的に使用したいと思います．

**Comment by taishiyamamoto** [comment]
条件のよさそうな屋外で1時間計測してみました．
![緯度経度](https://user-images.githubusercontent.com/25315656/75237370-91f2aa80-5802-11ea-9003-4c6f00e0de7e.png)

データにはだいたい9m程度の偏差がありそうです．

**Comment by yasuohayashibara** [comment]
こちらのページを使って計算すると，対角で2mでした．
https://keisan.casio.jp/exec/system/1257670779

![image](https://user-images.githubusercontent.com/5755200/75240461-b69d5100-5807-11ea-872f-e4235a312be2.png)

**Comment by taishiyamamoto** [comment]
すみません，計算を間違えていました．
https://vldb.gsi.go.jp/sokuchi/surveycalc/surveycalc/bl2stf.html
![Screenshot from 2020-02-25 23-06-45](https://user-images.githubusercontent.com/25315656/75254371-9da29900-5823-11ea-881b-8e0678836afa.png)

**Comment by MasayaOkada** [comment]
データ取り内容
・条件の悪いところ
・24時間計測
・移動した軌跡

**Comment by taishiyamamoto** [comment]
tree-mapsというGNSSの測位データをgooglemap上にプロットするツールを用いて軌跡を可視化しました．
https://1-dot-tree-maps-152415.appspot.com/prot/

nmea_navsat_driverを用いてデータを取得し，rosbag recordを用いてデータを記録しました．GNSSレシーバーの測位方法は単独測位です．

測位の様子を動画で撮影してないので示すことはできませんが，なるべく道の中央を歩くようにしています．

![cit_gnss_tracking_data](https://user-images.githubusercontent.com/25315656/86098988-d7492080-baf1-11ea-9edc-f1e4bf18b0f8.PNG)

データを下記リンクにアップロードしました．
https://drive.google.com/drive/u/0/folders/1tqIuyJD9ofi97CM8PvyjpQEjVAt65B3o

**Comment by taishiyamamoto** [comment]
拡大すると，ビル付近で軌跡が歪んでいることがわかります．
![multipass](https://user-images.githubusercontent.com/25315656/86100399-bd104200-baf3-11ea-9ac8-5e81b3117ae4.PNG)

**Comment by ryuichiueda** [comment]
でもそこまで値は飛ばないんですね

**Comment by taishiyamamoto** [comment]
10~20mクラスの誤差は観測されませんでした．
憶測になるのですが，センサリセット等，補助的にセンサデータを用いるのであれば，単独測位でも運用可能かもしれないです．

**Comment by ryuichiueda** [comment]
これくらいなら、誘拐からも戻りやすいかもしれません（ので、例のアルゴリズムの実装を・・・）

**Comment by tiger0421** [comment]
どれくらいの周期ですか？

**Comment by taishiyamamoto** [comment]
rostopic hz で確認したところ、10Hzでした。

**Comment by taishiyamamoto** [comment]
モジュールの動作確認が完了したのでcloseします．今後は，壁の付近を走行した際のデータなど，様々な状況でデータを取る．（データに天気などの情報をメモすることを徹底）

**Comment by luvwinnie** [comment]
@taishiyamamoto 大変参考になりました！

DG-PRO1RWSの場合でも、同じ設定で接続のでしょうか？

**Comment by taishiyamamoto** [comment]
DG-PRO1RWSで試したことはありませんが、下記スクリプトのMACアドレスを変更すれば接続できると思います。

https://github.com/NaokiTakahashi12/connect-serialport-for-bluetooth/blob/master/profile/drogger/dg-pro1rw.sh#L2
