### ISSUE TITLE
αとβのドキュメント化

### ISSUE THREAD

**Issue by ghost** [open-rdc/orne_navigation#455]
αとβの回路を整理する．
本日はαの配線を確認したので回路図におこす．

また、それぞれの回路やスペックをWikiに記す．
Wikiには，現状用いられている回路の経緯を記す．
それぞれの回路を基に改良版を提案する（これについては別途issueをたてると思います）

以下ToDoまとめ

- [x] αの回路確認

- [x] βの回路確認

- [x] αの回路図おこし

- [x] βの回路図おこし

- [x] αの情報をまとめてWikiに記す

- [x] βの情報をまとめてWikiに記す

- [ ] αの回路を改良し検証

- [ ] βの回路を改良し検証

**Comment by NaokiSato102** [comment]
γの物ですが、#445 とかもあります。

**Comment by ryuseiotsuka** [comment]
wikiには情報をまとめて乗せる予定ですが、こちらのissueには情報の共有のし忘れが無いように共有すべき情報はどんどん公開していきます。

**Comment by ryuseiotsuka** [comment]
ORNE-α　現在のシステム図 
![ORNE-α system](https://user-images.githubusercontent.com/50820803/74705126-23d44380-5256-11ea-9a34-f62339f86ceb.jpg)

**Comment by ryuseiotsuka** [comment]
αの感光基板に現在の使用用途を直接書き込みました

**Comment by ryuseiotsuka** [comment]
PowerSupply基板の仕様用途まとめ
![20200215_135002](https://user-images.githubusercontent.com/50820803/74705477-60546f00-5257-11ea-98c7-f60d03ae42b4.jpg)
あとで整理します

**Comment by ryuseiotsuka** [comment]
モータードライバ基板まとめ
![20200215_140559](https://user-images.githubusercontent.com/50820803/74705512-8417b500-5257-11ea-9a74-5cdf605e5a7e.jpg)
こちらもあとで整理します

**Comment by ryuseiotsuka** [comment]
ORNE-βの回路システム図です
![ORNE-β system](https://user-images.githubusercontent.com/50820803/75855193-0d70df00-5e35-11ea-9117-0adc75619296.jpg)

**Comment by NaokiSato102** [comment]
実機との情報の対応の為に、整理する前の、文字を添えた写真も しっかりとした文字と囲いにクリンナップしたものがあった方がいいと思いましたが、どうでしょうか？
元画像さえいただければ数日で出来ます。

**Comment by taishiyamamoto** [comment]
システムズにURGと書いてありますがORNE-βにはURGが2つ搭載されていました．
このシステムズのユニバーサルDCDCとは3D LiDARのYVT-35LXのために搭載されたものです．（今はありませんが）

**Comment by ghost** [comment]
To佐藤くん
写真は撮ってあります。
最終的にまとめる時に旧回路と新回路を載せておくといいですね。

To山本くん
指摘ありがとうございます。

To大塚Rくん
ということなので、上のシステム図に
・今は繋がれていないURGへの端子
・URGへの正しい
・3D LIDARへの端子
の三つの情報修正及び追加をお願いいたします。
でも一緒に見た時はDCDCの先にURGが繋がっていましたよね・・・？

**Comment by taishiyamamoto** [comment]
すみません．そういえば途中から方針が変わっていました．[電源基板](http://t-frog.com/products/power_supply/)から[2D LiDAR](https://www.hokuyo-aut.co.jp/search/single.php?serial=21)に12Vを供給できるようになっているのですが，あまり電流値に余裕のない設計になっていました．
そのため，２つのURGから電源を供給することはできないと判断し，DCDCコンバーターからURGの電源を供給するようにしていました．(#381)
ですのでシステム図はあっています．

**Comment by yasuohayashibara** [comment]
ドキュメントを見直してみて気づきましたが，モータを遮断するリレー回路にサージ吸収用のダイオードが入っていません．
時々電源回路が壊れますが，これが原因かも知れません．

使用しているリレー　LY2- DC12

https://ednjapan.com/edn/articles/1011/01/news114.html

**Comment by ghost** [comment]
感光基板の方ですよね。確かにβの回路周りを確認した時にも、似たような箇所が壊れていてジャンパー線を用いて修理されていましたね。

ただ今後はリレー回路を使わないで、モータ基板の電源供給にキャパシタを挟むことにしています。(#341 より)
一応の対策として、新たに設計する基板(バッテリーから3D LIDARとt-frogのPowerSupplyに分配してもらうためのもの)にグラウンドを十分に確保する、ということを検討しております。

**Comment by yasuohayashibara** [comment]
以前故障したのは，電源基板TF-PW36-5/12Mになります．
以下，追える範囲で故障の履歴を示します．
今考えると，これらはリレーのサージにより故障しているおそれが高いと思います．

### 電源基板　TF-PW36-5/12M
16/01/22 故障
16/09/18 故障 これによりURGが2台連続して故障
https://github.com/open-rdc/orne_navigation/issues/201#issuecomment-299621606

ドキュメント
https://github.com/open-rdc/orne_navigation/wiki/t_frog%E9%9B%BB%E6%BA%90%E5%9F%BA%E6%9D%BF_TF_PW36_5_12M_%E6%95%85%E9%9A%9C%E8%A8%BA%E6%96%AD

### モータドライバ TF-2MD3-R6
17/05/22 初期不良？　制御基板が故障
18/04/21 ２個故障　制御基板が故障　と　ドライバ基板が発火
18/06/15 配線ミスで故障

ドキュメント
https://github.com/open-rdc/orne_navigation/wiki/t_frog%E3%83%A2%E3%83%BC%E3%82%BF%E3%83%89%E3%83%A9%E3%82%A4%E3%83%90_TF_2MD3_R6_%E6%95%85%E9%9A%9C%E8%A8%BA%E6%96%AD

### リレーのサージ
制御回路系を製作する方　@ryuseiotsuka ?

参考までに以前リレーのサージを計測したときの様子を示します．
（別の回路です．）
電源電圧の数倍の電圧が一時的に発生して，電子回路を破壊します．

ということで，リレーをON/OFFするときの，12V電源の波形を確認したほうが良いです．
オシロスコープで確認してもらえればと思います．

ちなみに，壊れたURGは修理不可能でそのまま廃棄となりました．
挽回は難しいので，電源はよくチェックして製作していただければと思います．

![50871952-cd64c680-1400-11e9-856d-ba7ca9b80a16](https://user-images.githubusercontent.com/5755200/76612366-866fe500-655f-11ea-81df-1ee86c60dc89.jpeg)

**Comment by taishiyamamoto** [comment]
ORNE-αを用いてどれくらいサージが発生しているのかチェックする．

**Comment by ryuseiotsuka** [comment]
α・βのシステム図に誤りがある可能性があるので確認する必要がある。

**Comment by taishiyamamoto** [comment]
graph_navigationのパッケージ
https://github.com/Norihiro02/graph_navi

**Comment by ryuseiotsuka** [comment]
サージ電流計測結果
ボタンを押す動作（電流を遮断する動作）がかなり回路の負担になっていることが分かった。
電源遮断時
![20200625_144311](https://user-images.githubusercontent.com/50820803/85662192-8bae0580-b6f2-11ea-8d71-3484f7fe34db.jpg)
電源復旧時
![20200625_145115](https://user-images.githubusercontent.com/50820803/85662837-581fab00-b6f3-11ea-9595-ed6b3331a194.jpg)

**Comment by taishiyamamoto** [comment]
現在のαとβとγのシステム図

**ORNE-α**
![orne_alpha_system](https://user-images.githubusercontent.com/25315656/87918714-c7e64300-cab1-11ea-88e7-b7ff253fb046.png)


**ORNE-β**
![orne_beta_system](https://user-images.githubusercontent.com/25315656/87918368-4abace00-cab1-11ea-9ba9-926100f46f78.png)

**ORNE-γ**
![orne_gamma_system](https://user-images.githubusercontent.com/25315656/87918008-c36d5a80-cab0-11ea-9cca-1ef3b2cdb907.png)

**Comment by ryuseiotsuka** [comment]
システム図ありがとうございます
ToDOリストのα,βの回路図おこしなのですが、回路の大半が既製品なのでチェックをつけていいと思うのですがどうでしょうか。

**Comment by ryuseiotsuka** [comment]
α,βの回路図おこしは上記のシステム図で達成とする

**Comment by taishiyamamoto** [comment]
ORNEの回路に関してまとめたものをwikiに書きました。
https://github.com/open-rdc/orne_navigation/wiki/ORNE%E3%81%AE%E5%9B%9E%E8%B7%AF%E5%9B%B3

**Comment by taishiyamamoto** [comment]
@ryuseiotsuka 
回路の改良と検証は#482 など、別途issueを立てて行っているので、ドキュメント作成をメインとするこのissueは閉じても大丈夫かなと思っています。

**Comment by taishiyamamoto** [comment]
ドキュメントの作成が完了したので閉じる．
