### ISSUE TITLE
βのハードウェア開発

### ISSUE THREAD

**Issue by tiger0421** [open-rdc/orne_navigation#459]
### 目的
つくば課題達成，研究

### 要求
- 配線
- 拡張性

### Sensors
- IMU(ADIS16465)
- VLP16
- web camera or Realsense

### PC
Think pad

**Comment by yasuohayashibara** [comment]
こちら，従来のベータとは異なるものになりますので，名称はδというのはいかがでしょうか．
α，β，γときていますので，次の文字を割り当てた方が良さそうな気がします．
もしくはβ2020でしょうか．従来のベータとは異なる名称で読んだほうが良いと思います．

あと，想定されるコンピュータも記載してくれた方が良いです．

**Comment by taishiyamamoto** [comment]
設計してみました．
何か問題点があれば指摘して頂ければと思います．

オープンプラットフォームロボットと互換性を持たせたほうが良いと思い，#451 の上にノートPC等を搭載する箱を追加するような設計にしています．
箱の前方に回路やバッテリー等をまとめて配線処理を行い，箱の後方でノートPCを設置することを想定しています．
また，車体前方にカメラ(realsense D435i,T265を想定)を，取っ手にGNSSアンテナを搭載する予定です．
![orne_delta_devices](https://user-images.githubusercontent.com/25315656/75635078-8cf48780-5c56-11ea-90e4-745100d3389e.png)

他の特徴としては，
フリーアングルブラケットを用いて折りたたむことができる．
![orne_delta_tatami](https://user-images.githubusercontent.com/25315656/75635133-00969480-5c57-11ea-8a01-cf1fb660abaf.PNG)

箱は前面と後面に2か所ずつで締結されており，取り外しが容易
![buracet](https://user-images.githubusercontent.com/25315656/75635193-6420c200-5c57-11ea-8295-9c7cd0e850a9.png)
![buracet_back](https://user-images.githubusercontent.com/25315656/75635195-65ea8580-5c57-11ea-942d-8746b174698c.png)

赤い板を外すことでバッテリー交換も可能
（ノートPCをマジックテープ等で固定すれば，恐らく板がなくても安定するので省くことを検討中）
![box](https://user-images.githubusercontent.com/25315656/75635199-726ede00-5c57-11ea-8e9e-a6d1855aa11d.PNG)

VLP-16とR-Fans-16両方に対応した取り付け治具を設計
Φ20の半円にLIDAR,非常停止スイッチ，GNSSモジュールの配線を通して運用する予定
![rfans_velo_back](https://user-images.githubusercontent.com/25315656/75635312-591a6180-5c58-11ea-89ed-2706b46afae3.PNG)

**Comment by yasuohayashibara** [comment]
- レバー付きのフリーアングルブラケット良いですね．
- LIDARの位置が低いので，地面を検出するために上に上げた方が良いと思います．
- 重心位置を確認して，転倒しないかを確認してください．
- カメラは雨ざらしにしないほうが良いと思います．（屋根を付けるとか）
直射日光の問題を避けるためにも屋根はあったほうが良いと思います．
- オープンプラットフォームの考え方に従うのであれば，上モノはユニットとして取り外せて，載せてアルファフレームを横からネジで締める程度にしたほうが良いと思います．
あと，電池は即時交換以外は入れたまま充電が前提です．

**Comment by taishiyamamoto** [comment]
velodyneのマニュアルにレーザーが飛ぶ領域が記載されていました．
![velo_keep_out](https://user-images.githubusercontent.com/25315656/75993680-32507980-5f3d-11ea-8aa5-17654c1013a5.PNG)

視野を±15°とすると，現在の設計ではかろうじて視野を確保しているという状態でした．（このマニュアルには視野は±10°と記載されていますが）
![velo_back](https://user-images.githubusercontent.com/25315656/75993887-8196aa00-5f3d-11ea-95ee-35f98995d4b6.PNG)
![velo_side](https://user-images.githubusercontent.com/25315656/75993893-83606d80-5f3d-11ea-8fbd-d5c54061df0a.PNG)

現在のLIDARの位置だと，視野は以下のようになりました．約2.5m先にある地面が検出できます．
![velo_out_of_range](https://user-images.githubusercontent.com/25315656/75994032-b6a2fc80-5f3d-11ea-884c-cb2ca16990b6.PNG)

よって取付治具の高さを5㎜程あげようと思います．

**Comment by taishiyamamoto** [comment]
重心位置を求めました．（モバイルバッテリーを2㎏，ノートPCを1.5kgとして計算しました．）
![center_of_mass_x](https://user-images.githubusercontent.com/25315656/75998675-8579fa80-5f44-11ea-97f9-f59abdc4222a.PNG)
![center_of_mass_y](https://user-images.githubusercontent.com/25315656/75998677-86ab2780-5f44-11ea-999e-d7df1c1ac6d5.PNG)

**Comment by taishiyamamoto** [comment]
下の台車のバージョンが変わったのでそれに対応する必要がある．

**Comment by taishiyamamoto** [comment]
バージョンの変化に対応しました．設計コンセプトは上記と変わっていません．
上の箱のCADデータと部品リストを下記リンクにアップロードします．
https://drive.google.com/drive/folders/1yqpgmu-_5xMmvJX26m-u1H8-Vitg2K3R?usp=sharing

![orne_delta](https://user-images.githubusercontent.com/25315656/84805706-a5d74c00-b03f-11ea-9bb9-1e3251b21c12.PNG)

部品リストを見ると，少なくとも18000円程度かかりそうです．

**Comment by yasuohayashibara** [comment]
チェックします．

**Comment by yasuohayashibara** [comment]
チェックしました．
サイズ感などは良いと思いますが，細部に拘って扱いやすいメカニズムにしたいと思います．
図で示しましたが，全体的なコメントとこだわりを以下列記します．

・orne-boxの天板は上にユニットを乗せる場合には取り外したほうが良いと思います．
・防水にはこだわっているところがあり，できるだけ防水にしたいと考えています．
・防水のためテープとかコーキングで塞ぐのは分解が不要な場所だけにしたいと思います．
・車で移動するときも，分解する場所が少ないものにしたいです．
・排熱ファンは必要ありませんでしょうか．

ロボットを動かしていると，『設計時に対処してくれていればこんなに苦労しないのに』と考えることがあると思います．
アルゴリズムに集中するためには，できるだけ手間のかからないメカニズムを用意することが重要かなと考えています．
その点で，設計に時間をかけても，後の手間を考えるとお釣りがくると思いますので，しっかりと検討して作りたいと思います．

![image](https://user-images.githubusercontent.com/5755200/85221792-c7df1e80-b3f1-11ea-9a36-7198dd98f93d.png)

![image](https://user-images.githubusercontent.com/5755200/85221803-d6c5d100-b3f1-11ea-9f6b-2cb8fd4698a5.png)

[200621_ベータ設計コメント.pptx](https://github.com/open-rdc/orne_navigation/files/4809277/200621_.pptx)

**Comment by taishiyamamoto** [comment]
コメントありがとうございます。
指摘事項をチェックボックス化しました。

- [ ] orne-boxの天板は上にユニットを乗せる場合には取り外したほうが良いと思います．

- [ ] 防水にはこだわっているところがあり，できるだけ防水にしたいと考えています．

- [ ] 防水のためテープとかコーキングで塞ぐのは分解が不要な場所だけにしたいと思います．

- [ ] 車で移動するときも，分解する場所が少ないものにしたいです．

- [ ] 排熱ファンは必要ありませんでしょうか．

- [ ] LiDARの配線の検討が必要.

- [ ] LiDARの位置を後ろにしたほうが後ろが検出できる可能がある.

- [ ] 下の樹脂の板に穴をあける必要がある．

- [ ] ネジにラジアル方向の力が加わる．

- [ ] 背面がオープンになっているため，雨天では動かすことができない．

- [ ] 面倒かもしれないが，接合する部品も書いたほうが良い．

- [ ] 上下を配線する穴が無い．

- [ ] orne-boxの天板があるとすると，そちらの対処も必要.

- [ ] 板を固定する穴が少ないかも．
中央でも固定しないと，板が浮いて水が入るおそれがある.

**Comment by taishiyamamoto** [comment]
LiDARが高い位置にあると，低層にある障害物を認識できなくなるおそれがあるため，調査する．

**Comment by taishiyamamoto** [comment]
Rfansの視野角はマニュアルを見ると以下のようになっていました．
![rfans_vertical_distribution](https://user-images.githubusercontent.com/25315656/85409462-cacc4180-b5a0-11ea-8072-c31b82001a3d.PNG)
![rfans_sensor_dimentions](https://user-images.githubusercontent.com/25315656/85409474-cdc73200-b5a0-11ea-8eba-0753591df987.PNG)

**Comment by taishiyamamoto** [comment]
現在の設計のLiDARの視野の範囲は以下のようになっています．
地面からLiDARの高さは602mmです．
![rfans_vertical_runshort](https://user-images.githubusercontent.com/25315656/85411920-f3096f80-b5a3-11ea-932f-bc7b68122c94.PNG)
![rfans_with_orne_box](https://user-images.githubusercontent.com/25315656/85418242-82fee780-b5ab-11ea-8912-c81c83967cea.PNG)

**Comment by taishiyamamoto** [comment]
LiDARの地面からの高さと，地面をはじめて検出できる距離をグラフ化したものは以下の通りです．

式は検出距離をy，オフセット（Rfans16の場合は15.8mm）をd，地面からの高さをx，視野角をθとすると，
y = (d + x) / tan(θ)
で算出しています．
![image](https://user-images.githubusercontent.com/25315656/85418305-97db7b00-b5ab-11ea-9f1e-0b47256bb08f.png)

現在の設計(地面からの高さが602mm)では，LiDARの表面からや約2.3mほど離れた地面を検出できることになります．

**Comment by taishiyamamoto** [comment]
15.6インチのノートPCであるGALLERIA GCR2070RGF-QCを中に入れた際にどの程度スペースに余裕があるか確認しました．
![box_with_GALLERIA](https://user-images.githubusercontent.com/25315656/85593012-9ed4bd00-b681-11ea-8649-e051ab0ac361.PNG)

現在の設計だと後ろのタブレットとLiDARの視野範囲が干渉していて下げたほうが良いのですが，15.6インチのノートPCが入らなくなりそうです．

ですので，大きい液晶サイズのノートPCを使う場合は小型のモニターを使うなどして基本的に閉じて運用したほうがいいかもしれません．

**Comment by taishiyamamoto** [comment]
LiDARとノートPCの位置関係を逆にする案が出たので，それを検討する．

**Comment by taishiyamamoto** [comment]
orne_boxのリポジトリができたのでそちらに作業を引き継ぐ．
https://github.com/open-rdc/orne-box
