### ISSUE TITLE
プロジェクト分離の検討

### ISSUE THREAD

**Issue by NaokiSato102** [open-rdc/orne_navigation#462]
現在Orne-navigationとOrne-Boxがプロジェクトにありますが、Orne-Boxだけが分離しているのが少々不自然に見えたので、この際Orne-α, β, (γ)も別プロジェクトとして分離するのはどうかなと思った次第であります。
Orne-α, β, γはその性質上中のアプリケーションの開発プロジェクトと分けるのが難しいようにも思えますが…
お暇なときに議論だけでもしておく方がいい様にも思いましたのでissueとしてあげました。

**Comment by yasuohayashibara** [comment]
ロボットごとに管理するメリットはなさそうな気がします．
orne-boxのレポジトリはハードウェアのレポジトリになりますので，別にしています．
