### ISSUE TITLE
βの今後の方針

### ISSUE THREAD

**Issue by tiger0421** [open-rdc/orne_navigation#466]
#447 より
βの今後の方針

### 目的
・課題達成
・研究目的

※　βで安定して動作する技術をαにも取り入れる流れで開発する

### センサ
・3DLiDAR
・2DURG
・GNSS
・Camerα(realsenseD435, WebCamera)

### 内容
・3次元自己位置推定
・低層障害物回避（斜め付URG，Depth cameraなど）
・白線認識
・ER＋GR法
・信号認識
・チェックポイント，封鎖経路

**Comment by taishiyamamoto** [comment]
wikiに情報を記載していつでも見れるようにする．

**Comment by tiger0421** [comment]
wikiに書いたのでCloseします．
https://github.com/open-rdc/orne_navigation/wiki/βの方針
