### ISSUE TITLE
センサの取り付け治具の作成

### ISSUE THREAD

**Issue by taishiyamamoto** [open-rdc/orne_navigation#470]
センサの取り付け治具を作成する．
作成する治具の一覧を挙げる．

- [x] realsenseD435i

- [x] realsenseT265

- [x] R-fans-16

**Comment by taishiyamamoto** [comment]
センサの取り付け治具を作成する．
作成する治具の一覧を挙げる．

- [ ] realsenseD435i

- [ ] realsenseT265

- [ ] R-fans-16

**Comment by taishiyamamoto** [comment]
rfans16とvlp-16を取り付けられるCADモデルを作成しました．
iptファイルとstlファイルをアップロードしておきます．
https://drive.google.com/drive/folders/1xyOZ1PETrPRZbsznUQh_mXcR2zzV6M9d?usp=sharing
![rfans_velo_back](https://user-images.githubusercontent.com/25315656/75635312-591a6180-5c58-11ea-89ed-2706b46afae3.PNG)

@NaokiSato102 
上記CADモデルを3Dプリンタで出力して不具合がないかどうか確認してほしいです．

**Comment by tiger0421** [comment]
RealSense D435i用に設計しました．
取り付けるときはRealSense背面のねじ穴を使います．
指が入るように上下に1cmのスペースを付けました．
また，直射日光を遮る効果があるかはわかりませんが，一応屋根を付けました．

- 前から見た図
![RealSense_front](https://user-images.githubusercontent.com/20837922/87252219-42a8d000-c4ac-11ea-8baf-a4ccf31f2b00.png)
- 左から見た図
![RealSense_left](https://user-images.githubusercontent.com/20837922/87252226-48061a80-c4ac-11ea-85b5-3f88ceda1970.png)
- 右から見た図
![RealSense_right](https://user-images.githubusercontent.com/20837922/87252232-505e5580-c4ac-11ea-990a-2489823513bd.png)
- 屋根の長さ
![RealSense_length](https://user-images.githubusercontent.com/20837922/87252254-7d126d00-c4ac-11ea-967b-11230b339ff8.png)

**Comment by taishiyamamoto** [comment]
d435iを取り付けた状態での動作確認
![Screenshot from 2020-07-20 12-47-41](https://user-images.githubusercontent.com/25315656/87897882-9d7f9000-ca87-11ea-892b-19ef31918d71.png)

**Comment by taishiyamamoto** [comment]
出力しました．
Rfansの固定のため，長さ25mmのM4の六角穴付きボルトが3本必要になります．
また，治具の固定のため，長さ25mmのM5の六角穴付きボルトが4本必要です．
![IMG_1001](https://user-images.githubusercontent.com/25315656/87899201-6ad79680-ca8b-11ea-832d-e98c82234681.jpg)

**Comment by yasuohayashibara** [comment]
林原のネジケースの中にあるかもしれませんが，工場に頼めばいただけけると思います．

**Comment by taishiyamamoto** [comment]
@tiger0421 
RealsenseD435iの治具のデータを公開して欲しいです．

**Comment by tiger0421** [comment]
.iptと.stlがあればいいよね？
https://github.com/tiger0421/Realsensed435_Case

**Comment by taishiyamamoto** [comment]
工作センターに行きましたが、M4×25mmのネジは無いみたいです。

**Comment by yasuohayashibara** [comment]
なるほど．もしかしたら持っているかもしれませんが，購入したほうが早いかもしれませんので購入の場合は型番を下さい．

**Comment by NaokiSato102** [comment]
先輩作のrealsense T265のデータがiptだったので、Inventorで自前でstlに変換しました。
作成したstl, 3mf, gcodeを先輩のところにアップしておきます。

**Comment by taishiyamamoto** [comment]
M4x25mmの六角穴付ボルトの型番です．
https://jp.misumi-ec.com/vona2/detail/110302280360/

@yasuohayashibara 
購入したほうが早そうでしたら4本発注お願いします．

**Comment by yasuohayashibara** [comment]
『208 の型番候補があります』と出ます．

**Comment by taishiyamamoto** [comment]
すみません．型番を記載します．
CBE4-25

**Comment by yasuohayashibara** [comment]
発注しました．

**Comment by taishiyamamoto** [comment]
VLP-16を取り付けるためにはインチネジが必要になります．
![image](https://user-images.githubusercontent.com/25315656/88913993-e233d400-d29c-11ea-8361-d4385ac246c5.png)

この取り付け治具を使う場合，ネジの呼びが1/4inchの長さが約1インチのネジが必要になりそうです．下記にその条件に合いそうな型番を記載しておきます．
CSPPN-SUS-UNC1/4-1

**Comment by yasuohayashibara** [comment]
個数を聞こうとして，忘れておりました．
申し訳ありません．

本日３本発注しました．

**Comment by tiger0421** [comment]
雑ですがβに取り付けました
<img src='https://user-images.githubusercontent.com/20837922/89855578-d5cf4580-dbd1-11ea-93c9-7ac7f862ae84.png' width='380x415'>

**Comment by NaokiSato102** [comment]
realsenseT265の治具の設計に問題あり。
realsenseT265の固定ねじの穴がズレていた。
すでに印刷したものはドリルで穴開けし再利用する。
データは修正を行う。

ネジ頭が飛び出ることに依る問題の発生に備えデータはザクリ穴にしておく。
再利用品でネジ頭問題が出たら再印刷とする。

**Comment by NaokiSato102** [comment]
いざ治具に固定しようとしましたがトラブルが発生しました。
T265のネジ穴は[公称M3 0.5 mm pitch](https://www.intelrealsense.com/tracking-camera-t265/#Support)とのことなのですが、
研究室に転がってるM3ネジだと、すっぽ抜けます。
米国製品ですしもしかして忌々しいinchなのでしょうか？
ちょっと検索すると、ネジ穴がバカだとかそういう記述もありましたが、リンク切れしており詳しくは調べられませんでした。

**Comment by yasuohayashibara** [comment]
depthが3mmしかありませんので，気をつけて下さい．
ピッチが0.5mmですので，最大6回転です．
もしM3でスッポ抜けるようであれば，既にネジ溝が無くなっているかもしれません．

https://www.intelrealsense.com/wp-content/uploads/2019/09/Intel_RealSense_Tracking_Camera_Datasheet_Rev004_release.pdf?_ga=2.43419244.81405386.1598579520-1878591359.1598579520

**Comment by NaokiSato102** [comment]
ともすればすでにネジ穴は死んでおられますね。両面テープ接続に移行しようと思います。強力な両面テープはありますでしょうか？なければ私物がちょうどよいのがありますのでそれを使います。

**Comment by yasuohayashibara** [comment]
T265を使用する方が回答お願いします．

**Comment by NaokiSato102** [comment]
ミーティングにより両面テープによる固定が承認された。
両面テープ固定による問題が発生した場合、ハードウェア的固定方法を備えた治具を設計する。
強力両面テープは研究室になかったので私物を使う。

固定完了次第、試験運用を行う。
私はジョイスティック操作の方法はうろおぼえながら知っているが、センサ周りの使用方法はわからないので教えていただきたい。

**Comment by NaokiSato102** [comment]
私物協力両面テープにより固定の後、適当なアルファフレームへのねじ止めを行った。

- 両面テープによる固定の様子
![IMG_20200917_134618](https://user-images.githubusercontent.com/27545766/93428992-600a7800-f8fb-11ea-9d2a-5c4974fbf8c1.png)
- 固定後のケーブルの様子
![IMG_20200917_134626](https://user-images.githubusercontent.com/27545766/93429144-a52eaa00-f8fb-11ea-81a0-5c45be984657.png)
![IMG_20200917_134633](https://user-images.githubusercontent.com/27545766/93429146-a65fd700-f8fb-11ea-853a-af6c1ec88146.png)
- ねじ止め後
![IMG_20200917_143058](https://user-images.githubusercontent.com/27545766/93429227-c68f9600-f8fb-11ea-99a3-e721ae58d229.png)
ネジのクリアランスが狭く、ケーブル接続後にネジを通すのは不可能である。ネジを通した後にケーブルを通し、ねじ止めをするのは可能。差し込み角度的にさせないのでザグリ穴でネジ頭を逃がしても後からネジを入れるのは不可能である。あと、固定ねじの系を今までM4と誤認していたが、M5であったと判明。よって固定用ネジ穴はΦ5.1へ拡張を行った。
![IMG_20200917_143109](https://user-images.githubusercontent.com/27545766/93429597-5df4e900-f8fc-11ea-9c10-a291f13e47ae.png)
![IMG_20200917_143116](https://user-images.githubusercontent.com/27545766/93429601-5fbeac80-f8fc-11ea-8251-54a13ef80a77.png)

ネジ穴の系の反映をして、来週のミーティングで確認の後このissueは閉じたいと思う。動作試験は要りますか？

**Comment by NaokiSato102** [comment]
3Dモデルへのネジ系の反映とついでにザグリ穴追加をおこなったv3のアップロードを行った。
