### ISSUE TITLE
VTCで地図用のbagファイル取得

### ISSUE THREAD

**Issue by tiger0421** [open-rdc/orne_navigation#476]

**Comment by Souya25** [comment]
## 動作環境
シミュレータ側
OS Windows10 バージョン2004
メモリ 32GB
CPU Intel Core i7-8700

ROS側
OS Ubuntu18.04
メモリ 16GB
CPU Intel Core i5-6300U

## 手順
キーボードを使ってロボットの速度指令を送るパッケージを使って
https://github.com/Souya25/vtc_robo_teleop

以下のルートで地図作成用のbagファイルを取得しました
![image](https://user-images.githubusercontent.com/55970079/86490941-20c09680-bda4-11ea-874d-37a923a64cde.png)

## Bagファイル
https://chibakoudai-my.sharepoint.com/:f:/g/personal/s18c1137fp_s_chibakoudai_jp/EjrabR33MW5EqpHUvVlanMkBzjrJ_b2yH-vk9x4HxRu1TQ?e=qC9lHf

**Comment by ryuichiueda** [comment]
zipファイルになってますけど、bagファイルって最初から圧縮して記録したり、あとから圧縮したりできます。そうすると圧縮したままrosbagに読み込めます。

↓ご参考にどうぞ。

https://myenigma.hatenablog.com/entry/2016/05/14/170742

**Comment by ryuichiueda** [comment]
あれ、zipファイル、空になってます？

**Comment by Souya25** [comment]
bagファイルを圧縮してもう一度アップロードしました
https://chibakoudai-my.sharepoint.com/:f:/g/personal/s18c1137fp_s_chibakoudai_jp/EjrabR33MW5EqpHUvVlanMkBzjrJ_b2yH-vk9x4HxRu1TQ?e=lLU6kM

**Comment by tiger0421** [comment]
ファイルが見当たりません
![image](https://user-images.githubusercontent.com/20837922/86719882-72e11080-c05f-11ea-9cc8-0234f8fc9ccc.png)

**Comment by Souya25** [comment]
![image](https://user-images.githubusercontent.com/55970079/86728138-1eda2a00-c067-11ea-9a9d-197bd6636eb5.png)
これでいけますか
https://chibakoudai-my.sharepoint.com/:f:/g/personal/s18c1137fp_s_chibakoudai_jp/EjrabR33MW5EqpHUvVlanMkBBw64_t05x77aKmE1iW2P1A?e=I6L0fX

**Comment by tiger0421** [comment]
zipは容量が0byteだったので未確認ですが，.bagの方は開けました．
![Screenshot from 2020-07-07 16-25-34](https://user-images.githubusercontent.com/20837922/86736632-a4ada380-c06e-11ea-8757-0b0251aa6a65.png)

**Comment by Souya25** [comment]
bagファイルの取得と共有ができたのでクローズします

**Comment by uhobeike** [comment]
新たに取り直した
vtcのrosbagデータ(rosbag compressで圧縮済み)

https://1drv.ms/u/s!AomkMtsKOUnSglil7jAdiySMr_cq?e=LnztZM
