### ISSUE TITLE
VTCの地図の作成

### ISSUE THREAD

**Issue by tiger0421** [open-rdc/orne_navigation#477]

**Comment by uhobeike** [comment]
https://cit-outdoor-mr.slack.com/archives/C014CUG1LQ7/p1595826115010300

**Comment by uhobeike** [comment]
LIO-SAMの使用を検討したがうまくできていない

**Comment by uhobeike** [comment]
https://i.gyazo.com/17dfdc8abb5736c8f4088e426c59667e.png
動かせることを確認。
うまくは動作できていない。(オドメトリ関連のトピックの問題？)

**Comment by taishiyamamoto** [comment]
ここにパラメータを調整するファイルがあるので，シミュレーター環境に合わせれば正常に動作するかもしれないです．
https://github.com/TixiaoShan/LIO-SAM/blob/master/config/params.yaml

恐らくTopicsとExtrinsicsを書き換える必要があると思います．

**Comment by tiger0421** [comment]
LeGO-LOAMを用いて地図を作成したのでClose
https://github.com/tiger0421/Tsukuba_MAP

なお，LIO-SAMは引き続き #491
