### ISSUE TITLE
VTCで自己位置推定用のbagファイル取得

### ISSUE THREAD

**Issue by tiger0421** [open-rdc/orne_navigation#478]

**Comment by piropann** [comment]
# 動作環境
シミュレータ側
ノートパソコン
OS Windows10 Homeバージョン2004
メモリ 16GB
CPU Intel Core i7-7500

ROS側
ノートパソコン
OS Ubuntu18.04
メモリ 8GB
CPU Ryzen5-3500

# 手順
以下のルートでbagファイルをとった
青色の点までbagファイルをとる予定だったが通信がいきなり切れたため、赤色の点までのbagファイルをとった。
![image0](https://user-images.githubusercontent.com/55969921/87251284-66b4e300-c4a5-11ea-8917-e348c0ddd8df.jpg)

## bagファイル
https://chibakoudai-my.sharepoint.com/:f:/g/personal/s18c1043ha_s_chibakoudai_jp/Egu3kjUqdYJIlhXkBbvNsS4BD_Ti66ND762yJtovW_nf7g?e=3ghyPp

**Comment by piropann** [comment]
bagファイルを取りましたので閉めます。
今後は #479 で行います。
