### ISSUE TITLE
IMUのインタフェースボードの接触不良問題

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#48]
機体に取り付けられていない方のIMU（No.1）から受信した文字列がすべて0になるという問題が発生した。
IMU本体とインタフェース基板の接続部分を指で押さえつけると正常に通信できることから接触不良が疑われる。

**Comment by Nasupl** [comment]
ピンソケットのはんだづけをリワークして修正しました。No.1のIMUは現在MegaRoverに取り付けてしようされています。
