### ISSUE TITLE
VTCでWay Pointを配置して自律移動

### ISSUE THREAD

**Issue by tiger0421** [open-rdc/orne_navigation#480]

**Comment by uhobeike** [comment]
ナビゲーションができるか、やってみたところ以下のようなエラーが出た。
これが原因で、ナビゲーションが出来ていないのかと疑っているのだが、ネットで調べた
解決策でどうにもならず困っている。(move_baseの2Dcost_mapのエラー)

ネットで調べたこと(やったけどダメだった)
時刻同期が原因。
global_costmap_params.yaml とloacal_costmap_params.yamlのtransform_toleranceをいじる必要がある。

https://i.gyazo.com/d1082969f637b69eae17d5eb772ce063.png

**Comment by uhobeike** [comment]
現在の状況としては、以下のような感じ

https://www.youtube.com/watch?v=bzm8oVrMmSo&feature=youtu.be

**Comment by yasuohayashibara** [comment]
詳しくは無いので，あくまでも仮説ですが，global_poseを受け取れていないかもしれません．
rqt_graphを使用してorne_navigationと比較すると何か分かるかもしれません．
また，rqt_bagでタイムスタンプを確認すると何か分かりそうな気がします．

**Comment by uhobeike** [comment]
今後の予定がわからず、やる予定はないので、とりあえずクローズ。
