### ISSUE TITLE
自律走行の速度を常に上げた際の動作検証

### ISSUE THREAD

**Issue by taishiyamamoto** [open-rdc/orne_navigation#481]
#468 で自律走行の速度を常に上げるといった案が出たため，その検証を行う．

自律走行に特に支障が出なければ，限られた時間での実験走行のテスト回数が増える，横断歩道を制限時間内に渡れるとったメリットがある．

そのため，本issueでは自律走行の速度を上げて屋内環境で簡易的な実験を行い動作検証を行う．
特に問題が発生しなければ，最高速度のパラメータを変更したプルリクを送りマージされたらissueを閉じる．

**Comment by taishiyamamoto** [comment]
7月2日に行った実験動画です．
https://youtu.be/x5QqLSNhj-A

**Comment by yasuohayashibara** [comment]
経路生成は Carrot Planner ?

**Comment by taishiyamamoto** [comment]
Carrot Plannerです．

**Comment by taishiyamamoto** [comment]
パラメータを変更したブランチをプッシュしてプルリクがマージされたら閉じる．

**Comment by taishiyamamoto** [comment]
マージしたので閉じます。
