### ISSUE TITLE
orne_αの故障箇所のチェック

### ISSUE THREAD

**Issue by taishiyamamoto** [open-rdc/orne_navigation#482]
#461 の回路の故障が原因でorne_αが動かなくなった．

本issueではorne_αの回路とモーターの動作テストを行い，故障箇所をチェックする．

**Comment by taishiyamamoto** [comment]
故障している可能性のある部品のリストをチェックボックスにします．調査が終わった箇所は部品の状態を記載してください．

- [ ] モータードライバ http://t-frog.com/products/motor_driver/

- [x] 電源基板 http://t-frog.com/products/power_supply/

- [ ] リレー回路 https://github.com/open-rdc/orne_navigation/files/3929867/orne_a_PowerToMotor.pdf

- [ ] モーター http://t-frog.com/products/motor/

他にチェック項目があれば追加してください．

**Comment by taishiyamamoto** [comment]
モータードライバの動作テストの動画です．
https://youtu.be/ITeTRMZMI-I

ジョイスティックコントローラーで速度指令を送っているにも関わらず，モーターの挙動に異常があることがわかります．

**Comment by taishiyamamoto** [comment]
#201 でORNEで主に発生する故障に関して夏迫さんと渡辺先生で議論したものがあったのでリンクを添付します．
http://t-frog.com/forums/forum.php?ml=tf-2md3-devel&read=183

**Comment by taishiyamamoto** [comment]
wikiの故障診断に沿ってORNE-αの電源基板の導通チェックを行いました．
結果を以下にまとめます．

- LEDのLED201は点灯していません．

- LCフィルタ用のL200のインダクタが導通していませんでした．

- F200(5V用フューズ),F201(12V用フューズ),F202(TopURG用フューズ)は導通しています．負荷をかけた実験は行っていません．

- ダイオードのD200,D201,D202は順方向には導通し，逆方向には導通しないことを確認しました．

ちなみに電源基板から発煙したORNE-γのL200は導通していました．

**Comment by ryuseiotsuka** [comment]
電源回路の故障診断のページにL200が故障している場合交換するとありますが、部品の型番の記載がどこにあるかわかりますか？

**Comment by ryuseiotsuka** [comment]
辻電子に回路図を公開してもらえるよう連絡する

**Comment by ryuseiotsuka** [comment]
回路の故障を直すため、モータと電源回路、モータードライバの3点をまとめて修理に出す

**Comment by yasuohayashibara** [comment]
@ryuseiotsuka のコメントにあるように，リソースを割くことが難しい状況ですので，メーカーに修理を依頼することにしました．
現在，ORNE-α，γの部品（電源，モータドライバ，モータ）は梱包済みです．

@ryuseiotsuka @taishiyamamoto 
故障の経緯を書いたドキュメントを作成して下さい．
（ツジ電子の方が読んで，経緯が分かるようにお願いします．）

ドキュメントを頂いたら，修理に出します．
修理には１～２ヶ月かかりますので，できるだけ早めにいただけると助かります．
（前回のミーティングでORNE-β以外での急ぎの検証はないという認識ですが，困る場合はお知らせ下さい．）

**Comment by ryuseiotsuka** [comment]
@yasuohayashibara @taishiyamamoto 
ツジ電子に提出するドキュメントを作成しました。確認と訂正をお願いします。
文章の構成上ORNEα,γと見出しをつけているので相手方に提出する際には見出しだけ編集をお願いします。
https://docs.google.com/document/d/1AjmC1y1onf6eoffLD2XKztM6N9DdIiJnsf5vjxK8HlM/edit?usp=sharing

**Comment by yasuohayashibara** [comment]
明日，ミーティングですので，ミーティングで確認して修理に出したいと思います．

**Comment by ryuseiotsuka** [comment]
送付する文章の確認が終了したのでツジ電子に部品を送付して閉じます

**Comment by yasuohayashibara** [comment]
本日(7/29)，ツジ電子に２セット送りました．
