### ISSUE TITLE
電気回路周辺の故障に関する情報のまとめ

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne_navigation#484]
電気回路の問題が発生しているため，過去に起こった故障などをこのissueにまとめて，今後の対策の参考にする．

**Comment by yasuohayashibara** [comment]
- 電源基板　TF-PW36-5/12M
http://t-frog.com/products/power_supply/

- 故障診断のページ
https://github.com/open-rdc/orne_navigation/wiki/t_frog%E9%9B%BB%E6%BA%90%E5%9F%BA%E6%9D%BF_TF_PW36_5_12M_%E6%95%85%E9%9A%9C%E8%A8%BA%E6%96%AD

- 電源回路の問題
https://github.com/open-rdc/orne_navigation/issues/201
この後の議論が無い．解決しているかが不明．

- モータドライバ　TF-2MD3-R6
http://t-frog.com/products/motor_driver/

- 遮断回路の追加
https://github.com/open-rdc/orne_navigation/issues/356
想像していたより最近の話ですね．

- 故障診断のページ
https://github.com/open-rdc/orne_navigation/wiki/t_frog%E3%83%A2%E3%83%BC%E3%82%BF%E3%83%89%E3%83%A9%E3%82%A4%E3%83%90_TF_2MD3_R6_%E6%95%85%E9%9A%9C%E8%A8%BA%E6%96%AD

こちら読んだら手順が詳しく書いてある．この通りにすれば良さそうである．

**Comment by yasuohayashibara** [comment]
いきなり解決してしまった．

@ryuseiotsuka こちら確認したらissueを閉じて下さい．

**Comment by yasuohayashibara** [comment]
追加

- モータTF-M30-24-3500-G15L/R
一度故障して交換しています．

- 2016/12/13
巻線が損傷しており修理は不可能
損傷原因は、おそらく過電流

モータは今までほとんど故障していませんが，今回はショートさせていますので，故障のおそれがあります．

**Comment by ryuseiotsuka** [comment]
確認しました。

**Comment by taishiyamamoto** [comment]
#201 でORNEで主に発生する故障に関して夏迫さんと渡辺先生で議論したものがあったのでリンクを添付します．
http://t-frog.com/forums/forum.php?ml=tf-2md3-devel&read=183
