### ISSUE TITLE
fulanghua_navigationのビルドエラー

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne_navigation#486]
以下でビルドエラーが発生することが報告されている．
調査して，対処する．

https://github.com/open-rdc/fulanghua_navigation/issues/77

**Comment by taishiyamamoto** [comment]
一週間後に閉じる．

**Comment by taishiyamamoto** [comment]
一週間経過したのでcloseします．
何か返答があった場合,reopenする．
