### ISSUE TITLE
データセットの提供

### ISSUE THREAD

**Issue by taishiyamamoto** [open-rdc/orne_navigation#487]
つくばチャレンジ2020の活動内容の一つとしてつくばチャレンジに関連するデータセットの提供や利用をすることとなった．
https://tsukubachallenge.jp/2020/about/activities

具体的には以下のリポジトリにデータセットのリンクをプルリクすることになっている．
https://github.com/tsukubachallenge

**Comment by taishiyamamoto** [comment]
自分たちのサーバーにはつくばチャレンジの実験走行で2015年から2019年に取得したrosbagファイルがあります．
8月1日の説明会を聞き次第，運営に連絡するといった形になると思います．

どのようにしてデータを提供しましょうか．
5年分のbagファイルとなるのでかなりの容量になると思います．

**Comment by yasuohayashibara** [comment]
地図生成と自己位置推定に利用できそうな再利用性が高いものをコメント付きで提供するのが良いと思います．
webdavにアクセスしてもらうのも大変だと思いますので，google driveが良いでしょうか．

チームドライブというのが利用できそうです．
https://cloud-work.jp/productivity/google-apps/teamdrive/

**Comment by taishiyamamoto** [comment]
チームドライブ作成しました。
https://drive.google.com/drive/u/1/folders/0AMRk5ybblSDcUk9PVA

**Comment by tiger0421** [comment]
権限なくてブロックされたのですが，これは念のためにロックを掛けてるのでしょうか？
<img src='https://user-images.githubusercontent.com/20837922/89042072-53e54e00-d381-11ea-98ff-323d3dc9fbd9.png' width='500x300'>

**Comment by yasuohayashibara** [comment]
閲覧は誰でもできて，書き込みはチームメンバーしかできないという設定が良いと思います．

**Comment by taishiyamamoto** [comment]
データセットを提供する際のテンプレート
~~https://github.com/alexandrx/datasets/tree/alex-restruct-datasets~~

2020年8月10日追記
まだ検討中のようです．

**Comment by tiger0421** [comment]
自分のアカウントにforkしてREADMEに追記した
確認してもらい，問題がなければプルリクを送る
https://github.com/tiger0421/datasets#chiba-institute-of-technology-campus-in-tsudanuma-chiba

**Comment by tiger0421** [comment]
マージしていただいた
https://github.com/tsukubachallenge/datasets
