### ISSUE TITLE
LIO-SAMを使うために変更するパラメータ

### ISSUE THREAD

**Issue by tiger0421** [open-rdc/orne_navigation#491]
LIO-SAMを使うために変更する必要のあるパラメータを調査する

**Comment by uhobeike** [comment]
現状報告
https://i.gyazo.com/dee2d50bf0e3313c8c88a7d82fd25e65.png
以前変わらず、このエラーが出てしまう

**Comment by uhobeike** [comment]
現状の動作
https://drive.google.com/file/d/1xSx4IhFbXckbVpZ_TAh3Hv15Dxka2aNi/view?usp=sharing

**Comment by uhobeike** [comment]
velodyneのポイントクラウドデータがLIO-SAMの方に上記のエラーが原因で
渡せてないため、mapのフレームが発行されてないと考えている。

**Comment by uhobeike** [comment]
windowsとubuntuの時刻同期を行ったところ、出来た。

**Comment by uhobeike** [comment]
以下のサイトに方法と結果をまとめた。
https://beike.hatenablog.jp/entry/LIO-SAM/VTC

**Comment by uhobeike** [comment]
生成された、PCDデータ
https://youtu.be/xLB_UF2BNso

**Comment by tiger0421** [comment]
めちゃくちゃ細かいけどはてなブログの③時刻同期で1行目がwindosになってるのが気になった

**Comment by uhobeike** [comment]
指摘ありがとうございます。修正しました。

**Comment by uhobeike** [comment]
以下、まとめ終えたブログ

https://beike-re.hatenablog.com/entry/VTC/LIO-SAM/3d-mapping?_ga=2.177404837.1219929223.1598519329-703849559.1590685405

**Comment by uhobeike** [comment]
vtcのrosbagデータ(rosbag compressで圧縮済み)

https://1drv.ms/u/s!AomkMtsKOUnSglil7jAdiySMr_cq?e=LnztZM

**Comment by uhobeike** [comment]
作成したマップ（マージ済み）
https://drive.google.com/file/d/1Uwfp-8_bIER2_R1xI82eJ2LVPm_ymu9h/view?usp=sharing
