### ISSUE TITLE
IMUの積分ドリフトが激しい

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#50]
IMUの積分ドリフトが激しく使い物になりません。
Auton版のIMU基板のソースコードをビルドして書き込みましたが、相変わらず10分に20度近くドリフトします。

**Comment by DaikiMaekawa** [comment]
@Nasupl 二度手間になるのはイヤですが最新版のソースが手に入らない以上、ドリフト補償に関して再度実装し直す必要があると思います。

**Comment by Nasupl** [comment]
検証の際にキャリブレーションを行わずに動かしていたのが原因のようで、Auton版のソースコードをビルドして書き込んだものを利用して、キャリブレーションして検証したところ、10分で2度までドリフトは収まりました。

**Comment by Nasupl** [comment]
最終的にはRobocupのレポジトリに上がっているIMUのソースコードのキャリブレーションがうまく働いていなかったということになるかと思います。
