### ISSUE TITLE
Orne-γにて当方のPCがUTM-30LX、T-flogドライバを認識しなかった。

### ISSUE THREAD

**Issue by NaokiSato102** [open-rdc/orne_navigation#502]
まず、以下のコマンド類を実行する前に試してだめだった。 これは当然。実行する必要がある事を失念していた。
rosrun orne_setup create_robot_params
rosrun orne_setup create_udev_rules

次に、実行後に試したが動かなかった。
UTM-30LXの動作音が電源を入れてもしないので配線を疑ったところ、
なぜかコネクタが外れていた。自然にとれた？

ケーブルを直したところ、ガレリアでは正常動作。当方のPCでは動かないまま。

理由はいくつか考えられる。

- セットアップ不完全
一番有力。完全なセットアップができていない可能性がある。
コマンドの実行洩れがある恐れがある。中途半端に実行されたコマンドの影響を除く手段を教えてほしい。
catkin_wsでcatkin cleanを実行するだけで問題ないか？

- multi_view_imageを構成するアプリケーションとの干渉

- USB周りの不調

対処について情報をいただきたい。

**Comment by tiger0421** [comment]
よくわかりませんが，まずはusbが認識されているかどうか確認してください
`
$ ls /dev
`
とかの情報がないとわからないです

**Comment by NaokiSato102** [comment]
とりあえずlsusbには載っていませんでした。正常時の挙動を覚えてないのでそもそも載るものかは知りませんが。

**Comment by taishiyamamoto** [comment]
ドキュメントを更新しました．
よろしければ参考にしてください．
https://github.com/open-rdc/orne_navigation/wiki/ORNE環境動作の手順

**Comment by tiger0421** [comment]
lsusbで出ないなら認識してないです

**Comment by NaokiSato102** [comment]
対処はどうしましょうか

**Comment by tiger0421** [comment]
usbハブを繋がずに接続してみてください

**Comment by NaokiSato102** [comment]
失礼ながら書き忘れていましたが直刺しでもダメでした。
