### ISSUE TITLE
orne_navigation内branch及びファイル整理(γ)

### ISSUE THREAD

**Issue by haruyama8940** [open-rdc/orne_navigation#503]
brunchが混沌とし、また切り替えたbrunch内に明らかに不要なファイルが存在している

**Comment by uhobeike** [comment]
コメントはそれで問題ないけど、issue名は、「orne_navigation内brunchの整理（γ）」で良いかも

**Comment by haruyama8940** [comment]
ありがとうございます。修正しました。

**Comment by taishiyamamoto** [comment]
自分が関わっている中で不要なブランチは消しました。

**Comment by yasuohayashibara** [comment]
以下，整理の第一弾です．
gazeboで動作することは確認しています．
（自律移動のところでウェイポイント上で停止する様子が見られますので，何か問題がありそうですが．）
- orne_navigation (環境構築手順の簡略化)
https://github.com/open-rdc/orne_navigation/tree/brushup
- ypspur (ビルドの問題を解決)
https://github.com/open-rdc/ypspur
- icart_mini
https://github.com/open-rdc/icart/tree/brushup
通常の環境構築をするとmelodic-develが選択されるが，現在は一時的に上記のブランチに切り替える．

**Comment by yasuohayashibara** [comment]
kinetic-develに関しても整理しました．
- orne_navigation (環境構築手順の簡略化)
https://github.com/open-rdc/orne_navigation/tree/develop/kinetic-devel
- icart_mini (ビルドの問題を解決)
https://github.com/open-rdc/icart/tree/develop/kinetic-devel

**Comment by yasuohayashibara** [comment]
次に，しばらく変更がなくて，これから利用することがなさそうなbranchを整理します．
これらのbranchに関わっている方はマージするか，削除していただければと思います．

https://github.com/open-rdc/icart/branches/stale
https://github.com/open-rdc/orne_navigation/branches/stale

あと，こちらも不要だと思いますので，チュートリアルで使用しそうなもの以外は削除する予定です．
https://github.com/open-rdc/orne_navigation/tree/kinetic-devel/orne_navigation_executor/waypoints_cfg

**Comment by yasuohayashibara** [comment]
とりあえず一段落しました．
ただし，チェックの範囲はREADMEのインストールと操作の部分のみです．
3Dに関しては検証していません．

@uhobeike 先走ってしまいましたが，何かありましたら追加でお願いします．
