### ISSUE TITLE
orne-gammaの故障に関して

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne_navigation#527]
orne-gammaが故障中ですが，もしかしたら他のロボットにも影響を与えるかもしれませんので，共有しておきます．

林原が知る限りの状況は以下のとおりです．
１）orne-gammaのPCのUSBハブを外したところ，ハブのGNDがバッテリに接触してショート
２）USBハブにはURGとモータドライバが接続されていた．
３）URGとモータドライバは電源が入らない．
４）これをorne-alphaの電源で確認
５）インタラクティブ用のロボットのURGとモータドライバを取り外してorne-gammaに取り付けるところ．

その他の作業は林原は把握していません．
（自由に追加していただいて構いません．）

**Comment by yasuohayashibara** [comment]
３台間で部品を入れ替えながら動作チェックしたようですが，URGの電源が『ショートモード』で故障していましたので，それを接続して電源を入れた部品はすべて故障しているおそれがありあます．

ということで，この３台に関しては電気回路をよく理解する人が一通りチェックしてから動かすようにしてください．
電気回路のチェックと報告がなされるまで，この３台（orne-gamma, alpha, インタラクション）は『使用禁止』とします．

中途半端に動かすと，URGも含めて３台の部品が全て壊れるかもしれず，取り返しのつかないことになります．
電気回路のチェックは安定化電源を使用して，一つ一つ丁寧に行ってください．

電気回路の得意な人はできるだけご協力いただければと思います．

[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/ev860pvjnYA/0.jpg)](https://youtu.be/ev860pvjnYA)

**Comment by yasuohayashibara** [comment]
先輩が電源回路のチェック方法を残していた．

https://github.com/open-rdc/orne_navigation/wiki/t_frog%E9%9B%BB%E6%BA%90%E5%9F%BA%E6%9D%BF_TF_PW36_5_12M_%E6%95%85%E9%9A%9C%E8%A8%BA%E6%96%AD

**Comment by yasuohayashibara** [comment]
どうして林原が使用禁止という措置に出たのかピンと来ない人もいると思いますので，もう少し詳しく書きます．

以下，今回使用している電源基板 TF-PW36-5/12Mです．
https://t-frog.com/products/power_supply/

回路は24Vを入力して，5Vと12Vを出力します．
12Vの定格は『1A』です．

こちら過去に調査したことがありますが，瞬間的にでも1Aを超えると故障します．
あまりに耐圧が低いため，自作したこともあります．
https://github.com/open-rdc/orne_navigation/issues/381

そこで，今回電源回路に流れたかもしれない電流ですが，上の動画の値を参考に計算すると，以下となります．

0.59A * 12V/0.67V = 10.6A

**1A**の定格に対して，**10A以上**が流れたおそれがあります．
一定の抵抗値という前提で計算したもので，おそらくはこれほど流れていないと思いますが，それでも数倍の電流が流れたと思われます．

ということで，

１）**このURGをつないだ電源は，ある一定の確率で電子回路が故障している**と思います．

次に，この電源回路は24Vを12Vに変換する回路ですが，故障により電流が流れなくなるということであれば，この部品だけ交換すれば良いという話になります．
しかし，電流を多く流したときに例えば24Vがそのまま出力されますというような故障をしていると，

２）**URGを含めた周辺回路も故障する**ことになります．
　　（PCも故障するおそれがあります．）

特にURGの故障は早くても2ヶ月，ときには修理不能のときがありますので，ロボット開発が頓挫するおそれがあります．

現時点の対策としては，以下になると思います．

１）安定化電源で電流を最小に絞って，
２）上記のドキュメントに基づいて電源回路のチェックをする
３）特にプログラマブル抵抗器があるので，それを使用して電流を流したときの挙動を観察する
４）１つ１つ部品を追加して挙動を確認する

間違ってもバッテリを使用しないでください．
全ての回路を再起不可能な状態まで壊すおそれがあります．

**Comment by taishiyamamoto** [comment]
ORNE-α，ORNE-γ，インタラクションロボットに搭載されている基板の動作実験を行いました．

## 電源基板の動作実験
安定化電源とオシロスコープとプログラマブル抵抗を用いて**電源基板 TF-PW36-5/12M**の動作テストを行いました．
定格はそれぞれ以下のように定めて実験を行いました．

![IMG_9408](https://user-images.githubusercontent.com/25315656/130927153-d2870131-b64d-41c0-8e32-65b2311cd2be.png)


- 安定化電源
  - 定格電圧：24V
  - 定格電流：700mA
- オシロスコープ
  - 縦軸（電圧スケール）：5.00V
  - 横軸（時間スケール）：5.00ns
- プログラマブル抵抗
  - 抵抗：17Ω
    - （LiDARの消費電流は最大で700mA以下と[製品概要](https://www.hokuyo-aut.co.jp/search/single.php?serial=21#outline)に記載されているのでオームの法則から12V / 0.7A = 17.1428Ωに設定）

実験した電源基板はORNE-α，ORNE-γ，インタラクションロボット，に搭載されている電源基板です．

実験結果はそれぞれ以下のようになりました．

- ORNE-α
  - プログラマブル抵抗で7.64wが出ていることを確認
  - オシロスコープでスパイクノイズが発生していないことを確認 
  - [実験の様子](https://youtu.be/i1BHrWnPmNg) 
- ORNE-γ
  - ORNE-αと同様な出力が出ていることを確認
  - オシロスコープでスパイクノイズが発生していないことを確認
  - [実験の様子](https://youtu.be/smF6rHifh48) 
- インタラクションロボット
  - プログラマブル抵抗で7.67wが出ていることを確認
  - オシロスコープでスパイクノイズが発生していないことを確認
  - [実験の様子](https://youtu.be/Qyu8ySvBd5o) 

## 安定化電源を用いたモータードライバとLiDARの動作チェック
電源基板が安定化電源上で動作することを確認したので，
- 安定化電源
  - 電源基板
    - LiDAR
    - モータードライバ  　のように繋いで動作チェックをしました．

実験対象はORNE-αに搭載されているモータードライバとLiDAR，インタラクションロボットに搭載されているモータードライバとLiDARです．(ORNE-γに搭載されているモータードライバとLiDARはすでに故障していることを確認したので実験していません．)

安定化電源の定格は前の実験条件と同じ定格にしました．

実験結果はそれぞれ以下のようになりました．

2D LiDAR(UTM-30LX)の動作テスト
- ORNE-αのLiDAR
  - rostopic echo /scan で値が出力されていることを確認
- インタラクションロボットのLiDAR
  - rostopic echo /scan で値が出力されていることを確認

モータードライバの動作テスト
 - ORNE-αのモータードライバ
   - LEDのランプが光ることを確認
- インタラクションロボットのモータードライバ
  - LEDのランプが光ることを確認

LiDAR+モータードライバの動作テスト
- ORNE-α
  - rostopic echo /scan で値が出力されていることを確認
  - roslaunch icart_mini_driver teleop_joy.launchでモーターを操作できることを確認
- インタラクションロボット
  - rostopic echo /scan で値が出力されていることを確認
  - roslaunch icart_mini_driver teleop_joy.launchでモーターを操作できることを確認

## 24Vバッテリーを用いた動作テスト
安定化電源上で電源基板，モータードライバ，LiDARが動作することを確認したので，通常通りにバッテリーを電源にして動作確認する．

実験結果はそれぞれ以下のようになりました．

- ORNE-α
  - rostopic echo /scan で値が出力されていることを確認
  - roslaunch icart_mini_driver teleop_joy.launchでモーターを操作できることを確認
- インタラクションロボット
  - rostopic echo /scan で値が出力されていることを確認
  - roslaunch icart_mini_driver teleop_joy.launchでモーターを操作できることを確認

**Comment by taishiyamamoto** [comment]
インタラクションロボットよりもORNE-γの方が使用頻度が高いので，故障したLiDARとモータードライバを付け替えた．

**Comment by taishiyamamoto** [comment]
結論として現在，ORNE-αとORNE-γは問題なく動作することを確認しました．
今後は再発を防ぐために配線処理を行うことを検討します．

**Comment by yasuohayashibara** [comment]
お疲れさまでした．

【みなさま】
以後，問題が発生したときにはこちらのissueを参考にしながら，安定化電源とプログラマブル抵抗を使用して回路をチェックしていただければと思います．

インタラクション用のロボットは現在利用できませんが，orne-α，γは利用していただいて構いません．
情報を共有したらissueを閉じます．
