### ISSUE TITLE
経路の追従性能を向上させる

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#53]
直線コースであっても路面が凸凹だと安定して走行することが出来ずコースアウトすることが多い
また、障害物を回避するための経路もうまく追従出来ない場合があるので修正する必要がある。

**Comment by DaikiMaekawa** [comment]
https://github.com/open-rdc/icart_mini_ros_pkgs/issues/41 でIMUのデータの取りこぼしを少なくするために通信周期を20Hzにしたため、旋回後の機体の振幅がなかなか収束しない問題が発生していた。
走行実験を重ねた結果、自律走行には少なくともIMUからの姿勢データを30Hzで更新する必要があることがわかったため再度修正を加えた。 https://github.com/open-rdc/adis_imu_drivers/pull/12
修正後に実機で動作確認を行い、問題が改善されていることを確認した。

**Comment by DaikiMaekawa** [comment]
自律走行時の最大速度を0.55m/sまで下げた。
また、経路を外れにくくするためにNavigationの制御周期を5Hzに引き上げた。 https://github.com/open-rdc/icart_mini_navigation/pull/36
PCの性能以上に周期を早めすぎるとエラーが頻発するようになるため、5Hzという値は最もパフォーマンスが上がるものを実験的に求めた結果である。

**Comment by DaikiMaekawa** [comment]
ypspur側に左右同じ速度の指令を与えてロボットを前進させた場合にも必ず左側に軌道が逸れていく現象が確認されていました。 T-frog Driverにシリアルで送っている指令値は左右のモータで速度の違いがないことは確認できているのでドライバ側の制御関連でなんらかの問題が発生している可能性も考えられます。
Navigationの速度を抑えてもあまり効果が見られなかったのですがypspur側の設定で最大速度を低めに設定すると直進性が改善されました。 https://github.com/open-rdc/icart_mini_core/pull/29/files

**Comment by DaikiMaekawa** [comment]
> ypspur側に左右同じ速度の指令を与えてロボットを前進させた場合にも必ず左側に軌道が逸れていく現象が確認されていました。

この問題は凸凹の路面ではより顕著になっていたため、修正後の動作を同様の環境で再度検証する必要があります。

**Comment by DaikiMaekawa** [comment]
> ypspur側に左右同じ速度の指令を与えてロボットを前進させた場合にも必ず左側に軌道が逸れていく現象が確認されていました。 T-frog Driverにシリアルで送っている指令値は左右のモータで速度の違いがないことは確認できているのでドライバ側の制御関連でなんらかの問題が発生している可能性も考えられます。

モータを左右入れ替えても同じ挙動を示すためT-frog Driverの問題です。

**Comment by DaikiMaekawa** [comment]
i-Cart mini用に配布されているパラメータでは最大速度が0.9m/sになっていますが、0.6m/s程から直進性が失われる現象に悩まされてきましたがようやく解決しました。（凸凹な路面は低速でも発生するのでコースアウトに繋がっていた）
モータに対してどのような制御が行われているのかを明らかにするためにYPSpurのソースコードを解析した結果、モータのトルクの設定が足りない場合に右側のモータの出力が大きくなる計算になっていることが判明しました。
そこで、YPSpur側のトルクの制限を上げてみたところ0.6m/s以上の走行、凸凹の路面や坂等のトルクが必要な場面での直進性が改善されることを実機で確認しました。
こちらのハードウェアトラブル出ないことは確認済みなので、公式で配布されているパラメータファイルをそのまま使用してもi-Cart miniはまっすぐには走らないということになります。（平地且つ低速では可能ですが．．．）

**Comment by DaikiMaekawa** [comment]
バッテリーの残量が低下することにより0.4m/sでの走行時でも左側に逸れていく挙動が確認された。 
ジョイスティック等で検証した場合でも同様の挙動であるためナビゲーション側の原因である可能性は排除している。

**Comment by Nasupl** [comment]
この問題はモータドライバのPIDゲインが原因であり，発振寸前にピーキーな状態までチューニングしたが改善されることはなかったため閉じる．
