### ISSUE TITLE
DWAを用いた際に振動する問題の知見

### ISSUE THREAD

**Issue by haruyama8940** [open-rdc/orne_navigation#532]
つくば2022において，ローカルプランナーにDWAを用いた場合において，つくば市庁舎や公園付近で振動（左右に触れる）する
問題について議論，対策を行う．
まとまり次第追記

**Comment by yasuohayashibara** [comment]
後で見る方のためにも動画を載せてくれると助かります．

**Comment by haruyama8940** [comment]
https://photos.app.goo.gl/TMgd4LfSND5HTev39
症状としてはこちらです．
global_plan関連で問題がありました．
地図の解像度が高く，プランニングに時間を要することが，local_planにも影響を及ぼしている可能性があります．
これにより，local_planが再計算されず，前回の結果が残り続けることで，左右に揺れていたと考えられます．

対策として
・global_plannerの経路生成にはダイクストラ法よりも軽量なA*を用いる．
・地図の解像度を下げる．
これにより問題となっていた挙動は解消されました．

**Comment by haruyama8940** [comment]
解決したため，一旦issueを閉じます．
