### ISSUE TITLE
ORNE-αの電装系組み直し

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#69]
電圧計周辺の配線や12V供給系の見直しなどを行うべき

**Comment by Nasupl** [comment]
少なくとも都産技デモまでにきれいにまとめる

**Comment by Nasupl** [comment]
電圧計周辺配線の修正と配線の把捉を実施．

**Comment by Nasupl** [comment]
12V系は再度組み直し

**Comment by ShotaroTerato** [comment]
こちらのタスクは終了したでしょうか

**Comment by Nasupl** [comment]
回路の構成は整った．3DURGに使うZHコネクタのハウジングの在庫が切れてしまったので買いに行って付け替えれば完了．

**Comment by DaikiMaekawa** [comment]
@Nasupl 多分これは終わってるよね。 閉じても良いですか?

**Comment by Nasupl** [comment]
OKです．閉じます．
