### ISSUE TITLE
電源ポートが不足している

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#7]
iCart miniの電源基板には12Vのポートが1口しかないので、サーボとURGを同時に動かすには電源ポートが足りません。増設するか分配する必要があります。

**Comment by Nasupl** [comment]
サーボに電源を供給する基板も確保したので、サーボだけLi-Poなどで動かすのが手っ取り早そうです

**Comment by DaikiMaekawa** [comment]
@Nasupl 時間がないので差し当たり、その案で対処しましょう。

**Comment by Nasupl** [comment]
Li-Poを搭載するにあたり、4線用電源スイッチ付きハブのコネクタの形状変更が必要です

**Comment by DaikiMaekawa** [comment]
@Nasupl コネクタは入手しましたか？

**Comment by Nasupl** [comment]
入手しました

**Comment by Nasupl** [comment]
4千用電源スイッチ付ハブのコネクタの形状変更を完了しました
