### ISSUE TITLE
ORNE-βの電装系

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#70]
- ハーネス作成
- 電圧計

**Comment by Nasupl** [comment]
ハーネス作成完了

**Comment by Nasupl** [comment]
@yasuohayashibara 
昨年度RBB用（？）に購入していただいた小さい電圧計，まだ在庫ございますでしょうか．

**Comment by yasuohayashibara** [comment]
たくさん(10個ぐらい)購入した記憶がありますが，どこかは不明です．

**Comment by Nasupl** [comment]
モータドライバ/IMU/緊急停止スイッチを取り付けて配線までしたので，あとは電源基板を取り付ければ完了

**Comment by Nasupl** [comment]
電圧計以外はすべて配線完了．とりあえず都産技デモまではこのまま運用したい．

**Comment by Nasupl** [comment]
電圧計購入済み（？）

**Comment by Nasupl** [comment]
ThinkPadバッテリーを発注する

**Comment by yasuohayashibara** [comment]
検収した電圧計を夏迫くんの机の上に置きました．

**Comment by Nasupl** [comment]
電圧計の取付け完了
