### ISSUE TITLE
ORNE-β各種機器取付板の作成

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#71]
- 緊急停止スイッチ取付板
- IMU取付板

**Comment by Nasupl** [comment]
アルミの板をCNCでささーっと切削して作ってください．
データは申し訳ないけど残ってないです．

**Comment by Nasupl** [comment]
電源スイッチ用取付板もつくってください

**Comment by Nasupl** [comment]
電源スイッチ(サーキットプロテクタ)は #73 を参照してください．
[こちら](http://t-frog.com/forums/forum.php?ml=icart-mini-devel&read=6)の案２の形でよいかと思います．
IMUはAnalogDevicesのADIS16488です．
緊急停止スイッチについてはORNE-αの取付板を確認してください．

**Comment by Nasupl** [comment]
電源スイッチ取付板は見つかったので作らなくていいです。

**Comment by ShotaroTerato** [comment]
緊急停止スイッチ取り付け板ならびにIMU取り付け板の製作を行いました
orne-βの運用ノートの上に置いてあります
![image1](https://cloud.githubusercontent.com/assets/7301081/8104114/243fa2bc-1069-11e5-9169-ecd896593e9e.JPG)

**Comment by Nasupl** [comment]
@NDYun, @KentaKubota, @ShunShimamura 
すでに全て部品は揃っているので，取り付けまでお願いしたいです．

**Comment by Nasupl** [comment]
取り付けまで完了したので閉じます
