### ISSUE TITLE
ORNE-β用IMUの調達とファームウェア書き換え

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#72]
IMUを調達してつくば用ファームに書き換える

**Comment by Nasupl** [comment]
もう１台どっかについてるのでぶんどる

**Comment by Nasupl** [comment]
@yasuohayashibara 
AutonやRDC-10にはついていませんでした．先生のデスクの方を探していただきますでしょうか．

**Comment by yasuohayashibara** [comment]
見つけました．
夏迫くんの机の上に置いておきます．

**Comment by Nasupl** [comment]
調達とファームウェア書き換え完了
