### ISSUE TITLE
買い出し

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#73]
ミスミで買わなくていいものの買い出し
- M3のスプリングワッシャー
- 外装用ビニールシート
- 養生テープ
- 強力な両面テープ
- マジックテープ
- 白ガムテ

**Comment by Nasupl** [comment]
ビバホームまでバスやら自転車やらで行って買える量だと思うので誰か３年生おねがいします

**Comment by Nasupl** [comment]
- ４ポートのUSBハブ

ヤマダ電機で良さそうなのを1000円くらいで買ってきてください

**Comment by Nasupl** [comment]
- サーキットプロテクタ(http://www.sengoku.co.jp/mod/sgk_cart/detail.php?code=EEHD-4FKA)
- モータドライバ保護用キャパシタ(http://www.sengoku.co.jp/mod/sgk_cart/detail.php?code=EEHD-4D83)

どちらも千石．

**Comment by Nasupl** [comment]
サーキットプロテクタは見つかったので不要になりました

**Comment by ShotaroTerato** [comment]
・M5のスプリングワッシャー
・外装用ビニールシート
・養生テープ
・強力な両面テープ
・マジックテープ
・白ガムテ

以上のものは購入し検収に通しました

**Comment by Nasupl** [comment]
残りは4ポートハブだけ

**Comment by Nasupl** [comment]
ハブはAmazonで複数まとめて購入していただくように先生にお願いしたので閉じる
