### ISSUE TITLE
ORNE-β外装作成とαの外装修正

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#74]
ORNE-βもαと同様の外装を作成する．プラダンでよい．
αの上部構造は配線逃しのところでぐんにゃり曲がってしまっているので，β用外装はこれを改善した設計にすると共にαにもこれを適用する．

**Comment by Nasupl** [comment]
とりあえず @KentaKubota に投げてますが３年生で誰か担当という感じでおねがいします．

**Comment by elgure** [comment]
ORNE-βの外装完成しました.

**Comment by Nasupl** [comment]
ありがとうございました．
