### ISSUE TITLE
YPSpurパラメータ調整

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#79]
パラメータを調整してトルクがもうちょっと出るか探る

**Comment by ShotaroTerato** [comment]
orne_navigation(icart_mini_ros_pkg)/icart-mini.param
のTORQUE_LIMITを1.0[Nm]から1.5[Nm]に変更

・TORQUE_MAX　モータトルク制限
・TORQUE_LIMIT

**Comment by ShotaroTerato** [comment]
/orne_navigation(icart_mini_ros_pkg)/icart-mini.param
のTORQUE_LIMITを1.0[Nm]から1.5[Nm]に変更

なお
・TORQUE_MAX　モータトルク制限（PI制御ぶんの制限）
・TORQUE_LIMIT　モータトルク出力制限（最終的な出力制限）

**Comment by Nasupl** [comment]
実機で検証をおねがいします．

**Comment by Nasupl** [comment]
TORQUE_LIMITやTORQUE_MAXだけをいじっても変わらないのでPIDゲインの調整を行う．ダメだったら車輪径の変更も行う必要がある．

**Comment by ShotaroTerato** [comment]
GAIN_KPを120から180
GAIN_KIを300から450
に変更
動作を確認したところそれなりのトルクが出るようになった
