### ISSUE TITLE
緊急停止スイッチを取り付ける

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#8]
第三回試走会に向けて、緊急停止スイッチ等の安全装備を取り付ける必要があります。

**Comment by ximomoi** [comment]
緊急停止スイッチ本体の取り付けは完了．
@Nasupl 回路の取り付けお願いします．

**Comment by Nasupl** [comment]
写真の平型端子を入手する必要があります
![2014-09-14 18 46 29](https://cloud.githubusercontent.com/assets/7274407/4263627/85a5cddc-3bf4-11e4-8f66-45b89d194171.jpg)

**Comment by Nasupl** [comment]
平型端子を購入し、配線施工完了しましたので、このIssueは閉じます。
