### ISSUE TITLE
横断歩道対策

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#80]
- 追従どうする？
  など

**Comment by Hiroki-Goto** [comment]
今回出たこと

追従組
　・ROSの読み込み
　・スイッチ1つでモードチェンジ（？）←横断歩道とそれ以外のモード（？）←　座標値でモードチェンジ
　・横断歩道をどうわたるか（段差がきつい）

白線処理
自己位置でやるか？
waybpint　navigationでやるときついかも
地図にはセルごとに属性値と尤度は与えられるけどどうするか・・・
セルに情報入れると管理しずらい
地図とエリア情報を一括で管理する
これらは orne　navigationにパッケージしていく
FSM のパッケージにあるかも
目標値をロボットの少し後ろにしていれば障害物回避を回しながら追従行動できるかも

走行関係
モータのトルク関係？　
タイヤを大きくする？　←段差考えるとこっちかも
鬼畜どんぐり　←大きく浮かんだりする

**Comment by Nasupl** [comment]
追加・補足メモ（？）
- 横断歩道前や対象発見時のPathPlannningについて
  - 状態管理するノードを追加するべき
  - 一つのノード内でやる
  - 地図を分割する？
    - 地図内でエリアを分割する
    - orne_navigation内にパッケージを作るべき
  - ロボットの手前に目標を定めれば障害物回避しない
    - nav_goalをロボットの手前に設置してあげる

**Comment by ShunShimamura** [comment]
@Hiroki-Goto 状態管理関係
@Shiina-Shiotani  地図関係
@ShunShimamura 追従関係

**Comment by buzzshima** [comment]
座標値よりも地図を分割して状態を管理していったほうがいいかも
ただ今回は時間がないため座標値で状態を分割した方がいいかも
今回は地図と状態管理が必要
B3だと期限的厳しいため夏迫さんになげた

**Comment by buzzshima** [comment]
追従関係
waybpointナビゲーションするのは横断歩道の追従する地点までやる
横断歩道の区域に入ったら，障害物を認識次第それの少し前のところをゴールにしておく

**Comment by Nasupl** [comment]
#87 は完了
横断歩道関連では #104 が進行中

**Comment by Nasupl** [comment]
https://github.com/DaikiMaekawa/fulanghua_navigation の開発によって，横断歩道手前での一時停止は可能になった．今年度は信号機のある横断歩道に取り組むため一旦閉じる．
