### ISSUE TITLE
機体ごとのlaunchやparamの管理

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/orne_navigation#83]
マシンごとのlaunchファイルや各種パラメータの差異はlaunchファイルのif-unlessルールを使って管理し切り替えられるようにする
http://wiki.ros.org/ja/roslaunch/XML

**Comment by DaikiMaekawa** [comment]
加えて、icart_miniのリポジトリじゃなくて、orne_navigationのリポジトリに配置すること。 waypoints_cfgもこっちに持ってきていいと思いますよ。

**Comment by ShotaroTerato** [comment]
icart_miniのリポジトリの方にadd_hokuyo3dブランチを作成しました．

**Comment by DaikiMaekawa** [comment]
終わったらプルリクエストを投げること。 私がレビューします。

**Comment by ximomoi** [comment]
@DaikiMaekawa 
icart_miniリポジトリのselect_robotブランチでロボットの指定をできるようにしました、プルリクエストを送りましたのでレビューよろしくおねがいします。

**Comment by Nasupl** [comment]
- icart_mini_drive.launchにデバイス名が直に書いてある
  - if-unlessルールを利用して，指定したマシンのデバイス名が読み込まれるようにしてください
- icart_mini.paramにもマシンごとの差異が存在する
  - αとβそれぞれのパラメータを作成して，icart-mini.shに引数を与えてマシンを指定するとそれぞれのparamが読み込まれるようにする必要がある

**Comment by DaikiMaekawa** [comment]
icart_mini.paramもdebリリースするためにパッケージ化しました。 https://github.com/open-rdc/orne_navigation/tree/indigo-devel/orne_setup 

マシン毎のパラメータの違いはここを修正してください。

**Comment by ximomoi** [comment]
add_sensor_selectでロボットごとのデバイス名、
add selection paramでparamの指定をできるようにしました。
add_sensor_selectではα側のデバイス名が分からなかったので中身の同じlaunchファイルが存在しています、with_hokuyo3dファイルは @Nasupl 中身の変更をおねがいします。

**Comment by DaikiMaekawa** [comment]
https://github.com/open-rdc/orne_navigation/pull/94 にて対応した。 10/17日の試走会で動作確認をしてもらう。

**Comment by DaikiMaekawa** [comment]
masterにマージした。
