### ISSUE TITLE
起動時に3DURGが止まってしまうことがある

### ISSUE THREAD

**Issue by ShotaroTerato** [open-rdc/orne_navigation#85]
3DURGを起動した時に10数秒で3DURGが止まってしまうことがある

**Comment by Nasupl** [comment]
電源投入時以外発生しないのでとりあえずClose

**Comment by DaikiMaekawa** [comment]
GitHubのWikiに運用マニュアルとして載せておいた方が良い情報なのでは?

https://github.com/open-rdc/orne_navigation/wiki/%E9%81%8B%E7%94%A8%E3%83%9E%E3%83%8B%E3%83%A5%E3%82%A2%E3%83%AB

**Comment by Nasupl** [comment]
YVT-X002についての[運用ページ](https://github.com/open-rdc/orne_navigation/wiki/YVT-X002%E3%81%AE%E9%81%8B%E7%94%A8)を作成しました

**Comment by DaikiMaekawa** [comment]
フォーラムがあればフィードバックする
