### ISSUE TITLE
設計データ配布

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#86]
設計データ配布用のリポジトリを作成しました。

https://github.com/open-rdc/orne_icart_designs

@iou16 差し当たりアセンブリ後のstlファイルをアップしてください。 

GitHubはブラウザ上でstlを可視化する機能を持っています。 詳しくは以下を参照。
https://help.github.com/articles/3d-file-viewer/

**Comment by iou16** [comment]
このような質問をして申し訳ありません．
アップするにあたってどのようなファイル名を付けるのが好ましいでしょうか？

**Comment by iou16** [comment]
@DaikiMaekawa アップロードいたしました．
https://github.com/open-rdc/orne_icart_designs/blob/master/designs/2014/rdc_lab/i-Cart_mini_VerCIT.stl

**Comment by DaikiMaekawa** [comment]
確認しました。
