### ISSUE TITLE
T-frogにIMUを取り付ける

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#9]
余っているIMUを確保してT-frogに取り付ける

**Comment by ximomoi** [comment]
余っているIMUを確保、取り付け方を考える必要あり。

**Comment by DaikiMaekawa** [comment]
@yasuohayashibara T-frogにIMUを取り付けると、おそらく研究室内の在庫がゼロになると思います。
予備で1個は確保しておきたいので、追加で購入していただけますか？

**Comment by yasuohayashibara** [comment]
10軸タイプは全部で3台あります．
RDC10などはしばらく動かないと思いますので，取り外していただいて構いません．
※できれば元に戻せるように写真や取り付け方法をデータとして残していただければ助かりますが．．．

**Comment by DaikiMaekawa** [comment]
@yasuohayashibara IMUは野崎先輩から了承を得て、Autonから取り外しました。

**Comment by DaikiMaekawa** [comment]
@ximo112 IMUの取り付け位置はURGのすぐ横にしましょう。
取り付け用の板を製作してください。

**Comment by ximomoi** [comment]
@DaikiMaekawa ミスミフレームに取り付ける場合、専用のナットが必要になると思います。
または、T-frogのURG取り付け用板に拡張を施すかになります。
前者が良いと考えますが、ナットの発注が必要な分取り付けが遅れる可能性があります。

**Comment by ximomoi** [comment]
取り付け方が確定したので取り付け板の製作を行います．

**Comment by ximomoi** [comment]
T-frogにIMUの取り付けが完了しました。

**Comment by ximomoi** [comment]
IMU取り付け完了なのでこのissuesを閉じます。
