### ISSUE TITLE
Testing management script on the real robot

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#90]
他プロジェクトでこちらのソースを流用することになったので、細かい箇所を微調整しています。 https://github.com/open-rdc/icart_mini/pull/78 の修正ではicart_mini_driver.launchを立ち上げた際に従来使用していたypspur_coordinatorの起動スクリプトも同時に立ち上がるようにしました。 今までの状態だとパッケージとしてスクリプトを管理出来ませんので他の用途に流用する際に色々と面倒でした。

ブランチを変更してから実機でテストをお願いします。

**Comment by DaikiMaekawa** [comment]
@Nasupl 取り敢えず担当者を夏迫君にしましたが、誰でも良いので実機で実行してみてください。 今日は開発日だと思いますので、出来れば今日中に結果を書き込んでもらえると助かります。

**Comment by Nasupl** [comment]
@DaikiMaekawa
今日はもう帰宅してしまったので明日午後イチで実験します．申し訳ないです．

**Comment by ximomoi** [comment]
ORNE_betaにてrun-coordinator-processブランチのicart_mini_driver.launchを試しました。

icart_mini_driver.launch
![screenshot from 2015-09-29 20 24 57](https://cloud.githubusercontent.com/assets/7301098/10162940/0ca743c6-66ea-11e5-8a62-6e86e730b397.png)

./icart-mini.sh
![screenshot from 2015-09-29 20 36 50](https://cloud.githubusercontent.com/assets/7301098/10162993/8f9f9148-66ea-11e5-992f-1115336a7944.png)

---

ctrl+cをした時
icart_mini_driver.launch
![screenshot from 2015-09-29 20 23 26](https://cloud.githubusercontent.com/assets/7301098/10163056/011aafa6-66eb-11e5-8a39-c1a7e75cd164.png)

./icart-mini.sh
![screenshot from 2015-09-29 20 30 57](https://cloud.githubusercontent.com/assets/7301098/10163083/37cf9a02-66eb-11e5-8be1-905a188d468c.png)

**Comment by DaikiMaekawa** [comment]
@ximo112  ./icart-mini.shは必要ありません。 この修正でicart_mini_driver.launchを実行した際にセットで起動するようになりました。 一番目のスクリーンショットを見る限り起動には成功しているようですので試しに何かしらの指令を送ってみて実機が無事動いたらOKです。

**Comment by ximomoi** [comment]
teleop_joy.launchにて正常な動作を確認。

**Comment by DaikiMaekawa** [comment]
協力に感謝します。
