### ISSUE TITLE
Why not improve the avoidance performance for dynamic obstacles?

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/orne_navigation#97]
動的障害物の回避性能を向上させるためパラメータのチューニングもしくは新たなパッケージを開発する。

**Comment by DaikiMaekawa** [comment]
同時に障害物への衝突後のリカバリー動作を見直す。

**Comment by DaikiMaekawa** [comment]
徐々に減速するというわけではありませんが、障害物回避時に速度が抑制されていることを実機で確認出来たようです。

**Comment by DaikiMaekawa** [comment]
本番のコース上において、障害物回避前の減速が働き過ぎた結果小さな路面の変化によって車輪がスタックして抜け出せなくなる現象が見られたためmove_slow_and_clearを再び削除した。

**Comment by Nasupl** [comment]
問題が発生していないので閉じます
